/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 22:10:37 GMT 2026
 */

package legacyfighter.dietary;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.function.Function;
import java.util.function.Predicate;
import legacyfighter.dietary.Utils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Utils_ESTest extends Utils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Function<Object, Object> function0 = Function.identity();
      Predicate<String> predicate0 = Utils.distinctByKey((Function<? super String, ?>) function0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Utils utils0 = new Utils();
  }
}
