/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 17:11:13 GMT 2026
 */

package kyungseo.poc.simple.web.security.components.location;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Locale;
import kyungseo.poc.simple.web.security.components.location.OnDifferentLocationLoginEvent;
import kyungseo.poc.simple.web.security.persistence.entity.ds1.NewLocationToken;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OnDifferentLocationLoginEvent_ESTest extends OnDifferentLocationLoginEvent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("j");
      NewLocationToken newLocationToken0 = new NewLocationToken("j");
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, "j", "j", newLocationToken0, (String) null);
      String string0 = onDifferentLocationLoginEvent0.getUsername();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Locale locale0 = Locale.ENGLISH;
      NewLocationToken newLocationToken0 = new NewLocationToken();
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, "", "", newLocationToken0, "-)#M@Ib");
      String string0 = onDifferentLocationLoginEvent0.getUsername();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      NewLocationToken newLocationToken0 = new NewLocationToken();
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent((Locale) null, "ir#K$9radg.KJ*a~HAJ", "ir#K$9radg.KJ*a~HAJ", newLocationToken0, "Context path must not be empty");
      Locale locale0 = onDifferentLocationLoginEvent0.getLocale();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Locale locale0 = Locale.FRANCE;
      NewLocationToken newLocationToken0 = new NewLocationToken();
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, "H| Tj_Q4r>Lta454=;", "H| Tj_Q4r>Lta454=;", newLocationToken0, "H| Tj_Q4r>Lta454=;");
      String string0 = onDifferentLocationLoginEvent0.getIp();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Locale locale0 = Locale.ENGLISH;
      NewLocationToken newLocationToken0 = new NewLocationToken();
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, "", "", newLocationToken0, "-)#M@Ib");
      String string0 = onDifferentLocationLoginEvent0.getIp();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("j");
      NewLocationToken newLocationToken0 = new NewLocationToken("j");
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, "j", "j", newLocationToken0, (String) null);
      String string0 = onDifferentLocationLoginEvent0.getAppUrl();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      NewLocationToken newLocationToken0 = new NewLocationToken();
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent((Locale) null, "", "", newLocationToken0, "");
      String string0 = onDifferentLocationLoginEvent0.getAppUrl();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Locale locale0 = new Locale("^_)F?v{CUNXhq", "^_)F?v{CUNXhq");
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = null;
      try {
        onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, "^_)F?v{CUNXhq", "^_)F?v{CUNXhq", (NewLocationToken) null, "^_)F?v{CUNXhq");
      } catch(IllegalArgumentException e) {
         //
         // null source
         //
         verifyException("java.util.EventObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Locale locale0 = Locale.FRENCH;
      NewLocationToken newLocationToken0 = new NewLocationToken("}");
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, (String) null, (String) null, newLocationToken0, "<(iBo");
      String string0 = onDifferentLocationLoginEvent0.getUsername();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Locale locale0 = Locale.FRENCH;
      NewLocationToken newLocationToken0 = new NewLocationToken("}");
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, (String) null, (String) null, newLocationToken0, "<(iBo");
      String string0 = onDifferentLocationLoginEvent0.getAppUrl();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Locale locale0 = Locale.FRENCH;
      NewLocationToken newLocationToken0 = new NewLocationToken("}");
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, (String) null, (String) null, newLocationToken0, "<(iBo");
      Locale locale1 = onDifferentLocationLoginEvent0.getLocale();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Locale locale0 = Locale.FRENCH;
      NewLocationToken newLocationToken0 = new NewLocationToken("}");
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent(locale0, (String) null, (String) null, newLocationToken0, "<(iBo");
      String string0 = onDifferentLocationLoginEvent0.getIp();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      NewLocationToken newLocationToken0 = new NewLocationToken("H&!OP5T|s!-#_;");
      OnDifferentLocationLoginEvent onDifferentLocationLoginEvent0 = new OnDifferentLocationLoginEvent((Locale) null, "H&!OP5T|s!-#_;", "H&!OP5T|s!-#_;", newLocationToken0, "H&!OP5T|s!-#_;");
      NewLocationToken newLocationToken1 = onDifferentLocationLoginEvent0.getToken();
  }
}
