/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 12:44:34 GMT 2026
 */

package com.acme.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.acme.client.DeleteBookAuthorsBooksProjection;
import com.acme.client.DeleteBookAuthorsBooksPublishingFormatProjection;
import com.acme.client.DeleteBookAuthorsProjection;
import com.acme.client.DeleteBookProjectionRoot;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DeleteBookAuthorsBooksPublishingFormatProjection_ESTest extends DeleteBookAuthorsBooksPublishingFormatProjection_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DeleteBookProjectionRoot deleteBookProjectionRoot0 = new DeleteBookProjectionRoot();
      DeleteBookAuthorsProjection deleteBookAuthorsProjection0 = new DeleteBookAuthorsProjection(deleteBookProjectionRoot0, deleteBookProjectionRoot0);
      DeleteBookAuthorsBooksProjection deleteBookAuthorsBooksProjection0 = new DeleteBookAuthorsBooksProjection(deleteBookAuthorsProjection0, deleteBookProjectionRoot0);
      DeleteBookAuthorsBooksPublishingFormatProjection deleteBookAuthorsBooksPublishingFormatProjection0 = new DeleteBookAuthorsBooksPublishingFormatProjection(deleteBookAuthorsBooksProjection0, deleteBookProjectionRoot0);
      DeleteBookAuthorsBooksPublishingFormatProjection deleteBookAuthorsBooksPublishingFormatProjection1 = deleteBookAuthorsBooksPublishingFormatProjection0.formatName();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DeleteBookProjectionRoot deleteBookProjectionRoot0 = new DeleteBookProjectionRoot();
      DeleteBookAuthorsBooksPublishingFormatProjection deleteBookAuthorsBooksPublishingFormatProjection0 = new DeleteBookAuthorsBooksPublishingFormatProjection((DeleteBookAuthorsBooksProjection) null, deleteBookProjectionRoot0);
      DeleteBookAuthorsBooksPublishingFormatProjection deleteBookAuthorsBooksPublishingFormatProjection1 = deleteBookAuthorsBooksPublishingFormatProjection0.id();
  }
}
