/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 19 03:23:04 GMT 2026
 */

package ozi.app.printer.services.adminService;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ozi.app.printer.data.dtos.requests.AdminCreationRequest;
import ozi.app.printer.services.adminService.AdminServicesImpl;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AdminServicesImpl_ESTest extends AdminServicesImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      // Undeclared exception!
      try { 
        adminServicesImpl0.getAllAdmins();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      // Undeclared exception!
      try { 
        adminServicesImpl0.getAdminById("&N$u>6VU?");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      // Undeclared exception!
      try { 
        adminServicesImpl0.getAdminByEmail("+`");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      // Undeclared exception!
      try { 
        adminServicesImpl0.deleteAllAdmins();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      AdminCreationRequest adminCreationRequest0 = new AdminCreationRequest();
      adminCreationRequest0.setPassword("");
      adminCreationRequest0.setEmail("");
      adminCreationRequest0.setFirstName("");
      adminCreationRequest0.setPhoneNumber("");
      adminCreationRequest0.setLastName("");
      // Undeclared exception!
      try { 
        adminServicesImpl0.createAdmin(adminCreationRequest0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      AdminCreationRequest adminCreationRequest0 = new AdminCreationRequest();
      adminCreationRequest0.setEmail("");
      adminCreationRequest0.setFirstName("");
      adminCreationRequest0.setPhoneNumber("");
      adminCreationRequest0.setLastName("");
      try { 
        adminServicesImpl0.createAdmin(adminCreationRequest0);
      } catch(Exception e) {
         //
         // These details are incomplete
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      AdminCreationRequest adminCreationRequest0 = new AdminCreationRequest();
      adminCreationRequest0.setEmail("");
      adminCreationRequest0.setFirstName("");
      adminCreationRequest0.setLastName("");
      try { 
        adminServicesImpl0.createAdmin(adminCreationRequest0);
      } catch(Exception e) {
         //
         // These details are incomplete
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      AdminCreationRequest adminCreationRequest0 = new AdminCreationRequest();
      adminCreationRequest0.setFirstName("");
      adminCreationRequest0.setLastName("");
      try { 
        adminServicesImpl0.createAdmin(adminCreationRequest0);
      } catch(Exception e) {
         //
         // These details are incomplete
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      AdminCreationRequest adminCreationRequest0 = new AdminCreationRequest();
      adminCreationRequest0.setPassword("");
      try { 
        adminServicesImpl0.createAdmin(adminCreationRequest0);
      } catch(Exception e) {
         //
         // These details are incomplete
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AdminCreationRequest adminCreationRequest0 = new AdminCreationRequest();
      adminCreationRequest0.setLastName("SGt^4hnEA");
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      try { 
        adminServicesImpl0.createAdmin(adminCreationRequest0);
      } catch(Exception e) {
         //
         // These details are incomplete
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      AdminCreationRequest adminCreationRequest0 = new AdminCreationRequest();
      adminCreationRequest0.setFirstName("GqBsfYB}'eZaD(2n:7");
      try { 
        adminServicesImpl0.createAdmin(adminCreationRequest0);
      } catch(Exception e) {
         //
         // These details are incomplete
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AdminServicesImpl adminServicesImpl0 = new AdminServicesImpl();
      // Undeclared exception!
      try { 
        adminServicesImpl0.deleteAdminById((String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ozi.app.printer.services.adminService.AdminServicesImpl", e);
      }
  }
}
