/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 14:00:33 GMT 2026
 */

package org.apache.solr.suggest.analyzing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.Stack;
import java.util.TreeSet;
import java.util.concurrent.ForkJoinPool;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.index.LeafReader;
import org.apache.lucene.index.LeafReaderContext;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.SearcherFactory;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.search.similarities.AnotherCustomAutocompleteSimilarity;
import org.apache.lucene.search.similarities.Similarity;
import org.apache.lucene.search.suggest.InputIterator;
import org.apache.lucene.store.DataInput;
import org.apache.lucene.store.DataOutput;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.Lock;
import org.apache.lucene.util.Accountable;
import org.apache.lucene.util.BytesRef;
import org.apache.lucene.util.CharsRef;
import org.apache.solr.spelling.suggest.LocalSuggesterOptions;
import org.apache.solr.spelling.suggest.SuggesterOptions;
import org.apache.solr.suggest.analyzing.AutocompleteSuggester;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AutocompleteSuggester_ESTest extends AutocompleteSuggester_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      Integer integer0 = Integer.getInteger("steld=\"", 7724);
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 167, true, true, map0, (-184.19731F), integer0, anotherCustomAutocompleteSimilarity0, true);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.addPrefixMatch((StringBuilder) null, "org.apa", "", "%-uA3)n");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn((Object) stringArray0, (Object) stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(0);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1120, false, true, map0, 1.0F, integer0, anotherCustomAutocompleteSimilarity0, false);
      LinkedHashSet<BytesRef> linkedHashSet0 = new LinkedHashSet<BytesRef>();
      // Undeclared exception!
      try { 
        autocompleteSuggester0.lookup((CharSequence) "%-uA3)n", (Set<BytesRef>) linkedHashSet0, true, 1120);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      Integer integer0 = Integer.getInteger("", (-1643));
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      AutocompleteSuggester autocompleteSuggester0 = null;
      try {
        autocompleteSuggester0 = new AutocompleteSuggester((Directory) null, 0, false, true, map0, 0, integer0, anotherCustomAutocompleteSimilarity0, false);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(7724);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1.0F, integer0, anotherCustomAutocompleteSimilarity0, false);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "%-uA3)n");
      autocompleteSuggester0.addWholeMatch(stringBuilder0, "Ihw~ 5v 8+!P7kY", "org.apache");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      Integer integer0 = Integer.getInteger("steld=\"", 7724);
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 167, true, true, map0, (-184.19731F), integer0, anotherCustomAutocompleteSimilarity0, true);
      StringBuilder stringBuilder0 = new StringBuilder();
      autocompleteSuggester0.addPrefixMatch(stringBuilder0, "+_dj-1+55ZM}w", ",docCount=", "minVersion must be set when createdVersionMajor is >= 7");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      Integer integer0 = Integer.getInteger("%-uA3)n", 7724);
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 3501, true, true, map0, 3501, integer0, anotherCustomAutocompleteSimilarity0, true);
      StringBuilder stringBuilder0 = new StringBuilder("d[pT}SH:#}P");
      autocompleteSuggester0.addNonMatch(stringBuilder0, "d[pT}SH:#}P");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      Integer integer0 = Integer.getInteger("%-uA3)n", 7724);
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 3501, true, true, map0, 3501, integer0, anotherCustomAutocompleteSimilarity0, true);
      InputIterator inputIterator0 = mock(InputIterator.class, new ViolatedAssumptionAnswer());
      autocompleteSuggester0.build(inputIterator0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "87d";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1088);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1088, true, true, hashMap0, 1088, integer0, anotherCustomAutocompleteSimilarity0, true);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.lookup((LocalSuggesterOptions) null, true);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "{d";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, false, false, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, false);
      ArrayList<LeafReaderContext> arrayList0 = new ArrayList<LeafReaderContext>(842);
      LeafReader leafReader0 = mock(LeafReader.class, new ViolatedAssumptionAnswer());
      LeafReaderContext leafReaderContext0 = mock(LeafReaderContext.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(leafReaderContext0).leaves();
      doReturn(leafReader0).when(leafReaderContext0).reader();
      ForkJoinPool forkJoinPool0 = ForkJoinPool.commonPool();
      IndexSearcher indexSearcher0 = new IndexSearcher(leafReaderContext0, forkJoinPool0);
      // Undeclared exception!
      autocompleteSuggester0.lookup(indexSearcher0, (CharSequence) "{d", 10129, false, false, false);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, false, false, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, false);
      Stack<LeafReaderContext> stack0 = new Stack<LeafReaderContext>();
      LeafReader leafReader0 = mock(LeafReader.class, new ViolatedAssumptionAnswer());
      LeafReaderContext leafReaderContext0 = mock(LeafReaderContext.class, new ViolatedAssumptionAnswer());
      doReturn(stack0).when(leafReaderContext0).leaves();
      doReturn(leafReader0).when(leafReaderContext0).reader();
      ForkJoinPool forkJoinPool0 = ForkJoinPool.commonPool();
      IndexSearcher indexSearcher0 = new IndexSearcher(leafReaderContext0, forkJoinPool0);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.lookup(indexSearcher0, (CharSequence) "", 942, false, false, true);
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1133);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1133, true, true, map0, 1133, integer0, anotherCustomAutocompleteSimilarity0, true);
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      // Undeclared exception!
      try { 
        autocompleteSuggester0.highlight((String) null, set0, "@(Zorg.apache.lucene.analysis.tokenattributes.PackedTokenAttributeImpl@0000000006");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.StringReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, (Map<String, String>) null, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.getText((LeafReaderContext) null, 16, "%-uA3)n");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      HashSet<String> hashSet0 = new HashSet<String>();
      // Undeclared exception!
      try { 
        autocompleteSuggester0.createResults((IndexSearcher) null, (TopDocs) null, false, hashSet0, "id", true);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.addWholeMatch((StringBuilder) null, "%-uA3)n", "%-uA3)n");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "(-i";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(23);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 23, true, true, map0, 23, integer0, anotherCustomAutocompleteSimilarity0, true);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.addPrefixMatch((StringBuilder) null, "(-i", "contextField", "");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1133);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1133, true, true, map0, 1133, integer0, anotherCustomAutocompleteSimilarity0, true);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.addNonMatch((StringBuilder) null, "org.apache.lucene.a");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn((Object) stringArray0, (Object) null).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.lookup((IndexSearcher) null, (CharSequence) "id", 361, true, true, true);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn((Object) stringArray0, (Object) stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.lookup2("id", 1126, true, true);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = ",i?";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(23);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 23, true, true, map0, 23, integer0, anotherCustomAutocompleteSimilarity0, true);
      long long0 = autocompleteSuggester0.getCount();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "f";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = Integer.getInteger("f", 1129);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1129, true, true, map0, 1129, integer0, anotherCustomAutocompleteSimilarity0, true);
      Collection<Accountable> collection0 = autocompleteSuggester0.getChildResources();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      long long0 = autocompleteSuggester0.ramBytesUsed();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1133);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1133, true, true, map0, 1133, integer0, anotherCustomAutocompleteSimilarity0, true);
      autocompleteSuggester0.close();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Locale locale0 = Locale.TAIWAN;
      Set<String> set0 = locale0.getUnicodeLocaleKeys();
      Lock lock0 = mock(Lock.class, new ViolatedAssumptionAnswer());
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(set0).when(directory0).getPendingDeletions();
      doReturn((Object) stringArray0, (Object) stringArray0, (Object) stringArray0).when(directory0).listAll();
      doReturn(lock0).when(directory0).obtainLock(anyString());
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      IndexWriterConfig indexWriterConfig0 = new IndexWriterConfig();
      IndexWriter indexWriter0 = new IndexWriter(directory0, indexWriterConfig0);
      DirectoryReader directoryReader0 = DirectoryReader.open(indexWriter0);
      Directory directory1 = directoryReader0.directory();
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory1, 715827874, false, false, map0, 6511.6943F, (Integer) indexWriter0.MAX_DOCS, anotherCustomAutocompleteSimilarity0, false);
      TreeSet<String> treeSet0 = new TreeSet<String>();
      Object object0 = autocompleteSuggester0.highlight("~R*bV<6w4A#__%l6k", treeSet0, "");
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      TreeSet<String> treeSet0 = new TreeSet<String>();
      Object object0 = autocompleteSuggester0.highlight("id", treeSet0, "id");
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      TreeSet<String> treeSet0 = new TreeSet<String>();
      Object object0 = autocompleteSuggester0.highlight("id", treeSet0, (String) null);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.highlight("id", (Set<String>) null, "id");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      BytesRef bytesRef0 = autocompleteSuggester0.getText((LeafReaderContext) null, 1126, "id");
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, false, false, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, false);
      ArrayList<LeafReaderContext> arrayList0 = new ArrayList<LeafReaderContext>();
      LeafReader leafReader0 = mock(LeafReader.class, new ViolatedAssumptionAnswer());
      LeafReaderContext leafReaderContext0 = mock(LeafReaderContext.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(leafReaderContext0).leaves();
      doReturn(leafReader0).when(leafReaderContext0).reader();
      ForkJoinPool forkJoinPool0 = ForkJoinPool.commonPool();
      IndexSearcher indexSearcher0 = new IndexSearcher(leafReaderContext0, forkJoinPool0);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.lookup(indexSearcher0, (CharSequence) "id", 0, true, false, false);
      } catch(IllegalArgumentException e) {
         //
         // numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count
         //
         verifyException("org.apache.lucene.search.TopScoreDocCollector", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Locale locale0 = Locale.TAIWAN;
      Set<String> set0 = locale0.getUnicodeLocaleKeys();
      Lock lock0 = mock(Lock.class, new ViolatedAssumptionAnswer());
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(set0).when(directory0).getPendingDeletions();
      doReturn((Object) stringArray0, (Object) stringArray0, (Object) stringArray0).when(directory0).listAll();
      doReturn(lock0).when(directory0).obtainLock(anyString());
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      IndexWriterConfig indexWriterConfig0 = new IndexWriterConfig();
      IndexWriter indexWriter0 = new IndexWriter(directory0, indexWriterConfig0);
      DirectoryReader directoryReader0 = DirectoryReader.open(indexWriter0);
      Directory directory1 = directoryReader0.directory();
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory1, 715827874, false, false, map0, 6511.6943F, (Integer) indexWriterConfig0.DISABLE_AUTO_FLUSH, anotherCustomAutocompleteSimilarity0, false);
      SearcherFactory searcherFactory0 = new SearcherFactory();
      IndexSearcher indexSearcher0 = searcherFactory0.newSearcher(directoryReader0, directoryReader0);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.lookup(indexSearcher0, (CharSequence) "source", 445, false, true, true);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      Integer integer0 = new Integer((-1315));
      Similarity similarity0 = IndexSearcher.getDefaultSimilarity();
      AutocompleteSuggester autocompleteSuggester0 = null;
      try {
        autocompleteSuggester0 = new AutocompleteSuggester((Directory) null, (-1315), true, false, hashMap0, (-1315), integer0, similarity0, true);
      } catch(IllegalArgumentException e) {
         //
         // minPrefixChars must be >= 0; got: -1315
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "id";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn((Object) stringArray0, (Object) stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      SuggesterOptions suggesterOptions0 = new SuggesterOptions((CharsRef) null, 1126, "id", true, true);
      LocalSuggesterOptions localSuggesterOptions0 = new LocalSuggesterOptions(suggesterOptions0);
      // Undeclared exception!
      try { 
        autocompleteSuggester0.lookup(localSuggesterOptions0, false);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.solr.suggest.analyzing.AutocompleteSuggester", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      DataInput dataInput0 = mock(DataInput.class, new ViolatedAssumptionAnswer());
      boolean boolean0 = autocompleteSuggester0.load(dataInput0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "%-uA3)n";
      Directory directory0 = mock(Directory.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(directory0).listAll();
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      AnotherCustomAutocompleteSimilarity anotherCustomAutocompleteSimilarity0 = new AnotherCustomAutocompleteSimilarity();
      Integer integer0 = new Integer(1126);
      AutocompleteSuggester autocompleteSuggester0 = new AutocompleteSuggester(directory0, 1126, true, true, map0, 1126, integer0, anotherCustomAutocompleteSimilarity0, true);
      DataOutput dataOutput0 = mock(DataOutput.class, new ViolatedAssumptionAnswer());
      boolean boolean0 = autocompleteSuggester0.store(dataOutput0);
  }
}
