/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 10 19:11:47 GMT 2026
 */

package com.github.bhlangonijr.chesslib.game;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.bhlangonijr.chesslib.game.MovePerTime;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MovePerTime_ESTest extends MovePerTime_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MovePerTime movePerTime0 = new MovePerTime();
      movePerTime0.setMilliseconds((-4824));
      String string0 = movePerTime0.toString();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MovePerTime movePerTime0 = new MovePerTime();
      movePerTime0.setMilliseconds((-4824));
      String string0 = movePerTime0.toPGNString();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MovePerTime movePerTime0 = new MovePerTime();
      movePerTime0.setMoves(1);
      int int0 = movePerTime0.getMoves();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MovePerTime movePerTime0 = new MovePerTime();
      movePerTime0.setMoves((-4824));
      int int0 = movePerTime0.getMoves();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MovePerTime movePerTime0 = new MovePerTime();
      long long0 = movePerTime0.getMilliseconds();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MovePerTime movePerTime0 = new MovePerTime(0, (-2429L));
      movePerTime0.setMilliseconds(147L);
      long long0 = movePerTime0.getMilliseconds();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MovePerTime movePerTime0 = new MovePerTime(0, (-2429L));
      long long0 = movePerTime0.getMilliseconds();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MovePerTime movePerTime0 = new MovePerTime(0, (-2429L));
      int int0 = movePerTime0.getMoves();
  }
}
