/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Aug 10 19:07:25 GMT 2026
 */

package com.github.bhlangonijr.chesslib.game;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Round_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.github.bhlangonijr.chesslib.game.Round"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/suelenfelix/TCC/teste/analise-geracao-testes/projects/bhlangonijr_chesslib"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Round_ESTest_scaffolding.class.getClassLoader() ,
      "com.github.bhlangonijr.chesslib.Side",
      "com.github.bhlangonijr.chesslib.move.MoveException",
      "org.apache.commons.lang3.StringUtils",
      "com.github.bhlangonijr.chesslib.util.StringUtil",
      "com.github.bhlangonijr.chesslib.BoardEventType",
      "com.github.bhlangonijr.chesslib.util.LargeFile$FileIterator",
      "com.github.bhlangonijr.chesslib.MoveBackup",
      "com.github.bhlangonijr.chesslib.pgn.PgnException",
      "com.github.bhlangonijr.chesslib.game.Round",
      "com.github.bhlangonijr.chesslib.game.VariationType",
      "com.github.bhlangonijr.chesslib.Board",
      "com.github.bhlangonijr.chesslib.game.GameContext",
      "com.github.bhlangonijr.chesslib.PieceType",
      "com.github.bhlangonijr.chesslib.game.TimeControl",
      "com.github.bhlangonijr.chesslib.DiagonalA1H8",
      "com.github.bhlangonijr.chesslib.game.Game",
      "com.github.bhlangonijr.chesslib.pgn.GameLoader",
      "com.github.bhlangonijr.chesslib.game.TimeControlType",
      "com.github.bhlangonijr.chesslib.Constants",
      "com.github.bhlangonijr.chesslib.pgn.PgnProperty",
      "com.github.bhlangonijr.chesslib.pgn.PgnIterator$GameIterator",
      "com.github.bhlangonijr.chesslib.game.GameMode",
      "com.github.bhlangonijr.chesslib.Bitboard",
      "com.github.bhlangonijr.chesslib.File",
      "com.github.bhlangonijr.chesslib.BoardEvent",
      "com.github.bhlangonijr.chesslib.game.GenericPlayer",
      "com.github.bhlangonijr.chesslib.Square",
      "com.github.bhlangonijr.chesslib.Piece",
      "com.github.bhlangonijr.chesslib.util.XorShiftRandom",
      "com.github.bhlangonijr.chesslib.move.Move",
      "com.github.bhlangonijr.chesslib.move.MoveConversionException",
      "com.github.bhlangonijr.chesslib.pgn.PgnIterator",
      "com.github.bhlangonijr.chesslib.CastleRight",
      "com.github.bhlangonijr.chesslib.util.LargeFile",
      "com.github.bhlangonijr.chesslib.pgn.PgnHolder",
      "com.github.bhlangonijr.chesslib.pgn.GameLoader$PgnTempContainer",
      "com.github.bhlangonijr.chesslib.move.MoveList",
      "com.github.bhlangonijr.chesslib.game.Termination",
      "com.github.bhlangonijr.chesslib.game.EventType",
      "com.github.bhlangonijr.chesslib.game.PlayerType",
      "com.github.bhlangonijr.chesslib.game.Player",
      "com.github.bhlangonijr.chesslib.game.MovePerTime",
      "com.github.bhlangonijr.chesslib.DiagonalH1A8",
      "com.github.bhlangonijr.chesslib.BoardEventListener",
      "com.github.bhlangonijr.chesslib.pgn.PgnLoadListener",
      "com.github.bhlangonijr.chesslib.Board$1",
      "com.github.bhlangonijr.chesslib.Rank",
      "com.github.bhlangonijr.chesslib.game.GameResult",
      "com.github.bhlangonijr.chesslib.game.Event"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Round_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.github.bhlangonijr.chesslib.game.Round",
      "com.github.bhlangonijr.chesslib.game.GameContext",
      "com.github.bhlangonijr.chesslib.move.Move",
      "com.github.bhlangonijr.chesslib.PieceType",
      "com.github.bhlangonijr.chesslib.Piece",
      "com.github.bhlangonijr.chesslib.Constants",
      "com.github.bhlangonijr.chesslib.game.Game",
      "com.github.bhlangonijr.chesslib.move.MoveList",
      "com.github.bhlangonijr.chesslib.game.GameResult",
      "com.github.bhlangonijr.chesslib.util.XorShiftRandom",
      "com.github.bhlangonijr.chesslib.Board",
      "com.github.bhlangonijr.chesslib.BoardEventType",
      "com.github.bhlangonijr.chesslib.Board$1",
      "com.github.bhlangonijr.chesslib.DiagonalA1H8",
      "com.github.bhlangonijr.chesslib.DiagonalH1A8",
      "com.github.bhlangonijr.chesslib.Bitboard",
      "org.apache.commons.lang3.StringUtils",
      "com.github.bhlangonijr.chesslib.game.Event",
      "com.github.bhlangonijr.chesslib.pgn.PgnHolder",
      "com.github.bhlangonijr.chesslib.game.TimeControl",
      "com.github.bhlangonijr.chesslib.pgn.PgnIterator",
      "com.github.bhlangonijr.chesslib.util.LargeFile",
      "com.github.bhlangonijr.chesslib.pgn.GameLoader",
      "com.github.bhlangonijr.chesslib.pgn.GameLoader$PgnTempContainer",
      "com.github.bhlangonijr.chesslib.game.GenericPlayer",
      "com.github.bhlangonijr.chesslib.game.PlayerType",
      "com.github.bhlangonijr.chesslib.pgn.PgnProperty",
      "com.github.bhlangonijr.chesslib.pgn.PgnIterator$GameIterator",
      "com.github.bhlangonijr.chesslib.util.LargeFile$FileIterator",
      "com.github.bhlangonijr.chesslib.util.StringUtil",
      "com.github.bhlangonijr.chesslib.move.MoveConversionException"
    );
  }
}
