/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 01:49:57 GMT 2026
 */

package com.automation.xmldoclet.xjc;

import org.junit.Test;
import static org.junit.Assert.*;
import com.automation.xmldoclet.xjc.Annotation;
import com.automation.xmldoclet.xjc.AnnotationElement;
import com.automation.xmldoclet.xjc.AnnotationInstance;
import com.automation.xmldoclet.xjc.TagInfo;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Annotation_ESTest extends Annotation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      LinkedList<TagInfo> linkedList0 = new LinkedList<TagInfo>();
      annotation0.tag = (List<TagInfo>) linkedList0;
      TagInfo tagInfo0 = new TagInfo();
      boolean boolean0 = linkedList0.offerLast(tagInfo0);
      List<TagInfo> list0 = annotation0.getTag();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      annotation0.setScope("N`+GlEnzPD^5#KuASXg");
      String string0 = annotation0.getScope();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      annotation0.setQualified("com.automation.xmldoclet.xjc.TagInfo");
      String string0 = annotation0.getQualified();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      annotation0.setQualified("");
      String string0 = annotation0.getQualified();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      annotation0.name = "N`+GlEnzPD^5#KuASXg";
      String string0 = annotation0.getName();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      annotation0.name = "";
      String string0 = annotation0.getName();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      LinkedList<AnnotationElement> linkedList0 = new LinkedList<AnnotationElement>();
      AnnotationElement annotationElement0 = new AnnotationElement();
      boolean boolean0 = linkedList0.add(annotationElement0);
      annotation0.element = (List<AnnotationElement>) linkedList0;
      List<AnnotationElement> list0 = annotation0.getElement();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      annotation0.comment = "N`+GlEnzPD^5#KuASXg";
      String string0 = annotation0.getComment();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      annotation0.setComment("");
      String string0 = annotation0.getComment();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      AnnotationInstance[] annotationInstanceArray0 = new AnnotationInstance[7];
      AnnotationInstance annotationInstance0 = new AnnotationInstance();
      annotationInstanceArray0[0] = annotationInstance0;
      annotationInstanceArray0[1] = annotationInstanceArray0[0];
      annotationInstanceArray0[2] = annotationInstance0;
      annotationInstanceArray0[3] = annotationInstance0;
      annotationInstanceArray0[4] = annotationInstance0;
      annotationInstanceArray0[5] = annotationInstance0;
      annotationInstanceArray0[6] = annotationInstance0;
      List<AnnotationInstance> list0 = List.of(annotationInstanceArray0);
      LinkedList<AnnotationInstance> linkedList0 = new LinkedList<AnnotationInstance>(list0);
      annotation0.annotation = (List<AnnotationInstance>) linkedList0;
      List<AnnotationInstance> list1 = annotation0.getAnnotation();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      boolean boolean0 = annotation0.isIncluded();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      Boolean boolean0 = Boolean.valueOf(false);
      annotation0.included = boolean0;
      boolean boolean1 = annotation0.isIncluded();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      List<AnnotationInstance> list0 = annotation0.getAnnotation();
      List<AnnotationInstance> list1 = annotation0.getAnnotation();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      List<AnnotationElement> list0 = annotation0.getElement();
      List<AnnotationElement> list1 = annotation0.getElement();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      List<TagInfo> list0 = annotation0.getTag();
      List<TagInfo> list1 = annotation0.getTag();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      Boolean boolean0 = Boolean.valueOf(false);
      annotation0.setIncluded(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      String string0 = annotation0.getScope();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      annotation0.setScope("");
      String string0 = annotation0.getScope();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      String string0 = annotation0.getQualified();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      String string0 = annotation0.getName();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      String string0 = annotation0.getComment();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Annotation annotation0 = new Annotation();
      annotation0.setName("d2jPxHy9");
  }
}
