/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 01:46:41 GMT 2026
 */

package com.automation.xmldoclet.xjc;

import org.junit.Test;
import static org.junit.Assert.*;
import com.automation.xmldoclet.xjc.AnnotationInstance;
import com.automation.xmldoclet.xjc.Field;
import com.automation.xmldoclet.xjc.Interface;
import com.automation.xmldoclet.xjc.Method;
import com.automation.xmldoclet.xjc.TagInfo;
import com.automation.xmldoclet.xjc.TypeInfo;
import com.automation.xmldoclet.xjc.TypeParameter;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Interface_ESTest extends Interface_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Interface interface0 = new Interface();
      Boolean boolean0 = Boolean.valueOf("");
      interface0.setIncluded(boolean0);
      boolean boolean1 = interface0.isIncluded();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Interface interface0 = new Interface();
      TagInfo tagInfo0 = new TagInfo();
      List<TagInfo> list0 = List.of(tagInfo0);
      LinkedList<TagInfo> linkedList0 = new LinkedList<TagInfo>(list0);
      interface0.tag = (List<TagInfo>) linkedList0;
      List<TagInfo> list1 = interface0.getTag();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.setScope("l'4kX>ki?g");
      String string0 = interface0.getScope();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.qualified = "&CO=#&uxc;'b29";
      String string0 = interface0.getQualified();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.qualified = "";
      String string0 = interface0.getQualified();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.name = "com.automation.xmldoclet.xjc.Field";
      String string0 = interface0.getName();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.name = "";
      String string0 = interface0.getName();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Interface interface0 = new Interface();
      LinkedList<Method> linkedList0 = new LinkedList<Method>();
      interface0.method = (List<Method>) linkedList0;
      boolean boolean0 = linkedList0.offerFirst((Method) null);
      List<Method> list0 = interface0.getMethod();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Interface interface0 = new Interface();
      LinkedList<TypeInfo> linkedList0 = new LinkedList<TypeInfo>();
      interface0._interface = (List<TypeInfo>) linkedList0;
      TypeInfo typeInfo0 = new TypeInfo();
      boolean boolean0 = linkedList0.add(typeInfo0);
      List<TypeInfo> list0 = interface0.getInterface();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Interface interface0 = new Interface();
      LinkedList<TypeParameter> linkedList0 = new LinkedList<TypeParameter>();
      TypeParameter typeParameter0 = new TypeParameter();
      boolean boolean0 = linkedList0.add(typeParameter0);
      interface0.generic = (List<TypeParameter>) linkedList0;
      List<TypeParameter> list0 = interface0.getGeneric();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Interface interface0 = new Interface();
      LinkedList<Field> linkedList0 = new LinkedList<Field>();
      Field field0 = new Field();
      boolean boolean0 = linkedList0.add(field0);
      interface0.field = (List<Field>) linkedList0;
      List<Field> list0 = interface0.getField();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.setComment("com.automation.xmldoclet.xjc.Field");
      String string0 = interface0.getComment();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.comment = "@DpE=>t<H~";
      interface0.comment = "";
      String string0 = interface0.getComment();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Interface interface0 = new Interface();
      LinkedList<AnnotationInstance> linkedList0 = new LinkedList<AnnotationInstance>();
      interface0.annotation = (List<AnnotationInstance>) linkedList0;
      AnnotationInstance annotationInstance0 = new AnnotationInstance();
      boolean boolean0 = linkedList0.add(annotationInstance0);
      List<AnnotationInstance> list0 = interface0.getAnnotation();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Interface interface0 = new Interface();
      boolean boolean0 = interface0.isIncluded();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Interface interface0 = new Interface();
      List<Field> list0 = interface0.getField();
      List<Field> list1 = interface0.getField();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Interface interface0 = new Interface();
      List<AnnotationInstance> list0 = interface0.getAnnotation();
      List<AnnotationInstance> list1 = interface0.getAnnotation();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Interface interface0 = new Interface();
      List<Method> list0 = interface0.getMethod();
      List<Method> list1 = interface0.getMethod();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Interface interface0 = new Interface();
      List<TypeInfo> list0 = interface0.getInterface();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Interface interface0 = new Interface();
      List<TypeParameter> list0 = interface0.getGeneric();
      List<TypeParameter> list1 = interface0.getGeneric();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Interface interface0 = new Interface();
      List<TagInfo> list0 = interface0.getTag();
      List<TagInfo> list1 = interface0.getTag();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.setName("");
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.setScope("");
      String string0 = interface0.getScope();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Interface interface0 = new Interface();
      String string0 = interface0.getName();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Interface interface0 = new Interface();
      String string0 = interface0.getComment();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Interface interface0 = new Interface();
      String string0 = interface0.getScope();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Interface interface0 = new Interface();
      String string0 = interface0.getQualified();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Interface interface0 = new Interface();
      interface0.setQualified("d+pKGytjNIwz3n_g7T");
  }
}
