/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 17:30:31 GMT 2026
 */

package net.alenzen.a2l;

import org.junit.Test;
import static org.junit.Assert.*;
import net.alenzen.a2l.VariantCoding;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class A2LSerializer_ESTest extends A2LSerializer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VariantCoding variantCoding0 = new VariantCoding();
      String string0 = variantCoding0.toString();
  }
}
