/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 18:25:54 GMT 2026
 */

package net.alenzen.a2l;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import net.alenzen.a2l.IA2LWriteable;
import net.alenzen.a2l.IAsap2TreeElement;
import net.alenzen.a2l.OffsetXYZ45;
import net.alenzen.a2l.enums.DataType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OffsetXYZ45_ESTest extends OffsetXYZ45_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      offsetXYZ45_0.setPosition(2287L);
      OffsetXYZ45 offsetXYZ45_1 = new OffsetXYZ45();
      boolean boolean0 = offsetXYZ45_1.equals(offsetXYZ45_0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      long long0 = offsetXYZ45_0.getPosition();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      offsetXYZ45_0.setPosition(73L);
      long long0 = offsetXYZ45_0.getPosition();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      offsetXYZ45_0.setPosition((-1L));
      long long0 = offsetXYZ45_0.getPosition();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      DataType dataType0 = offsetXYZ45_0.getDataType();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      DataType dataType0 = DataType.UBYTE;
      offsetXYZ45_0.setDataType(dataType0);
      DataType dataType1 = offsetXYZ45_0.getDataType();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      OffsetXYZ45 offsetXYZ45_1 = new OffsetXYZ45();
      DataType dataType0 = DataType.A_UINT64;
      offsetXYZ45_1.setDataType(dataType0);
      boolean boolean0 = offsetXYZ45_1.equals(offsetXYZ45_0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      OffsetXYZ45 offsetXYZ45_1 = new OffsetXYZ45();
      offsetXYZ45_1.setPosition((-390L));
      boolean boolean0 = offsetXYZ45_0.equals(offsetXYZ45_1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      boolean boolean0 = offsetXYZ45_0.equals("{\n  \"position\" : 0,\n  \"dataType\" : \"UBYTE\"\n}");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      boolean boolean0 = offsetXYZ45_0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      boolean boolean0 = offsetXYZ45_0.equals(offsetXYZ45_0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      OffsetXYZ45 offsetXYZ45_1 = new OffsetXYZ45();
      boolean boolean0 = offsetXYZ45_0.equals(offsetXYZ45_1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      List<IAsap2TreeElement> list0 = offsetXYZ45_0.collectSubNodes();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      IA2LWriteable iA2LWriteable0 = offsetXYZ45_0.getA2lWritable("");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      OffsetXYZ45 offsetXYZ45_0 = new OffsetXYZ45();
      int int0 = offsetXYZ45_0.hashCode();
  }
}
