/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 11:41:47 GMT 2026
 */

package com.analytics.covid19.REST;

import org.junit.Test;
import static org.junit.Assert.*;
import com.analytics.covid19.REST.Request;
import java.time.LocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Request_ESTest extends Request_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Request request0 = new Request("", localDate0, localDate0);
      LocalDate localDate1 = request0.getToDate();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Request request0 = new Request("com.analytics.covid19.REST.Request", (LocalDate) null, (LocalDate) null);
      LocalDate localDate0 = request0.getFromDate();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Request request0 = new Request("", localDate0, localDate0);
      request0.setCountryName("}y>+Q<t");
      String string0 = request0.getCountryName();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Request request0 = new Request("", localDate0, localDate0);
      String string0 = request0.getCountryName();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Request request0 = new Request(localDate0);
      String string0 = request0.getCountryName();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Request request0 = new Request(localDate0);
      LocalDate localDate1 = request0.getFromDate();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Request request0 = new Request("com.analytics.covid19.REST.Request", (LocalDate) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Request request0 = new Request(localDate0);
      request0.setToDate(localDate0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Request request0 = new Request(localDate0);
      LocalDate localDate1 = request0.getToDate();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Request request0 = new Request();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Request request0 = new Request(localDate0);
      request0.setFromDate(localDate0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Request request0 = new Request("q<");
  }
}
