/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 30 16:48:26 GMT 2026
 */

package com.innova.security;

import org.junit.Test;
import static org.junit.Assert.*;
import com.innova.security._01_SecurityActive;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class _01_SecurityActive_ESTest extends _01_SecurityActive_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      _01_SecurityActive _01_SecurityActive0 = new _01_SecurityActive();
  }
}
