/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 30 16:45:40 GMT 2026
 */

package com.innova.security;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.innova.security._04_SecurityHttpBasic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class _04_SecurityHttpBasic_ESTest extends _04_SecurityHttpBasic_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      _04_SecurityHttpBasic _04_SecurityHttpBasic0 = new _04_SecurityHttpBasic();
      try { 
        _04_SecurityHttpBasic0.configure((HttpSecurity) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.innova.security._04_SecurityHttpBasic", e);
      }
  }
}
