/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 03:36:56 GMT 2026
 */

package com.github.nylle.javafixture.specimen;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.nylle.javafixture.Configuration;
import com.github.nylle.javafixture.Context;
import com.github.nylle.javafixture.CustomizationContext;
import com.github.nylle.javafixture.SpecimenType;
import com.github.nylle.javafixture.specimen.PredefinedSpecimen;
import java.lang.annotation.Annotation;
import java.lang.reflect.Type;
import java.time.chrono.ChronoLocalDate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PredefinedSpecimen_ESTest extends PredefinedSpecimen_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Class<String> class0 = String.class;
      Type[] typeArray0 = new Type[0];
      SpecimenType<String> specimenType0 = SpecimenType.fromRawType((Class<?>) class0, typeArray0);
      Configuration configuration0 = new Configuration((-2038), (-343), 1);
      Context context0 = new Context(configuration0);
      CustomizationContext customizationContext0 = CustomizationContext.noContext();
      Class<ChronoLocalDate> class1 = ChronoLocalDate.class;
      SpecimenType<ChronoLocalDate> specimenType1 = SpecimenType.fromRawType((Class<?>) class1, typeArray0);
      SpecimenType<Object> specimenType2 = SpecimenType.fromRawType((Class<?>) class1, typeArray0);
      PredefinedSpecimen<Object> predefinedSpecimen0 = new PredefinedSpecimen<Object>(specimenType2, context0);
      Annotation[] annotationArray0 = new Annotation[0];
      Object object0 = context0.overwrite((SpecimenType<?>) specimenType1, (Object) specimenType0);
      Object object1 = predefinedSpecimen0.create(customizationContext0, annotationArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Class<String> class0 = String.class;
      Type[] typeArray0 = new Type[0];
      SpecimenType<String> specimenType0 = SpecimenType.fromRawType((Class<?>) class0, typeArray0);
      PredefinedSpecimen<String> predefinedSpecimen0 = null;
      try {
        predefinedSpecimen0 = new PredefinedSpecimen<String>(specimenType0, (Context) null);
      } catch(IllegalArgumentException e) {
         //
         // context: null
         //
         verifyException("com.github.nylle.javafixture.specimen.PredefinedSpecimen", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Configuration configuration0 = new Configuration((-1143), (-1143), (-1143), true);
      Context context0 = new Context(configuration0);
      PredefinedSpecimen<Integer> predefinedSpecimen0 = null;
      try {
        predefinedSpecimen0 = new PredefinedSpecimen<Integer>((SpecimenType<Integer>) null, context0);
      } catch(IllegalArgumentException e) {
         //
         // type: null
         //
         verifyException("com.github.nylle.javafixture.specimen.PredefinedSpecimen", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Type[] typeArray0 = new Type[0];
      Configuration configuration0 = new Configuration((-2038), (-343), 1);
      Context context0 = new Context(configuration0);
      CustomizationContext customizationContext0 = CustomizationContext.noContext();
      Class<ChronoLocalDate> class0 = ChronoLocalDate.class;
      SpecimenType<Object> specimenType0 = SpecimenType.fromRawType((Class<?>) class0, typeArray0);
      PredefinedSpecimen<Object> predefinedSpecimen0 = new PredefinedSpecimen<Object>(specimenType0, context0);
      Annotation[] annotationArray0 = new Annotation[0];
      Object object0 = predefinedSpecimen0.create(customizationContext0, annotationArray0);
  }
}
