/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 03:32:07 GMT 2026
 */

package com.github.nylle.javafixture.specimen;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.nylle.javafixture.Configuration;
import com.github.nylle.javafixture.Context;
import com.github.nylle.javafixture.CustomizationContext;
import com.github.nylle.javafixture.SpecimenType;
import com.github.nylle.javafixture.specimen.TimeSpecimen;
import java.lang.annotation.Annotation;
import java.lang.reflect.Type;
import java.sql.Date;
import java.time.Duration;
import java.time.ZoneOffset;
import java.time.chrono.JapaneseEra;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeSpecimen_ESTest extends TimeSpecimen_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Configuration configuration0 = new Configuration();
      Context context0 = new Context(configuration0);
      SpecimenType<Object> specimenType0 = SpecimenType.fromClass((Type) null);
      TimeSpecimen<Object> timeSpecimen0 = null;
      try {
        timeSpecimen0 = new TimeSpecimen<Object>(specimenType0, context0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Class<ZoneOffset> class0 = ZoneOffset.class;
      Type[] typeArray0 = new Type[0];
      Configuration configuration0 = new Configuration();
      Context context0 = new Context(configuration0);
      SpecimenType<Date> specimenType0 = SpecimenType.fromRawType((Class<?>) class0, typeArray0);
      TimeSpecimen<Date> timeSpecimen0 = null;
      try {
        timeSpecimen0 = new TimeSpecimen<Date>(specimenType0, context0);
      } catch(ClassCastException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Configuration configuration0 = new Configuration();
      Context context0 = new Context(configuration0);
      CustomizationContext customizationContext0 = CustomizationContext.noContext();
      Class<Duration> class0 = Duration.class;
      SpecimenType<Object> specimenType0 = SpecimenType.fromClass((Type) class0);
      TimeSpecimen<Object> timeSpecimen0 = new TimeSpecimen<Object>(specimenType0, context0);
      Object object0 = timeSpecimen0.create(customizationContext0, (Annotation[]) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Class<Date> class0 = Date.class;
      Configuration configuration0 = new Configuration((-3180), 686, 686, false);
      Context context0 = new Context(configuration0);
      CustomizationContext customizationContext0 = CustomizationContext.noContext();
      SpecimenType<Object> specimenType0 = SpecimenType.fromClass((Type) class0);
      TimeSpecimen<Object> timeSpecimen0 = new TimeSpecimen<Object>(specimenType0, context0);
      Annotation[] annotationArray0 = new Annotation[3];
      Object object0 = timeSpecimen0.create(customizationContext0, annotationArray0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Class<ZoneOffset> class0 = ZoneOffset.class;
      Configuration configuration0 = new Configuration();
      Context context0 = new Context(configuration0);
      CustomizationContext customizationContext0 = CustomizationContext.noContext();
      SpecimenType<Object> specimenType0 = SpecimenType.fromClass((Type) class0);
      TimeSpecimen<Object> timeSpecimen0 = new TimeSpecimen<Object>(specimenType0, context0);
      Object object0 = timeSpecimen0.create(customizationContext0, (Annotation[]) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Class<ZoneOffset> class0 = ZoneOffset.class;
      SpecimenType<Object> specimenType0 = SpecimenType.fromClass((Type) class0);
      TimeSpecimen<Object> timeSpecimen0 = null;
      try {
        timeSpecimen0 = new TimeSpecimen<Object>(specimenType0, (Context) null);
      } catch(IllegalArgumentException e) {
         //
         // context: null
         //
         verifyException("com.github.nylle.javafixture.specimen.TimeSpecimen", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Class<MockLocalTime> class0 = MockLocalTime.class;
      Configuration configuration0 = new Configuration((-1120), (-2133), 2584, true);
      SpecimenType<JapaneseEra> specimenType0 = SpecimenType.fromClass((Type) class0);
      Context context0 = new Context(configuration0);
      TimeSpecimen<JapaneseEra> timeSpecimen0 = null;
      try {
        timeSpecimen0 = new TimeSpecimen<JapaneseEra>(specimenType0, context0);
      } catch(IllegalArgumentException e) {
         //
         // type: org.evosuite.runtime.mock.java.time.MockLocalTime
         //
         verifyException("com.github.nylle.javafixture.specimen.TimeSpecimen", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TimeSpecimen<JapaneseEra> timeSpecimen0 = null;
      try {
        timeSpecimen0 = new TimeSpecimen<JapaneseEra>((SpecimenType<JapaneseEra>) null, (Context) null);
      } catch(IllegalArgumentException e) {
         //
         // type: null
         //
         verifyException("com.github.nylle.javafixture.specimen.TimeSpecimen", e);
      }
  }
}
