/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 03:23:25 GMT 2026
 */

package leetcode;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import leetcode.IntersectionOfTwoArrays;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IntersectionOfTwoArrays_ESTest extends IntersectionOfTwoArrays_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IntersectionOfTwoArrays intersectionOfTwoArrays0 = new IntersectionOfTwoArrays();
      // Undeclared exception!
      try { 
        intersectionOfTwoArrays0.intersection((int[]) null, (int[]) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IntersectionOfTwoArrays intersectionOfTwoArrays0 = new IntersectionOfTwoArrays();
      int[] intArray0 = new int[2];
      int[] intArray1 = new int[0];
      int[] intArray2 = intersectionOfTwoArrays0.intersection(intArray1, intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IntersectionOfTwoArrays intersectionOfTwoArrays0 = new IntersectionOfTwoArrays();
      int[] intArray0 = new int[2];
      int[] intArray1 = intersectionOfTwoArrays0.intersection(intArray0, intArray0);
  }
}
