/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 10:11:08 GMT 2026
 */

package com.github.hannotify.elevencrazyjavathings.number1;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.hannotify.elevencrazyjavathings.number1.Number1PassingArgumentsToMethodReferences;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Number1PassingArgumentsToMethodReferences_ESTest extends Number1PassingArgumentsToMethodReferences_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Number1PassingArgumentsToMethodReferences number1PassingArgumentsToMethodReferences0 = new Number1PassingArgumentsToMethodReferences();
  }
}
