/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 08:37:33 GMT 2026
 */

package io.reactive.learning.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.qos.logback.classic.spi.LoggingEvent;
import io.reactive.learning.controller.Anything;
import java.nio.file.StandardOpenOption;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Anything_ESTest extends Anything_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.url = "reactor.left.onChannelWriteIdle";
      String string0 = anything0.getUrl();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setUrl("");
      String string0 = anything0.getUrl();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setOrigin("io.reactive.learning.controller.Anything");
      String string0 = anything0.getOrigin();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setOrigin("");
      String string0 = anything0.getOrigin();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setMethod(")");
      String string0 = anything0.getMethod();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setMethod("");
      String string0 = anything0.getMethod();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Anything anything0 = new Anything();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      anything0.setHeaders(hashMap0);
      Map<String, String> map0 = anything0.getHeaders();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Anything anything0 = new Anything();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      String string0 = hashMap0.put("AD0t", "");
      anything0.setHeaders(hashMap0);
      Map<String, String> map0 = anything0.getHeaders();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Anything anything0 = new Anything();
      boolean boolean0 = anything0.canEqual(anything0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Anything anything0 = new Anything();
      boolean boolean0 = anything0.canEqual("Anything(url=null, method=null, origin=io.netty.channel.unix.IovArray, headers=null)");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Anything anything0 = new Anything();
      Map<String, String> map0 = anything0.getHeaders();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Anything anything0 = new Anything();
      String string0 = anything0.getOrigin();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Anything anything0 = new Anything();
      String string0 = anything0.getMethod();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Anything anything0 = new Anything();
      String string0 = anything0.getUrl();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Anything anything0 = new Anything();
      Anything anything1 = new Anything();
      LoggingEvent loggingEvent0 = new LoggingEvent();
      Map<String, String> map0 = loggingEvent0.getMDCPropertyMap();
      anything0.setHeaders(map0);
      anything1.headers = map0;
      boolean boolean0 = anything1.equals(anything0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Anything anything0 = new Anything();
      Anything anything1 = new Anything();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      anything1.setHeaders(hashMap0);
      boolean boolean0 = anything0.equals(anything1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Anything anything0 = new Anything();
      Anything anything1 = new Anything();
      LoggingEvent loggingEvent0 = new LoggingEvent();
      Map<String, String> map0 = loggingEvent0.getMDCPropertyMap();
      anything1.headers = map0;
      boolean boolean0 = anything1.equals(anything0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setOrigin("bd");
      Anything anything1 = new Anything();
      anything1.setOrigin("bd");
      boolean boolean0 = anything0.equals(anything1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Anything anything0 = new Anything();
      Anything anything1 = new Anything();
      anything1.origin = "io.reactive.learning.controller.Anything";
      boolean boolean0 = anything0.equals(anything1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.method = ">M;C;Aw}'+4q9";
      Anything anything1 = new Anything();
      anything1.method = ">M;C;Aw}'+4q9";
      boolean boolean0 = anything1.equals(anything0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Anything anything0 = new Anything();
      Anything anything1 = new Anything();
      anything1.setMethod("");
      boolean boolean0 = anything0.equals(anything1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Anything anything0 = new Anything();
      Anything anything1 = new Anything();
      anything1.method = ">M;C;Aw}'+4q9";
      boolean boolean0 = anything1.equals(anything0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.url = "";
      Anything anything1 = new Anything();
      anything1.url = "";
      boolean boolean0 = anything0.equals(anything1);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.url = "";
      Anything anything1 = new Anything();
      boolean boolean0 = anything0.equals(anything1);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Anything anything0 = new Anything();
      StandardOpenOption standardOpenOption0 = StandardOpenOption.CREATE_NEW;
      boolean boolean0 = anything0.equals(standardOpenOption0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Anything anything0 = new Anything();
      boolean boolean0 = anything0.equals(anything0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Anything anything0 = new Anything();
      LoggingEvent loggingEvent0 = new LoggingEvent();
      Map<String, String> map0 = loggingEvent0.getMDCPropertyMap();
      anything0.setHeaders(map0);
      int int0 = anything0.hashCode();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setOrigin("");
      int int0 = anything0.hashCode();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setMethod("J5Uh)beHA");
      int int0 = anything0.hashCode();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setUrl("registered to an event loop already");
      int int0 = anything0.hashCode();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setUrl("parallel");
      Anything anything1 = new Anything();
      boolean boolean0 = anything1.equals(anything0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Anything anything0 = new Anything();
      String string0 = anything0.toString();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Anything anything0 = new Anything();
      anything0.setOrigin("bd");
      Anything anything1 = new Anything();
      boolean boolean0 = anything0.equals(anything1);
  }
}
