/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Aug 06 18:02:57 GMT 2026
 */

package com.piinalpin.queryrequest.service;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class OperatingSystemService_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.piinalpin.queryrequest.service.OperatingSystemService"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(OperatingSystemService_ESTest_scaffolding.class.getClassLoader() ,
      "com.piinalpin.queryrequest.domain.common.query.SortDirection",
      "com.fasterxml.jackson.databind.PropertyNamingStrategies$NamingBase",
      "org.springframework.beans.factory.annotation.Autowired",
      "org.springframework.data.domain.AbstractPageRequest",
      "org.springframework.data.repository.CrudRepository",
      "com.fasterxml.jackson.annotation.JacksonAnnotation",
      "org.springframework.data.domain.Sort$Direction",
      "com.piinalpin.queryrequest.domain.common.query.SortRequest",
      "com.piinalpin.queryrequest.domain.common.query.FieldType",
      "org.springframework.stereotype.Service",
      "com.piinalpin.queryrequest.domain.common.query.FilterRequest",
      "com.piinalpin.queryrequest.domain.common.query.Operator",
      "org.springframework.data.repository.Repository",
      "com.piinalpin.queryrequest.domain.common.query.FilterRequest$FilterRequestBuilder",
      "org.springframework.data.domain.Sort",
      "org.springframework.data.domain.Pageable",
      "com.piinalpin.queryrequest.domain.common.query.SortRequest$SortRequestBuilder",
      "org.springframework.stereotype.Repository",
      "org.springframework.data.jpa.repository.JpaSpecificationExecutor",
      "com.piinalpin.queryrequest.service.OperatingSystemService",
      "com.fasterxml.jackson.databind.PropertyNamingStrategy",
      "org.springframework.data.repository.PagingAndSortingRepository",
      "com.fasterxml.jackson.databind.PropertyNamingStrategies$SnakeCaseStrategy",
      "com.piinalpin.queryrequest.domain.common.query.SearchRequest$SearchRequestBuilder",
      "com.piinalpin.queryrequest.domain.dao.OperatingSystem",
      "org.springframework.data.domain.PageRequest",
      "com.piinalpin.queryrequest.domain.common.query.SearchRequest",
      "org.springframework.data.domain.Page",
      "com.piinalpin.queryrequest.repository.OperatingSystemRepository",
      "org.springframework.data.domain.Sort$Order",
      "org.springframework.data.domain.Slice",
      "org.springframework.data.domain.Sort$NullHandling",
      "com.piinalpin.queryrequest.domain.common.query.SearchSpecification",
      "org.springframework.data.repository.query.QueryByExampleExecutor",
      "org.springframework.stereotype.Component",
      "org.springframework.data.jpa.domain.Specification",
      "org.springframework.data.util.Streamable",
      "com.piinalpin.queryrequest.domain.dao.OperatingSystem$OperatingSystemBuilder",
      "com.fasterxml.jackson.databind.annotation.JsonNaming",
      "org.springframework.data.domain.Sort$TypedSort",
      "org.springframework.data.jpa.repository.JpaRepository",
      "com.fasterxml.jackson.annotation.JsonIgnoreProperties",
      "org.springframework.util.Assert"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(OperatingSystemService_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.piinalpin.queryrequest.service.OperatingSystemService",
      "org.springframework.data.domain.Sort$Direction",
      "org.springframework.util.Assert",
      "org.springframework.data.domain.Sort",
      "com.piinalpin.queryrequest.domain.common.query.SearchRequest",
      "com.piinalpin.queryrequest.domain.common.query.SortRequest",
      "com.piinalpin.queryrequest.domain.common.query.FilterRequest",
      "com.piinalpin.queryrequest.domain.common.query.SearchSpecification",
      "org.springframework.data.domain.AbstractPageRequest",
      "org.springframework.data.domain.PageRequest",
      "com.piinalpin.queryrequest.domain.common.query.SearchRequest$SearchRequestBuilder",
      "com.piinalpin.queryrequest.domain.dao.OperatingSystem",
      "com.piinalpin.queryrequest.domain.dao.OperatingSystem$OperatingSystemBuilder"
    );
  }
}
