/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 21:38:19 GMT 2026
 */

package refactoring.app.chapter10.replaceNestedConditionalWithGuardClauses;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import refactoring.app.chapter10.replaceNestedConditionalWithGuardClauses.Instrument;
import refactoring.app.chapter10.replaceNestedConditionalWithGuardClauses.ReverseExample;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ReverseExample_ESTest extends ReverseExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReverseExample reverseExample0 = new ReverseExample();
      Instrument instrument0 = new Instrument();
      instrument0.duration = 63;
      instrument0.interRate = 745.072775;
      instrument0.income = 1;
      int int0 = reverseExample0.adjustedCapital(instrument0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReverseExample reverseExample0 = new ReverseExample();
      Instrument instrument0 = new Instrument();
      instrument0.duration = (-1008);
      instrument0.interRate = (-1.0);
      instrument0.interRate = 2079.013571;
      int int0 = reverseExample0.adjustedCapital(instrument0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReverseExample reverseExample0 = new ReverseExample();
      Instrument instrument0 = new Instrument();
      instrument0.interRate = (-2118.7226965731);
      int int0 = reverseExample0.adjustedCapital(instrument0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ReverseExample reverseExample0 = new ReverseExample();
      Instrument instrument0 = new Instrument();
      instrument0.capital = 845;
      int int0 = reverseExample0.adjustedCapital(instrument0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ReverseExample reverseExample0 = new ReverseExample();
      Instrument instrument0 = new Instrument();
      instrument0.adjustmentFactor = 572.1;
      instrument0.interRate = 1728.14879;
      instrument0.duration = 1;
      instrument0.income = (-296);
      instrument0.income = 1;
      int int0 = reverseExample0.adjustedCapital(instrument0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ReverseExample reverseExample0 = new ReverseExample();
      Instrument instrument0 = new Instrument();
      instrument0.adjustmentFactor = 572.1;
      instrument0.interRate = 1728.14879;
      instrument0.duration = 1;
      instrument0.income = (-296);
      int int0 = reverseExample0.adjustedCapital(instrument0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ReverseExample reverseExample0 = new ReverseExample();
      // Undeclared exception!
      try { 
        reverseExample0.adjustedCapital((Instrument) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ReverseExample reverseExample0 = new ReverseExample();
      Instrument instrument0 = new Instrument();
      instrument0.interRate = 1728.14879;
      int int0 = reverseExample0.adjustedCapital(instrument0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ReverseExample reverseExample0 = new ReverseExample();
      Instrument instrument0 = new Instrument();
      instrument0.capital = (-2146470551);
      int int0 = reverseExample0.adjustedCapital(instrument0);
  }
}
