/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 15:19:04 GMT 2026
 */

package icu.samnyan.aqua.sega.diva.handler.user;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import icu.samnyan.aqua.sega.diva.dao.gamedata.ContestRepository;
import icu.samnyan.aqua.sega.diva.dao.userdata.GameSessionRepository;
import icu.samnyan.aqua.sega.diva.dao.userdata.PlayerContestRepository;
import icu.samnyan.aqua.sega.diva.dao.userdata.PlayerProfileRepository;
import icu.samnyan.aqua.sega.diva.handler.user.EndHandler;
import icu.samnyan.aqua.sega.diva.model.common.StartMode;
import icu.samnyan.aqua.sega.diva.model.gamedata.Contest;
import icu.samnyan.aqua.sega.diva.model.request.ingame.StageResultRequest;
import icu.samnyan.aqua.sega.diva.model.userdata.GameSession;
import icu.samnyan.aqua.sega.diva.model.userdata.PlayerContest;
import icu.samnyan.aqua.sega.diva.model.userdata.PlayerProfile;
import icu.samnyan.aqua.sega.diva.service.PlayerProfileService;
import icu.samnyan.aqua.sega.diva.util.DivaMapper;
import java.time.LocalDateTime;
import java.util.Optional;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.springframework.asm.Opcodes;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EndHandler_ESTest extends EndHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DivaMapper divaMapper0 = new DivaMapper();
      ContestRepository contestRepository0 = mock(ContestRepository.class, new ViolatedAssumptionAnswer());
      doReturn((Optional) null).when(contestRepository0).findById(anyInt());
      PlayerProfile playerProfile0 = new PlayerProfile();
      Optional<PlayerProfile> optional0 = Optional.ofNullable(playerProfile0);
      PlayerProfileRepository playerProfileRepository0 = mock(PlayerProfileRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional0).when(playerProfileRepository0).findByPdId(anyInt());
      PlayerProfileService playerProfileService0 = new PlayerProfileService(playerProfileRepository0);
      PlayerContestRepository playerContestRepository0 = mock(PlayerContestRepository.class, new ViolatedAssumptionAnswer());
      StartMode startMode0 = StartMode.CARD_PROCEDURE;
      Integer integer0 = Opcodes.LONG;
      GameSession gameSession0 = new GameSession((-32769), playerProfile0, startMode0, (LocalDateTime) null, (LocalDateTime) null, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Optional<GameSession> optional1 = Optional.ofNullable(gameSession0);
      GameSessionRepository gameSessionRepository0 = mock(GameSessionRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional1).when(gameSessionRepository0).findByPdId(any(icu.samnyan.aqua.sega.diva.model.userdata.PlayerProfile.class));
      EndHandler endHandler0 = new EndHandler(divaMapper0, contestRepository0, playerProfileService0, playerContestRepository0, gameSessionRepository0);
      StageResultRequest stageResultRequest0 = new StageResultRequest();
      // Undeclared exception!
      try { 
        endHandler0.handle(stageResultRequest0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("icu.samnyan.aqua.sega.diva.handler.user.EndHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DivaMapper divaMapper0 = new DivaMapper();
      ContestRepository contestRepository0 = mock(ContestRepository.class, new ViolatedAssumptionAnswer());
      PlayerProfileRepository playerProfileRepository0 = mock(PlayerProfileRepository.class, new ViolatedAssumptionAnswer());
      doReturn((Optional) null).when(playerProfileRepository0).findByPdId(anyInt());
      PlayerProfileService playerProfileService0 = new PlayerProfileService(playerProfileRepository0);
      PlayerContestRepository playerContestRepository0 = mock(PlayerContestRepository.class, new ViolatedAssumptionAnswer());
      GameSessionRepository gameSessionRepository0 = mock(GameSessionRepository.class, new ViolatedAssumptionAnswer());
      EndHandler endHandler0 = new EndHandler(divaMapper0, contestRepository0, playerProfileService0, playerContestRepository0, gameSessionRepository0);
      StageResultRequest stageResultRequest0 = new StageResultRequest();
      // Undeclared exception!
      try { 
        endHandler0.handle(stageResultRequest0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("icu.samnyan.aqua.sega.diva.handler.user.EndHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DivaMapper divaMapper0 = new DivaMapper();
      ContestRepository contestRepository0 = mock(ContestRepository.class, new ViolatedAssumptionAnswer());
      doReturn((Optional) null).when(contestRepository0).findById(anyInt());
      PlayerProfile playerProfile0 = new PlayerProfile();
      Optional<PlayerProfile> optional0 = Optional.ofNullable(playerProfile0);
      PlayerProfileRepository playerProfileRepository0 = mock(PlayerProfileRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional0).when(playerProfileRepository0).findByPdId(anyInt());
      PlayerProfileService playerProfileService0 = new PlayerProfileService(playerProfileRepository0);
      PlayerContestRepository playerContestRepository0 = mock(PlayerContestRepository.class, new ViolatedAssumptionAnswer());
      StartMode startMode0 = StartMode.CARD_PROCEDURE;
      Integer integer0 = Opcodes.LONG;
      GameSession gameSession0 = new GameSession((-32769), playerProfile0, startMode0, (LocalDateTime) null, (LocalDateTime) null, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Optional<GameSession> optional1 = Optional.ofNullable(gameSession0);
      GameSessionRepository gameSessionRepository0 = mock(GameSessionRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional1).when(gameSessionRepository0).findByPdId(any(icu.samnyan.aqua.sega.diva.model.userdata.PlayerProfile.class));
      EndHandler endHandler0 = new EndHandler(divaMapper0, contestRepository0, playerProfileService0, playerContestRepository0, gameSessionRepository0);
      int[] intArray0 = new int[0];
      int[] intArray1 = new int[1];
      String[] stringArray0 = new String[9];
      StageResultRequest stageResultRequest0 = new StageResultRequest((-494), 0, (-494), 0, false, (-494), 0, false, 1458, 1458, 2026, 0, (-1432), (-936), 0, intArray0, intArray0, false, (-1432), intArray0, intArray0, intArray1, intArray0, intArray1, intArray1, intArray1, intArray1, intArray1, intArray0, intArray1, intArray0, intArray0, intArray1, intArray1, intArray1, intArray1, intArray0, intArray1, intArray0, intArray1, intArray1, intArray1, intArray0, intArray1, intArray1, intArray0, intArray1, intArray1, intArray1, intArray0, intArray1, intArray1, intArray1, intArray1, intArray1, intArray1, intArray0, intArray1, intArray1, intArray1, intArray1, intArray0, intArray1, intArray1, intArray1, intArray0, intArray1, intArray0, intArray1, intArray1, intArray1, 0, (-936), 1420, (-1514), intArray0, intArray1, intArray1, intArray0, intArray0, intArray1, intArray1, intArray1, (-1432), 1420, 60, 2882, stringArray0);
      // Undeclared exception!
      try { 
        endHandler0.handle(stageResultRequest0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("icu.samnyan.aqua.sega.diva.handler.user.EndHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DivaMapper divaMapper0 = new DivaMapper();
      Optional<Contest> optional0 = Optional.empty();
      ContestRepository contestRepository0 = mock(ContestRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional0).when(contestRepository0).findById(anyInt());
      PlayerProfile playerProfile0 = new PlayerProfile();
      Optional<PlayerProfile> optional1 = Optional.ofNullable(playerProfile0);
      PlayerProfileRepository playerProfileRepository0 = mock(PlayerProfileRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional1).when(playerProfileRepository0).findByPdId(anyInt());
      doReturn(optional1).when(playerProfileRepository0).save(any());
      PlayerProfileService playerProfileService0 = new PlayerProfileService(playerProfileRepository0);
      PlayerContestRepository playerContestRepository0 = mock(PlayerContestRepository.class, new ViolatedAssumptionAnswer());
      StartMode startMode0 = StartMode.START;
      Integer integer0 = Opcodes.LONG;
      GameSession gameSession0 = new GameSession((-32769), playerProfile0, startMode0, (LocalDateTime) null, (LocalDateTime) null, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Optional<GameSession> optional2 = Optional.ofNullable(gameSession0);
      GameSessionRepository gameSessionRepository0 = mock(GameSessionRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional2).when(gameSessionRepository0).findByPdId(any(icu.samnyan.aqua.sega.diva.model.userdata.PlayerProfile.class));
      EndHandler endHandler0 = new EndHandler(divaMapper0, contestRepository0, playerProfileService0, playerContestRepository0, gameSessionRepository0);
      int[] intArray0 = new int[7];
      String[] stringArray0 = new String[5];
      StageResultRequest stageResultRequest0 = new StageResultRequest((-1), 0, 197, 0, true, 60, (-1563), true, 110, (-1), 0, (-32769), 2505, (-1), 1, intArray0, intArray0, false, (-1934), intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, 0, (-3641), (-881), 0, intArray0, (int[]) null, intArray0, intArray0, intArray0, intArray0, intArray0, (int[]) null, 0, (-1), 60, 0, stringArray0);
      // Undeclared exception!
      try { 
        endHandler0.handle(stageResultRequest0);
      } catch(ClassCastException e) {
         //
         // class java.util.Optional cannot be cast to class icu.samnyan.aqua.sega.diva.model.userdata.PlayerProfile (java.util.Optional is in module java.base of loader 'bootstrap'; icu.samnyan.aqua.sega.diva.model.userdata.PlayerProfile is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @38e1d27f)
         //
         verifyException("icu.samnyan.aqua.sega.diva.dao.userdata.PlayerProfileRepository$MockitoMock$985671342", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DivaMapper divaMapper0 = new DivaMapper();
      Optional<Contest> optional0 = Optional.empty();
      ContestRepository contestRepository0 = mock(ContestRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional0).when(contestRepository0).findById(anyInt());
      PlayerProfile playerProfile0 = new PlayerProfile();
      Optional<PlayerProfile> optional1 = Optional.ofNullable(playerProfile0);
      PlayerProfileRepository playerProfileRepository0 = mock(PlayerProfileRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional1).when(playerProfileRepository0).findByPdId(anyInt());
      doReturn((Object) null).when(playerProfileRepository0).save(any());
      PlayerProfileService playerProfileService0 = new PlayerProfileService(playerProfileRepository0);
      PlayerContest playerContest0 = new PlayerContest();
      Optional<PlayerContest> optional2 = Optional.of(playerContest0);
      PlayerContestRepository playerContestRepository0 = mock(PlayerContestRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional2).when(playerContestRepository0).findByPdIdAndContestId(any(icu.samnyan.aqua.sega.diva.model.userdata.PlayerProfile.class) , anyInt());
      doReturn(playerContest0).when(playerContestRepository0).save(any());
      StartMode startMode0 = StartMode.START;
      Integer integer0 = Opcodes.LONG;
      GameSession gameSession0 = new GameSession((-32769), playerProfile0, startMode0, (LocalDateTime) null, (LocalDateTime) null, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Optional<GameSession> optional3 = Optional.ofNullable(gameSession0);
      GameSessionRepository gameSessionRepository0 = mock(GameSessionRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional3).when(gameSessionRepository0).findByPdId(any(icu.samnyan.aqua.sega.diva.model.userdata.PlayerProfile.class));
      EndHandler endHandler0 = new EndHandler(divaMapper0, contestRepository0, playerProfileService0, playerContestRepository0, gameSessionRepository0);
      int[] intArray0 = new int[7];
      String[] stringArray0 = new String[5];
      StageResultRequest stageResultRequest0 = new StageResultRequest((-1), (-23), 197, (-23), true, 197, (-1563), true, 110, (-1), 0, (-32769), 2505, (-1), 1, intArray0, intArray0, false, (-1934), intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, 0, (-3641), (-881), (-23), intArray0, (int[]) null, intArray0, intArray0, intArray0, intArray0, intArray0, (int[]) null, 0, (-1), (-23), (-32769), stringArray0);
      String string0 = endHandler0.handle(stageResultRequest0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DivaMapper divaMapper0 = new DivaMapper();
      ContestRepository contestRepository0 = mock(ContestRepository.class, new ViolatedAssumptionAnswer());
      PlayerProfile playerProfile0 = new PlayerProfile();
      Optional<PlayerProfile> optional0 = Optional.ofNullable(playerProfile0);
      PlayerProfileRepository playerProfileRepository0 = mock(PlayerProfileRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional0).when(playerProfileRepository0).findByPdId(anyInt());
      doReturn((Object) null).when(playerProfileRepository0).save(any());
      PlayerProfileService playerProfileService0 = new PlayerProfileService(playerProfileRepository0);
      PlayerContestRepository playerContestRepository0 = mock(PlayerContestRepository.class, new ViolatedAssumptionAnswer());
      StartMode startMode0 = StartMode.CARD_PROCEDURE;
      Integer integer0 = Opcodes.LONG;
      GameSession gameSession0 = new GameSession((-32769), playerProfile0, startMode0, (LocalDateTime) null, (LocalDateTime) null, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Optional<GameSession> optional1 = Optional.ofNullable(gameSession0);
      GameSessionRepository gameSessionRepository0 = mock(GameSessionRepository.class, new ViolatedAssumptionAnswer());
      doReturn(optional1).when(gameSessionRepository0).findByPdId(any(icu.samnyan.aqua.sega.diva.model.userdata.PlayerProfile.class));
      EndHandler endHandler0 = new EndHandler(divaMapper0, contestRepository0, playerProfileService0, playerContestRepository0, gameSessionRepository0);
      int[] intArray0 = new int[4];
      String[] stringArray0 = new String[3];
      StageResultRequest stageResultRequest0 = new StageResultRequest((-32769), (-1399), (-32769), (-1058), false, 84, (-1399), false, (-889275714), 2, (-32769), 3639, (-1058), 0, (-3471), intArray0, intArray0, true, (-32769), (int[]) null, intArray0, (int[]) null, intArray0, (int[]) null, (int[]) null, intArray0, intArray0, intArray0, (int[]) null, intArray0, intArray0, (int[]) null, (int[]) null, (int[]) null, (int[]) null, (int[]) null, (int[]) null, (int[]) null, intArray0, intArray0, (int[]) null, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, (int[]) null, intArray0, (int[]) null, intArray0, (int[]) null, intArray0, intArray0, intArray0, intArray0, intArray0, intArray0, (int[]) null, intArray0, intArray0, (int[]) null, intArray0, intArray0, intArray0, (int[]) null, 0, 4660, (-1060), 84, intArray0, (int[]) null, (int[]) null, intArray0, intArray0, intArray0, intArray0, intArray0, (-1), (-1), (-1433), (-32769), stringArray0);
      String string0 = endHandler0.handle(stageResultRequest0);
  }
}
