/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Jun 11 23:49:09 GMT 2026
 */

package com.gin.mergegfassets.utils;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class IoUtils_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.gin.mergegfassets.utils.IoUtils"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
    org.evosuite.runtime.util.SystemInUtil.getInstance().initForTestCase(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/suelenfelix/TCC/nova-geracao/evosuite/projects/AgMonk_merge-gf-assets"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(IoUtils_ESTest_scaffolding.class.getClassLoader() ,
      "com.alibaba.fastjson2.JSONPath$EvalSegment",
      "com.alibaba.fastjson2.reader.ConstructorFunction",
      "com.alibaba.fastjson2.reader.TypeConverts$ToNumber",
      "com.alibaba.fastjson2.JSONPath",
      "com.alibaba.fastjson2.util.GuavaSupport$AsMapWriter",
      "org.assertj.core.extractor.ByNameMultipleExtractor",
      "com.alibaba.fastjson2.reader.TypeConverts$ToByte",
      "com.alibaba.fastjson2.reader.TypeConverts$ToShort",
      "com.alibaba.fastjson2.util.Fastjson1xSupport$ObjectCreatorUF",
      "com.alibaba.fastjson2.reader.TypeConverts$ToInteger",
      "com.alibaba.fastjson2.JSONPath$AllSegment",
      "com.alibaba.fastjson2.support.AwtRederModule$ColorCreator",
      "org.assertj.core.extractor.ByNameSingleExtractor",
      "com.alibaba.fastjson2.JSONPath$SizeFunction",
      "com.alibaba.fastjson2.JSONPath$IndexSegment",
      "com.alibaba.fastjson2.JSONPath$MultiSegmentPath",
      "com.alibaba.fastjson2.JSONPath$KeysSegment",
      "com.alibaba.fastjson2.reader.TypeConverts$ToDouble",
      "com.alibaba.fastjson2.JSONPath$BiFunctionAdapter",
      "com.alibaba.fastjson2.JSONPath$NameIntOpSegment",
      "com.alibaba.fastjson2.reader.FactoryFunction",
      "com.alibaba.fastjson2.JSONPath$Segment",
      "com.alibaba.fastjson2.JSONPath$RangeIndexSegment",
      "com.alibaba.fastjson2.util.GuavaSupport$ArrayListMultimapConvertFunction",
      "com.alibaba.fastjson2.util.GuavaSupport$ImmutableSetConvertFunction",
      "com.alibaba.fastjson2.JSONPath$MultiNameSegment",
      "com.alibaba.fastjson2.JSONPath$NameFilter",
      "com.alibaba.fastjson2.JSONPath$NameSegment",
      "com.alibaba.fastjson2.JSONPath$SingleNamePath",
      "com.alibaba.fastjson2.reader.TypeConverts$ToBigInteger",
      "com.alibaba.fastjson2.JSONPath$MaxSegment",
      "com.alibaba.fastjson2.util.GuavaSupport$ImmutableListConvertFunction",
      "com.alibaba.fastjson2.JSONPath$MinSegment",
      "com.alibaba.fastjson2.util.GuavaSupport$SingletonImmutableBiMapConvertFunction",
      "com.alibaba.fastjson2.reader.TypeConverts$ToString",
      "com.alibaba.fastjson2.reader.TypeConverts$ToBigDecimal",
      "com.alibaba.fastjson2.JSONPath$PreviousPath",
      "com.alibaba.fastjson2.JSONPath$NameExistsFilter",
      "com.alibaba.fastjson2.JSONPath$TwoSegmentPath",
      "org.assertj.core.extractor.ToStringExtractor",
      "com.alibaba.fastjson2.JSONPath$SingleSegmentPath",
      "com.alibaba.fastjson2.JSONPath$FilterSegment",
      "com.gin.mergegfassets.utils.IoUtils",
      "com.alibaba.fastjson2.reader.TypeConverts$StringToAny",
      "com.alibaba.fastjson2.JSONReader",
      "com.alibaba.fastjson2.JSONPath$StartsWithSegment",
      "com.alibaba.fastjson2.JSONPath$TypeFunction",
      "com.alibaba.fastjson2.util.Fastjson1xSupport",
      "com.alibaba.fastjson2.JSONFactory",
      "com.alibaba.fastjson2.JSONPath$MultiIndexSegment",
      "com.alibaba.fastjson2.reader.TypeConverts$ToLong",
      "com.alibaba.fastjson2.JSONWriter",
      "com.alibaba.fastjson2.writer.ObjectWriter",
      "com.alibaba.fastjson2.reader.TypeConverts",
      "com.alibaba.fastjson2.JSONPath$RandomIndexSegment",
      "com.alibaba.fastjson2.JSONPath$CycleNameSegment",
      "org.assertj.core.extractor.ResultOfExtractor",
      "com.alibaba.fastjson2.JSONException",
      "com.alibaba.fastjson2.JSONPath$LengthSegment",
      "com.alibaba.fastjson2.JSONPath$Operator",
      "com.alibaba.fastjson2.JSONPath$FunctionSegment",
      "com.alibaba.fastjson2.modules.ObjectReaderModule",
      "com.alibaba.fastjson2.support.AwtRederModule",
      "com.alibaba.fastjson2.util.GuavaSupport$ImmutableSingletonMapConvertFunction",
      "com.alibaba.fastjson2.reader.TypeConverts$ToFloat",
      "com.alibaba.fastjson2.util.GuavaSupport"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(IoUtils_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.gin.mergegfassets.utils.IoUtils",
      "com.alibaba.fastjson2.reader.TypeConverts$ToDouble",
      "com.alibaba.fastjson2.JSONException"
    );
  }
}
