package io.github.moacirrf.netbeans.markdown.ui.preview.image;

import java.lang.Throwable;
import java.lang.IllegalStateException;
import org.junit.Test;
import org.junit.Rule;
import org.junit.rules.Timeout;
import java.util.concurrent.TimeUnit;
import org.junit.Before;
import java.lang.Class;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import static io.github.moacirrf.netbeans.markdown.ui.preview.image.ReflectionUtils.*;
import static org.junit.Assert.assertTrue;
import java.lang.Object;

public class ImageLabel_createImageIcon_16416566542 {
    @Rule public Timeout globalTimeout = new Timeout(10, TimeUnit.SECONDS);
     Object term781;

    public ImageLabel_createImageIcon_16416566542() {
    }

    public <T> T unknown() {
        throw new IllegalStateException();
    }

    @Before
    public void setup() throws Throwable {
        term781 = newInstance(Class.forName("io.github.moacirrf.netbeans.markdown.ui.preview.image.ImageLabel"));
        Object term794 = newInstance(Class.forName("javax.swing.ImageIcon"));
        Object term807 = newInstance(Class.forName("java.net.URL"));
        Object term851 = newInstance(Class.forName("sun.net.www.protocol.http.Handler"));
        Object term868 = newInstance(Class.forName("javax.swing.ImageIcon$AccessibleImageIcon"));
        Object term893 = newInstance(Class.forName("java.beans.PropertyChangeSupport"));
        Object term894 = newInstance(Class.forName("java.beans.PropertyChangeSupport$PropertyChangeListenerMap"));
        Object term895 = newInstance(Class.forName("java.lang.Object"));
        Object term896 = newInstance(Class.forName("javax.accessibility.AccessibleRelationSet"));
        Object term897 = newInstance(Class.forName("java.util.Vector"));
        Object term901 = newInstance(Class.forName("java.lang.Object"));
        Object term938 = newInstance(Class.forName("javax.swing.event.EventListenerList"));
        Object[] term939 = (Object[]) newArray("java.lang.Object", 0);
        Object term940 = newInstance(Class.forName("javax.swing.ArrayTable"));
        Object term941 = newInstance(Class.forName("java.beans.VetoableChangeSupport"));
        setField(term781, term781.getClass(), "urlHiperlinkParent", "eZFUvlxvGV");
        setField(term794, term794.getClass(), "filename", "BYqFIqCKAV");
        setField(term807, term807.getClass(), "protocol", "http");
        setField(term807, term807.getClass(), "host", "www.google.com");
        setIntField(term807, term807.getClass(), "port", -1);
        setField(term807, term807.getClass(), "file", "");
        setField(term807, term807.getClass(), "query", null);
        setField(term807, term807.getClass(), "authority", "www.google.com");
        setField(term807, term807.getClass(), "path", "");
        setField(term807, term807.getClass(), "userInfo", null);
        setField(term807, term807.getClass(), "ref", null);
        setField(term807, term807.getClass(), "hostAddress", null);
        setField(term851, term851.getClass(), "proxy", null);
        setIntField(term851, term851.getClass(), "proxyPort", -1);
        setField(term807, term807.getClass(), "handler", term851);
        setField(term807, term807.getClass(), "tempState", null);
        setField(term794, term794.getClass(), "location", term807);
        setField(term794, term794.getClass(), "image", null);
        setIntField(term794, term794.getClass(), "loadStatus", -1685132342);
        setField(term794, term794.getClass(), "imageObserver", null);
        setField(term794, term794.getClass(), "description", "vrQLuWIDJX");
        setIntField(term794, term794.getClass(), "width", -1);
        setIntField(term794, term794.getClass(), "height", -1);
        setField(term868, term868.getClass(), "this$0", null);
        setField(term868, term868.getClass(), "targetAppContext", null);
        setField(term868, term868.getClass(), "accessibleParent", null);
        setField(term868, term868.getClass(), "accessibleName", "flxyYxBRtu");
        setField(term868, term868.getClass(), "accessibleDescription", "OclPbYPkcH");
        setField(term894, term894.getClass(), "map", null);
        setField(term893, term893.getClass(), "map", term894);
        setField(term893, term893.getClass(), "source", term895);
        setField(term868, term868.getClass(), "accessibleChangeSupport", term893);
        setField(term897, term897.getClass(), "elementData", null);
        setIntField(term897, term897.getClass(), "elementCount", 2);
        setIntField(term897, term897.getClass(), "capacityIncrement", 0);
        setIntField(term897, term897.getClass(), "modCount", 2);
        setField(term896, term896.getClass(), "relations", term897);
        setField(term868, term868.getClass(), "relationSet", term896);
        setField(term868, term868.getClass(), "nativeAXResource", term901);
        setField(term794, term794.getClass(), "accessibleContext", term868);
        setField(term781, term781.getClass(), "imageIconOriginal", term794);
        setField(term781, term781.getClass(), "imageKey", "SbAoxhfrkn");
        setIntField(term781, term781.getClass(), "mnemonic", -1456670397);
        setIntField(term781, term781.getClass(), "mnemonicIndex", 1622346318);
        setField(term781, term781.getClass(), "text", "kuTXqwMtDB");
        setField(term781, term781.getClass(), "defaultIcon", null);
        setField(term781, term781.getClass(), "disabledIcon", null);
        setBooleanField(term781, term781.getClass(), "disabledIconSet", true);
        setIntField(term781, term781.getClass(), "verticalAlignment", 1048535127);
        setIntField(term781, term781.getClass(), "horizontalAlignment", -655067527);
        setIntField(term781, term781.getClass(), "verticalTextPosition", -6029667);
        setIntField(term781, term781.getClass(), "horizontalTextPosition", -2068769794);
        setIntField(term781, term781.getClass(), "iconTextGap", -117576464);
        setField(term781, term781.getClass(), "labelFor", null);
        setBooleanField(term781, term781.getClass(), "isAlignmentXSet", true);
        setFloatField(term781, term781.getClass(), "alignmentX", 0.3455959F);
        setBooleanField(term781, term781.getClass(), "isAlignmentYSet", false);
        setFloatField(term781, term781.getClass(), "alignmentY", 0.09123778F);
        setField(term781, term781.getClass(), "ui", null);
        setField(term938, term938.getClass(), "listenerList", term939);
        setField(term781, term781.getClass(), "listenerList", term938);
        setField(term940, term940.getClass(), "table", null);
        setField(term781, term781.getClass(), "clientProperties", term940);
        setField(term941, term941.getClass(), "map", null);
        setField(term941, term941.getClass(), "source", null);
        setField(term781, term781.getClass(), "vetoableChangeSupport", term941);
        setBooleanField(term781, term781.getClass(), "autoscrolls", true);
        setField(term781, term781.getClass(), "border", null);
        setIntField(term781, term781.getClass(), "flags", 0);
        setField(term781, term781.getClass(), "inputVerifier", null);
        setBooleanField(term781, term781.getClass(), "verifyInputWhenFocusTarget", false);
        setField(term781, term781.getClass(), "paintingChild", null);
        setField(term781, term781.getClass(), "popupMenu", null);
        setField(term781, term781.getClass(), "revalidateRunnableScheduled", null);
        setField(term781, term781.getClass(), "focusInputMap", null);
        setField(term781, term781.getClass(), "ancestorInputMap", null);
        setField(term781, term781.getClass(), "windowInputMap", null);
        setField(term781, term781.getClass(), "actionMap", null);
        setField(term781, term781.getClass(), "aaHint", null);
        setField(term781, term781.getClass(), "lcdRenderingHint", null);
        setField(term781, term781.getClass(), "component", null);
        setField(term781, term781.getClass(), "layoutMgr", null);
        setField(term781, term781.getClass(), "dispatcher", null);
        setField(term781, term781.getClass(), "focusTraversalPolicy", null);
        setBooleanField(term781, term781.getClass(), "focusCycleRoot", false);
        setBooleanField(term781, term781.getClass(), "focusTraversalPolicyProvider", false);
        setField(term781, term781.getClass(), "printingThreads", null);
        setBooleanField(term781, term781.getClass(), "printing", false);
        setField(term781, term781.getClass(), "containerListener", null);
        setIntField(term781, term781.getClass(), "listeningChildren", 0);
        setIntField(term781, term781.getClass(), "listeningBoundsChildren", 0);
        setIntField(term781, term781.getClass(), "descendantsCount", 0);
        setField(term781, term781.getClass(), "preserveBackgroundColor", null);
        setIntField(term781, term781.getClass(), "numOfHWComponents", 0);
        setIntField(term781, term781.getClass(), "numOfLWComponents", 0);
        setField(term781, term781.getClass(), "modalComp", null);
        setField(term781, term781.getClass(), "modalAppContext", null);
        setIntField(term781, term781.getClass(), "containerSerializedDataVersion", 0);
        setField(term781, term781.getClass(), "peer", null);
        setField(term781, term781.getClass(), "parent", null);
        setField(term781, term781.getClass(), "appContext", null);
        setIntField(term781, term781.getClass(), "x", 0);
        setIntField(term781, term781.getClass(), "y", 0);
        setIntField(term781, term781.getClass(), "width", 0);
        setIntField(term781, term781.getClass(), "height", 0);
        setField(term781, term781.getClass(), "foreground", null);
        setField(term781, term781.getClass(), "background", null);
        setField(term781, term781.getClass(), "font", null);
        setField(term781, term781.getClass(), "peerFont", null);
        setField(term781, term781.getClass(), "cursor", null);
        setField(term781, term781.getClass(), "locale", null);
        setField(term781, term781.getClass(), "graphicsConfig", null);
        setField(term781, term781.getClass(), "bufferStrategy", null);
        setBooleanField(term781, term781.getClass(), "ignoreRepaint", false);
        setBooleanField(term781, term781.getClass(), "visible", false);
        setBooleanField(term781, term781.getClass(), "enabled", false);
        setBooleanField(term781, term781.getClass(), "valid", false);
        setField(term781, term781.getClass(), "dropTarget", null);
        setField(term781, term781.getClass(), "popups", null);
        setField(term781, term781.getClass(), "name", null);
        setBooleanField(term781, term781.getClass(), "nameExplicitlySet", false);
        setBooleanField(term781, term781.getClass(), "focusable", false);
        setIntField(term781, term781.getClass(), "isFocusTraversableOverridden", 0);
        setField(term781, term781.getClass(), "focusTraversalKeys", null);
        setBooleanField(term781, term781.getClass(), "focusTraversalKeysEnabled", false);
        setField(term781, term781.getClass(), "acc", null);
        setField(term781, term781.getClass(), "minSize", null);
        setBooleanField(term781, term781.getClass(), "minSizeSet", false);
        setField(term781, term781.getClass(), "prefSize", null);
        setBooleanField(term781, term781.getClass(), "prefSizeSet", false);
        setField(term781, term781.getClass(), "maxSize", null);
        setBooleanField(term781, term781.getClass(), "maxSizeSet", false);
        setField(term781, term781.getClass(), "componentOrientation", null);
        setBooleanField(term781, term781.getClass(), "newEventsOnly", false);
        setField(term781, term781.getClass(), "componentListener", null);
        setField(term781, term781.getClass(), "focusListener", null);
        setField(term781, term781.getClass(), "hierarchyListener", null);
        setField(term781, term781.getClass(), "hierarchyBoundsListener", null);
        setField(term781, term781.getClass(), "keyListener", null);
        setField(term781, term781.getClass(), "mouseListener", null);
        setField(term781, term781.getClass(), "mouseMotionListener", null);
        setField(term781, term781.getClass(), "mouseWheelListener", null);
        setField(term781, term781.getClass(), "inputMethodListener", null);
        setLongField(term781, term781.getClass(), "eventMask", 0L);
        setField(term781, term781.getClass(), "changeSupport", null);
        setField(term781, term781.getClass(), "objectLock", null);
        setBooleanField(term781, term781.getClass(), "isPacked", false);
        setIntField(term781, term781.getClass(), "boundsOp", 0);
        setField(term781, term781.getClass(), "compoundShape", null);
        setField(term781, term781.getClass(), "mixingCutoutRegion", null);
        setBooleanField(term781, term781.getClass(), "isAddNotifyComplete", false);
        setBooleanField(term781, term781.getClass(), "backgroundEraseDisabled", false);
        setField(term781, term781.getClass(), "eventCache", null);
        setBooleanField(term781, term781.getClass(), "coalescingEnabled", false);
        setBooleanField(term781, term781.getClass(), "autoFocusTransferOnDisposal", false);
        setIntField(term781, term781.getClass(), "componentSerializedDataVersion", 0);
        setField(term781, term781.getClass(), "accessibleContext", null);
    }

    @Test
    public void test() throws Throwable, Throwable {
        Class<?> klass = Class.forName("io.github.moacirrf.netbeans.markdown.ui.preview.image.ImageLabel");
        Class<?>[] argTypes = new Class<?>[1];
        argTypes[0] = Class.forName("javax.swing.text.Element");
        Object[] args = new Object[1];
        args[0] = null;
        callMethod(klass, "createImageIcon", argTypes, term781, args);
    }

};


