/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 03:26:49 GMT 2026
 */

package io.github.janlely.jparser.impl.xml;

import org.junit.Test;
import static org.junit.Assert.*;
import io.github.janlely.jparser.impl.xml.XmlProp;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class XmlProp_ESTest extends XmlProp_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      XmlProp xmlProp0 = new XmlProp("ksac:[2rS_+snU%HwLz", "");
      xmlProp0.setValue("ksac:[2rS_+snU%HwLz");
      String string0 = xmlProp0.getValue();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder1 = xmlProp_XmlPropBuilder0.name("du[w");
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder1.build();
      String string0 = xmlProp0.getName();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      xmlProp0.setName("");
      String string0 = xmlProp0.getName();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = new XmlProp.XmlPropBuilder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      boolean boolean0 = xmlProp0.canEqual(xmlProp0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = new XmlProp.XmlPropBuilder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      boolean boolean0 = xmlProp0.canEqual("");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      String string0 = xmlProp0.getName();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      XmlProp xmlProp0 = new XmlProp("5^9&qAks~y", "5^9&qAks~y");
      XmlProp xmlProp1 = new XmlProp("5^9&qAks~y", "5^9&qAks~y");
      boolean boolean0 = xmlProp0.equals(xmlProp1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      xmlProp0.setName("");
      XmlProp xmlProp1 = new XmlProp("", "'bo/\"$<2Q*@HT/t+");
      xmlProp0.setValue("Q|ZaU/=");
      boolean boolean0 = xmlProp0.equals(xmlProp1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      xmlProp0.setName("");
      XmlProp xmlProp1 = new XmlProp("", "'bo/\"$<2Q*@HT/t+");
      boolean boolean0 = xmlProp0.equals(xmlProp1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      XmlProp xmlProp1 = xmlProp_XmlPropBuilder0.build();
      boolean boolean0 = xmlProp0.equals(xmlProp1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = new XmlProp.XmlPropBuilder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      boolean boolean0 = xmlProp0.equals("");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      boolean boolean0 = xmlProp0.equals(xmlProp0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = new XmlProp.XmlPropBuilder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      xmlProp0.setValue("9,2Aj!,yPQm");
      int int0 = xmlProp0.hashCode();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = new XmlProp.XmlPropBuilder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      int int0 = xmlProp0.hashCode();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = new XmlProp.XmlPropBuilder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      xmlProp0.setName("NxD<9");
      int int0 = xmlProp0.hashCode();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      String string0 = xmlProp_XmlPropBuilder0.toString();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder1 = xmlProp_XmlPropBuilder0.value("");
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder1.build();
      String string0 = xmlProp0.getValue();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      String string0 = xmlProp0.toString();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      xmlProp0.setName("Q|ZaU/=");
      XmlProp xmlProp1 = new XmlProp("", "'bo/\"$<2Q*@HT/t+");
      boolean boolean0 = xmlProp0.equals(xmlProp1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      String string0 = xmlProp0.getValue();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      XmlProp.XmlPropBuilder xmlProp_XmlPropBuilder0 = XmlProp.builder();
      XmlProp xmlProp0 = xmlProp_XmlPropBuilder0.build();
      XmlProp xmlProp1 = new XmlProp("", "'bo/\"$<2Q*@HT/t+");
      boolean boolean0 = xmlProp0.equals(xmlProp1);
  }
}
