/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 17:03:49 GMT 2026
 */

package icu.samnyan.aqua.sega.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import icu.samnyan.aqua.sega.util.VersionInfo;
import icu.samnyan.aqua.sega.util.VersionUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VersionUtil_ESTest extends VersionUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = VersionUtil.getTargetVersion(".", "5");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = VersionUtil.getTargetVersion("", "L0`<3u0>ef");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        VersionUtil.parseVersion((String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        VersionUtil.getTargetVersion((String) null, (String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = VersionUtil.getTargetVersion("4", "5");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = VersionUtil.getTargetVersion("9", "5");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = VersionUtil.getTargetVersion("5", "5");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VersionInfo versionInfo0 = VersionUtil.parseVersion("8.Sx]*ODQvJ$+5%Z\"");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VersionInfo versionInfo0 = VersionUtil.parseVersion("4");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VersionInfo versionInfo0 = VersionUtil.parseVersion(".");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VersionUtil versionUtil0 = new VersionUtil();
  }
}
