/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 19 04:11:14 GMT 2026
 */

package nl.jiankai.mapper.converters;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.sql.Time;
import java.time.LocalTime;
import nl.jiankai.mapper.converters.TimeToLocalTimeConverter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TimeToLocalTimeConverter_ESTest extends TimeToLocalTimeConverter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimeToLocalTimeConverter timeToLocalTimeConverter0 = new TimeToLocalTimeConverter();
      Time time0 = new Time(0L);
      LocalTime localTime0 = timeToLocalTimeConverter0.convert(time0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimeToLocalTimeConverter timeToLocalTimeConverter0 = new TimeToLocalTimeConverter();
      Class<LocalTime> class0 = timeToLocalTimeConverter0.target();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimeToLocalTimeConverter timeToLocalTimeConverter0 = new TimeToLocalTimeConverter();
      Class<Time> class0 = timeToLocalTimeConverter0.source();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TimeToLocalTimeConverter timeToLocalTimeConverter0 = new TimeToLocalTimeConverter();
      // Undeclared exception!
      try { 
        timeToLocalTimeConverter0.convert((Time) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
