/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 17:36:53 GMT 2026
 */

package com.salomondev.interceptor.interceptor.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.salomondev.interceptor.interceptor.service.TraceServiceImpl;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletRequestWrapper;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpServletResponseWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TraceServiceImpl_ESTest extends TraceServiceImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TraceServiceImpl traceServiceImpl0 = new TraceServiceImpl();
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(httpServletRequest0).getRemoteAddr();
      doReturn((String) null).when(httpServletRequest0).getMethod();
      doReturn((String) null).when(httpServletRequest0).getRequestURI();
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      Long long0 = new Long((-2147483648L));
      traceServiceImpl0.loggerDto.setTimeConsumeService(long0);
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(httpServletResponse0).getStatus();
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      traceServiceImpl0.registerTrace(httpServletRequestWrapper0, httpServletResponseWrapper0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TraceServiceImpl traceServiceImpl0 = new TraceServiceImpl();
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((Map) null).when(httpServletRequest0).getParameterMap();
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      // Undeclared exception!
      try { 
        traceServiceImpl0.registerInitTime(httpServletRequestWrapper0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TraceServiceImpl traceServiceImpl0 = new TraceServiceImpl();
      traceServiceImpl0.registerBodyRequest((Object) null);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((Map) null).when(httpServletRequest0).getParameterMap();
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      // Undeclared exception!
      try { 
        traceServiceImpl0.registerInitTime(httpServletRequestWrapper0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TraceServiceImpl traceServiceImpl0 = new TraceServiceImpl();
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      httpServletRequestWrapper0.setRequest(httpServletRequestWrapper0);
      // Undeclared exception!
      try { 
        traceServiceImpl0.registerInitTime(httpServletRequestWrapper0);
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TraceServiceImpl traceServiceImpl0 = new TraceServiceImpl();
      Hashtable<String, String[]> hashtable0 = new Hashtable<String, String[]>();
      String[] stringArray0 = new String[0];
      String[] stringArray1 = hashtable0.put("qi*sk*", stringArray0);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn(hashtable0, hashtable0).when(httpServletRequest0).getParameterMap();
      // Undeclared exception!
      try { 
        traceServiceImpl0.registerInitTime(httpServletRequest0);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TraceServiceImpl traceServiceImpl0 = new TraceServiceImpl();
      traceServiceImpl0.loggerDto = null;
      // Undeclared exception!
      try { 
        traceServiceImpl0.registerBodyRequest((Object) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.salomondev.interceptor.interceptor.service.TraceServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TraceServiceImpl traceServiceImpl0 = new TraceServiceImpl();
      traceServiceImpl0.loggerDto = null;
      // Undeclared exception!
      try { 
        traceServiceImpl0.registerBody((Object) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.salomondev.interceptor.interceptor.service.TraceServiceImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TraceServiceImpl traceServiceImpl0 = new TraceServiceImpl();
      HashMap<String, String[]> hashMap0 = new HashMap<String, String[]>();
      String[] stringArray0 = new String[7];
      String[] stringArray1 = hashMap0.put("com.salomondev.interceptor.interceptor.service.TraceServiceImpl", stringArray0);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn(hashMap0, hashMap0, hashMap0).when(httpServletRequest0).getParameterMap();
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      traceServiceImpl0.registerInitTime(httpServletRequestWrapper0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TraceServiceImpl traceServiceImpl0 = new TraceServiceImpl();
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      // Undeclared exception!
      try { 
        traceServiceImpl0.registerTrace(httpServletRequestWrapper0, httpServletResponseWrapper0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.salomondev.interceptor.interceptor.service.TraceServiceImpl", e);
      }
  }
}
