/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 17:34:12 GMT 2026
 */

package com.salomondev.interceptor.interceptor;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.salomondev.interceptor.interceptor.ResponseBodyInterceptor;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.core.MethodParameter;
import org.springframework.http.MediaType;
import org.springframework.http.converter.ByteArrayHttpMessageConverter;
import org.springframework.http.converter.ResourceRegionHttpMessageConverter;
import org.springframework.http.server.ServerHttpRequest;
import org.springframework.http.server.ServerHttpResponse;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ResponseBodyInterceptor_ESTest extends ResponseBodyInterceptor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResponseBodyInterceptor responseBodyInterceptor0 = new ResponseBodyInterceptor();
      Class<ResourceRegionHttpMessageConverter> class0 = ResourceRegionHttpMessageConverter.class;
      boolean boolean0 = responseBodyInterceptor0.supports((MethodParameter) null, class0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ResponseBodyInterceptor responseBodyInterceptor0 = new ResponseBodyInterceptor();
      MediaType mediaType0 = MediaType.APPLICATION_XML;
      Class<ByteArrayHttpMessageConverter> class0 = ByteArrayHttpMessageConverter.class;
      // Undeclared exception!
      try { 
        responseBodyInterceptor0.beforeBodyWrite((Object) null, (MethodParameter) null, mediaType0, class0, (ServerHttpRequest) null, (ServerHttpResponse) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.salomondev.interceptor.interceptor.ResponseBodyInterceptor", e);
      }
  }
}
