/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 19 05:19:38 GMT 2026
 */

package com.amazonaws.samples.stream.temperature.enrichment.async;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.amazonaws.samples.stream.temperature.enrichment.async.AsyncEnrichmentFunction;
import com.amazonaws.samples.stream.temperature.event.EnrichedTemperature;
import com.amazonaws.samples.stream.temperature.event.Temperature;
import org.apache.flink.streaming.api.functions.async.ResultFuture;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AsyncEnrichmentFunction_ESTest extends AsyncEnrichmentFunction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AsyncEnrichmentFunction asyncEnrichmentFunction0 = new AsyncEnrichmentFunction("dH`$AU(rX8v");
      try { 
        asyncEnrichmentFunction0.close();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.amazonaws.samples.stream.temperature.enrichment.async.AsyncEnrichmentFunction", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AsyncEnrichmentFunction asyncEnrichmentFunction0 = new AsyncEnrichmentFunction("{3zJ?");
      Temperature temperature0 = new Temperature("BCpGI.X(-0ag,IDb", (-2649L), 1588L, "{3zJ?");
      ResultFuture<EnrichedTemperature> resultFuture0 = (ResultFuture<EnrichedTemperature>) mock(ResultFuture.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        asyncEnrichmentFunction0.asyncInvoke(temperature0, resultFuture0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.amazonaws.samples.stream.temperature.enrichment.async.AsyncEnrichmentFunction", e);
      }
  }
}
