/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Aug 08 06:23:57 GMT 2026
 */

package tech.jiayezheng.miniJuliaSonar.ast;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class KW_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "tech.jiayezheng.miniJuliaSonar.ast.KW"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(KW_ESTest_scaffolding.class.getClassLoader() ,
      "tech.jiayezheng.miniJuliaSonar.ast.Global",
      "tech.jiayezheng.miniJuliaSonar.ast.Try",
      "tech.jiayezheng.miniJuliaSonar.ast.If",
      "tech.jiayezheng.miniJuliaSonar.ast.Missing",
      "tech.jiayezheng.miniJuliaSonar.ast.LPAREN",
      "tech.jiayezheng.miniJuliaSonar.ast.BaseType",
      "tech.jiayezheng.miniJuliaSonar.ast.LSQUARE",
      "tech.jiayezheng.miniJuliaSonar.ast.Str",
      "tech.jiayezheng.miniJuliaSonar.ast.Break",
      "tech.jiayezheng.miniJuliaSonar.ast.VarArg",
      "tech.jiayezheng.miniJuliaSonar.ast.KeyWord",
      "tech.jiayezheng.miniJuliaSonar.ast.Node",
      "tech.jiayezheng.miniJuliaSonar.ast.Block",
      "tech.jiayezheng.miniJuliaSonar.ast.Assign",
      "tech.jiayezheng.miniJuliaSonar.ast.SymbolKind",
      "tech.jiayezheng.miniJuliaSonar.$",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaInt",
      "tech.jiayezheng.miniJuliaSonar.ast.End",
      "tech.jiayezheng.miniJuliaSonar.ast.Complex",
      "tech.jiayezheng.miniJuliaSonar.ast.RSQUARE",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaBool",
      "tech.jiayezheng.miniJuliaSonar.ast.Where",
      "tech.jiayezheng.miniJuliaSonar.ast.PrimitiveType",
      "tech.jiayezheng.miniJuliaSonar.ast.Return",
      "tech.jiayezheng.miniJuliaSonar.ast.Do",
      "tech.jiayezheng.miniJuliaSonar.ast.Dot",
      "tech.jiayezheng.miniJuliaSonar.ast.For",
      "tech.jiayezheng.miniJuliaSonar.ast.Call",
      "tech.jiayezheng.miniJuliaSonar.ast.Catch",
      "tech.jiayezheng.miniJuliaSonar.ast.ParamType",
      "tech.jiayezheng.miniJuliaSonar.ast.Operator",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaComplex",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaFloat",
      "tech.jiayezheng.miniJuliaSonar.ast.SubType",
      "tech.jiayezheng.miniJuliaSonar.ast.UnaryOp",
      "tech.jiayezheng.miniJuliaSonar.ast.Symbol",
      "tech.jiayezheng.miniJuliaSonar.ast.Op",
      "tech.jiayezheng.miniJuliaSonar.ast.FuncDef",
      "tech.jiayezheng.miniJuliaSonar.ast.Root",
      "tech.jiayezheng.miniJuliaSonar.ast.Url",
      "tech.jiayezheng.miniJuliaSonar.ast.NodeType",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaModule",
      "tech.jiayezheng.miniJuliaSonar.ast.Nothing",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaBool$BoolValue",
      "tech.jiayezheng.miniJuliaSonar.ast.Expr",
      "tech.jiayezheng.miniJuliaSonar.ast.QuoteNode",
      "tech.jiayezheng.miniJuliaSonar.ast.FuncCombineCall",
      "tech.jiayezheng.miniJuliaSonar.ast.Continue",
      "tech.jiayezheng.miniJuliaSonar.ast.AbstractType",
      "tech.jiayezheng.miniJuliaSonar.ast.TypeDecl",
      "tech.jiayezheng.miniJuliaSonar.ast.Dummy",
      "tech.jiayezheng.miniJuliaSonar.ast.BinOp",
      "tech.jiayezheng.miniJuliaSonar.ast.Comma",
      "tech.jiayezheng.miniJuliaSonar.ast.StructDef",
      "tech.jiayezheng.miniJuliaSonar.ast.Tuple",
      "tech.jiayezheng.miniJuliaSonar.ast.RPAREN",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaVector",
      "tech.jiayezheng.miniJuliaSonar.ast.Ref",
      "tech.jiayezheng.miniJuliaSonar.ast.RBRACE",
      "tech.jiayezheng.miniJuliaSonar.ast.LBRACE",
      "tech.jiayezheng.miniJuliaSonar.ast.Char",
      "tech.jiayezheng.miniJuliaSonar.ast.KW",
      "tech.jiayezheng.miniJuliaSonar.ast.Union",
      "tech.jiayezheng.miniJuliaSonar.ast.While"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(KW_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "tech.jiayezheng.miniJuliaSonar.ast.Node",
      "tech.jiayezheng.miniJuliaSonar.ast.KW",
      "tech.jiayezheng.miniJuliaSonar.ast.NodeType",
      "tech.jiayezheng.miniJuliaSonar.ast.Symbol",
      "tech.jiayezheng.miniJuliaSonar.ast.Global",
      "tech.jiayezheng.miniJuliaSonar.ast.Union",
      "tech.jiayezheng.miniJuliaSonar.ast.Tuple",
      "tech.jiayezheng.miniJuliaSonar.ast.Block",
      "tech.jiayezheng.miniJuliaSonar.ast.RBRACE",
      "tech.jiayezheng.miniJuliaSonar.ast.RPAREN",
      "tech.jiayezheng.miniJuliaSonar.ast.BaseType",
      "tech.jiayezheng.miniJuliaSonar.ast.Op",
      "tech.jiayezheng.miniJuliaSonar.ast.TypeDecl",
      "tech.jiayezheng.miniJuliaSonar.ast.Comma",
      "tech.jiayezheng.miniJuliaSonar.ast.FuncDef",
      "tech.jiayezheng.miniJuliaSonar.ast.Call",
      "tech.jiayezheng.miniJuliaSonar.ast.LPAREN",
      "tech.jiayezheng.miniJuliaSonar.ast.Assign",
      "tech.jiayezheng.miniJuliaSonar.$",
      "tech.jiayezheng.miniJuliaSonar.ast.LSQUARE",
      "tech.jiayezheng.miniJuliaSonar.ast.Dummy",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaVector",
      "tech.jiayezheng.miniJuliaSonar.ast.While",
      "tech.jiayezheng.miniJuliaSonar.ast.Do",
      "tech.jiayezheng.miniJuliaSonar.ast.Ref",
      "tech.jiayezheng.miniJuliaSonar.ast.PrimitiveType",
      "tech.jiayezheng.miniJuliaSonar.ast.ParamType",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaBool",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaBool$BoolValue",
      "tech.jiayezheng.miniJuliaSonar.ast.Dot",
      "tech.jiayezheng.miniJuliaSonar.ast.StructDef",
      "tech.jiayezheng.miniJuliaSonar.ast.Str",
      "tech.jiayezheng.miniJuliaSonar.ast.Break",
      "tech.jiayezheng.miniJuliaSonar.ast.AbstractType",
      "tech.jiayezheng.miniJuliaSonar.ast.LBRACE",
      "tech.jiayezheng.miniJuliaSonar.ast.Where",
      "tech.jiayezheng.miniJuliaSonar.ast.SubType",
      "tech.jiayezheng.miniJuliaSonar.ast.If",
      "tech.jiayezheng.miniJuliaSonar.ast.Operator",
      "tech.jiayezheng.miniJuliaSonar.ast.FuncCombineCall",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaInt",
      "tech.jiayezheng.miniJuliaSonar.ast.Expr",
      "tech.jiayezheng.miniJuliaSonar.ast.BinOp",
      "tech.jiayezheng.miniJuliaSonar.ast.VarArg",
      "tech.jiayezheng.miniJuliaSonar.ast.RSQUARE",
      "tech.jiayezheng.miniJuliaSonar.ast.Return",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaComplex",
      "tech.jiayezheng.miniJuliaSonar.ast.Root",
      "tech.jiayezheng.miniJuliaSonar.ast.UnaryOp",
      "tech.jiayezheng.miniJuliaSonar.ast.End",
      "tech.jiayezheng.miniJuliaSonar.ast.Continue",
      "tech.jiayezheng.miniJuliaSonar.ast.Nothing",
      "tech.jiayezheng.miniJuliaSonar.ast.Missing",
      "tech.jiayezheng.miniJuliaSonar.ast.Catch",
      "tech.jiayezheng.miniJuliaSonar.ast.Url",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaFloat",
      "tech.jiayezheng.miniJuliaSonar.ast.QuoteNode",
      "tech.jiayezheng.miniJuliaSonar.ast.KeyWord",
      "tech.jiayezheng.miniJuliaSonar.ast.For",
      "tech.jiayezheng.miniJuliaSonar.ast.Char",
      "tech.jiayezheng.miniJuliaSonar.ast.Try",
      "tech.jiayezheng.miniJuliaSonar.ast.Complex",
      "tech.jiayezheng.miniJuliaSonar.ast.JuliaModule"
    );
  }
}
