/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 12 09:19:05 GMT 2026
 */

package refactoring.app.chapter01.performanceCalculator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import refactoring.app.chapter01.Performance;
import refactoring.app.chapter01.Play;
import refactoring.app.chapter01.PlayType;
import refactoring.app.chapter01.performanceCalculator.PerformanceCalculator;
import refactoring.app.chapter01.performanceCalculator.PerformanceCalculatorFactory;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PerformanceCalculatorFactory_ESTest extends PerformanceCalculatorFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PerformanceCalculatorFactory performanceCalculatorFactory0 = new PerformanceCalculatorFactory();
      try { 
        performanceCalculatorFactory0.createPerformanceCalculator((Performance) null, (Play) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PerformanceCalculatorFactory performanceCalculatorFactory0 = new PerformanceCalculatorFactory();
      Performance performance0 = new Performance("refactoring.app.chapter01.performanceCalculator.PerformanceCalculatorFactory", 3080);
      PlayType playType0 = PlayType.COMEDY;
      Play play0 = new Play("", playType0);
      PerformanceCalculator performanceCalculator0 = performanceCalculatorFactory0.createPerformanceCalculator(performance0, play0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PerformanceCalculatorFactory performanceCalculatorFactory0 = new PerformanceCalculatorFactory();
      PlayType playType0 = PlayType.TRAGEDY;
      Play play0 = new Play((String) null, playType0);
      PerformanceCalculator performanceCalculator0 = performanceCalculatorFactory0.createPerformanceCalculator((Performance) null, play0);
  }
}
