/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 16:04:22 GMT 2026
 */

package kyungseo.poc.simple.web.appcore.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import javax.swing.JRadioButton;
import kyungseo.poc.simple.web.appcore.util.SpringContextUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.support.ChildBeanDefinition;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.context.support.FileSystemXmlApplicationContext;
import org.springframework.context.support.GenericXmlApplicationContext;
import org.springframework.context.support.StaticApplicationContext;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SpringContextUtil_ESTest extends SpringContextUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      String[] stringArray0 = new String[0];
      FileSystemXmlApplicationContext fileSystemXmlApplicationContext0 = new FileSystemXmlApplicationContext(stringArray0);
      springContextUtil0.setApplicationContext(fileSystemXmlApplicationContext0);
      Object object0 = SpringContextUtil.getBean("applicationEventMulticaster");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      StaticApplicationContext staticApplicationContext0 = new StaticApplicationContext();
      springContextUtil0.setApplicationContext(staticApplicationContext0);
      Class<Object> class0 = Object.class;
      Object object0 = SpringContextUtil.getBean(class0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      StaticApplicationContext staticApplicationContext0 = new StaticApplicationContext((ApplicationContext) null);
      springContextUtil0.setApplicationContext(staticApplicationContext0);
      ApplicationContext applicationContext0 = SpringContextUtil.getApplicationContext();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      String[] stringArray0 = new String[0];
      FileSystemXmlApplicationContext fileSystemXmlApplicationContext0 = new FileSystemXmlApplicationContext(stringArray0);
      springContextUtil0.setApplicationContext(fileSystemXmlApplicationContext0);
      ApplicationContext applicationContext0 = SpringContextUtil.getApplicationContext();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      StaticApplicationContext staticApplicationContext0 = new StaticApplicationContext();
      springContextUtil0.setApplicationContext(staticApplicationContext0);
      // Undeclared exception!
      try { 
        SpringContextUtil.getBean("lifecycleProcessor");
      } catch(RuntimeException e) {
         //
         // No bean named 'lifecycleProcessor' available
         //
         verifyException("org.springframework.beans.factory.support.DefaultListableBeanFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      GenericXmlApplicationContext genericXmlApplicationContext0 = new GenericXmlApplicationContext();
      springContextUtil0.setApplicationContext(genericXmlApplicationContext0);
      // Undeclared exception!
      try { 
        SpringContextUtil.getBean("applicationEventMulticaster");
      } catch(IllegalStateException e) {
         //
         // org.springframework.context.support.GenericXmlApplicationContext@2 has not been refreshed yet
         //
         verifyException("org.springframework.context.support.AbstractApplicationContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      StaticApplicationContext staticApplicationContext0 = new StaticApplicationContext();
      springContextUtil0.setApplicationContext(staticApplicationContext0);
      // Undeclared exception!
      try { 
        SpringContextUtil.getBean((String) null);
      } catch(IllegalArgumentException e) {
         //
         // 'name' must not be null
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      String[] stringArray0 = new String[0];
      ClassPathXmlApplicationContext classPathXmlApplicationContext0 = new ClassPathXmlApplicationContext(stringArray0);
      springContextUtil0.setApplicationContext(classPathXmlApplicationContext0);
      Class<Object> class0 = Object.class;
      // Undeclared exception!
      try { 
        SpringContextUtil.getBean(class0);
      } catch(RuntimeException e) {
         //
         // No qualifying bean of type 'java.lang.Object' available: expected single matching bean but found 7: environment,systemProperties,systemEnvironment,applicationStartup,messageSource,applicationEventMulticaster,lifecycleProcessor
         //
         verifyException("org.springframework.beans.factory.support.DefaultListableBeanFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      Class<Object>[] classArray0 = (Class<Object>[]) Array.newInstance(Class.class, 2);
      Class<Object> class0 = Object.class;
      classArray0[0] = class0;
      classArray0[1] = class0;
      AnnotationConfigApplicationContext annotationConfigApplicationContext0 = new AnnotationConfigApplicationContext(classArray0);
      ChildBeanDefinition childBeanDefinition0 = new ChildBeanDefinition("KeyPairGenerator.ElGamal");
      annotationConfigApplicationContext0.registerBeanDefinition("KeyPairGenerator.ElGamal", childBeanDefinition0);
      springContextUtil0.setApplicationContext(annotationConfigApplicationContext0);
      Class<JRadioButton> class1 = JRadioButton.class;
      // Undeclared exception!
      try { 
        SpringContextUtil.getBean(class1);
      } catch(RuntimeException e) {
         //
         // Invalid bean definition with name 'KeyPairGenerator.ElGamal' defined in null: Could not resolve parent bean definition 'KeyPairGenerator.ElGamal'; nested exception is org.evosuite.runtime.mock.java.lang.MockThrowable: No bean named 'KeyPairGenerator.ElGamal' available: Parent name 'KeyPairGenerator.ElGamal' is equal to bean name 'KeyPairGenerator.ElGamal': cannot be resolved without a ConfigurableBeanFactory parent
         //
         verifyException("org.springframework.beans.factory.support.AbstractBeanFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      StaticApplicationContext staticApplicationContext0 = new StaticApplicationContext();
      springContextUtil0.setApplicationContext(staticApplicationContext0);
      Class<String> class0 = String.class;
      // Undeclared exception!
      try { 
        SpringContextUtil.getBean(class0);
      } catch(RuntimeException e) {
         //
         // No qualifying bean of type 'java.lang.String' available
         //
         verifyException("org.springframework.beans.factory.support.DefaultListableBeanFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Class<Object> class0 = Object.class;
      // Undeclared exception!
      try { 
        SpringContextUtil.getBean(class0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        SpringContextUtil.getBean("lifecycleProcessor");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ApplicationContext applicationContext0 = SpringContextUtil.getApplicationContext();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SpringContextUtil springContextUtil0 = new SpringContextUtil();
      StaticApplicationContext staticApplicationContext0 = new StaticApplicationContext();
      springContextUtil0.setApplicationContext(staticApplicationContext0);
      // Undeclared exception!
      try { 
        SpringContextUtil.getBean((Class<Object>) null);
      } catch(IllegalArgumentException e) {
         //
         // Required type must not be null
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }
}
