/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Aug 06 04:32:33 GMT 2026
 */

package org.commoncrawl.webgraph;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

@EvoSuiteClassExclude
public class JoinSortRanks_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  protected static ExecutorService executor; 

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.commoncrawl.webgraph.JoinSortRanks"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    executor = Executors.newCachedThreadPool(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    executor.shutdownNow(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/suelenfelix/TCC/teste/analise-geracao-testes/projects/commoncrawl_cc-webgraph"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(JoinSortRanks_ESTest_scaffolding.class.getClassLoader() ,
      "it.unimi.dsi.fastutil.BigArrays",
      "it.unimi.dsi.fastutil.floats.AbstractFloatCollection",
      "it.unimi.dsi.fastutil.floats.FloatBigArrays$BigArrayHashStrategy",
      "it.unimi.dsi.fastutil.doubles.DoubleCollection",
      "it.unimi.dsi.fastutil.chars.CharIterator",
      "it.unimi.dsi.fastutil.floats.FloatMappedBigList",
      "it.unimi.dsi.fastutil.io.MeasurableOutputStream",
      "it.unimi.dsi.fastutil.doubles.DoubleBigList",
      "it.unimi.dsi.fastutil.bytes.ByteIterator",
      "it.unimi.dsi.fastutil.Size64",
      "it.unimi.dsi.fastutil.chars.CharIterable",
      "it.unimi.dsi.fastutil.bytes.ByteIterable",
      "it.unimi.dsi.fastutil.floats.FloatBigArrays$ForkJoinQuickSort",
      "it.unimi.dsi.fastutil.io.MeasurableInputStream",
      "it.unimi.dsi.fastutil.doubles.DoubleBigListIterator",
      "it.unimi.dsi.fastutil.doubles.DoubleBidirectionalIterator",
      "it.unimi.dsi.fastutil.doubles.DoubleBigArrays$BigArrayHashStrategy",
      "it.unimi.dsi.fastutil.Arrays",
      "it.unimi.dsi.fastutil.doubles.DoubleBigArrays",
      "it.unimi.dsi.fastutil.ints.IntComparator",
      "it.unimi.dsi.fastutil.io.RepositionableStream",
      "it.unimi.dsi.fastutil.doubles.DoubleBigArrays$ForkJoinQuickSortComp",
      "it.unimi.dsi.fastutil.Arrays$ForkJoinGenericQuickSort",
      "it.unimi.dsi.fastutil.doubles.AbstractDoubleBigList$DoubleSubList",
      "it.unimi.dsi.fastutil.floats.FloatIterable",
      "it.unimi.dsi.fastutil.Stack",
      "it.unimi.dsi.fastutil.floats.FloatBigArrays",
      "it.unimi.dsi.fastutil.doubles.DoubleMappedBigList",
      "it.unimi.dsi.fastutil.floats.FloatIterator",
      "it.unimi.dsi.fastutil.objects.ObjectBidirectionalIterator",
      "it.unimi.dsi.fastutil.doubles.DoubleBigArrays$ForkJoinQuickSort",
      "it.unimi.dsi.fastutil.BigList",
      "it.unimi.dsi.fastutil.shorts.ShortIterable",
      "it.unimi.dsi.fastutil.shorts.ShortIterator",
      "it.unimi.dsi.fastutil.doubles.AbstractDoubleCollection",
      "it.unimi.dsi.fastutil.io.FastBufferedInputStream",
      "it.unimi.dsi.fastutil.floats.AbstractFloatBigList$FloatSubList",
      "it.unimi.dsi.fastutil.floats.AbstractFloatBigList$FloatRandomAccessSubList",
      "it.unimi.dsi.fastutil.booleans.BooleanIterator",
      "it.unimi.dsi.fastutil.booleans.BooleanIterable",
      "org.commoncrawl.webgraph.JoinSortRanks$JoinSortRanksBig",
      "it.unimi.dsi.fastutil.Hash$Strategy",
      "it.unimi.dsi.fastutil.ints.IntIterator",
      "it.unimi.dsi.fastutil.doubles.DoubleIterable",
      "it.unimi.dsi.fastutil.doubles.DoubleStack",
      "it.unimi.dsi.fastutil.longs.LongIterable",
      "it.unimi.dsi.fastutil.BidirectionalIterator",
      "org.commoncrawl.webgraph.JoinSortRanks",
      "it.unimi.dsi.fastutil.ints.IntIterable",
      "it.unimi.dsi.fastutil.longs.LongIterator",
      "it.unimi.dsi.fastutil.doubles.DoubleIterator",
      "it.unimi.dsi.fastutil.floats.FloatStack",
      "it.unimi.dsi.fastutil.objects.ObjectIterator",
      "it.unimi.dsi.fastutil.doubles.AbstractDoubleBigList$DoubleRandomAccessSubList",
      "it.unimi.dsi.fastutil.io.BinIO",
      "it.unimi.dsi.fastutil.io.MeasurableStream",
      "it.unimi.dsi.fastutil.floats.FloatBidirectionalIterator",
      "it.unimi.dsi.fastutil.floats.FloatBigListIterator",
      "it.unimi.dsi.fastutil.doubles.AbstractDoubleBigList",
      "it.unimi.dsi.fastutil.longs.LongComparator",
      "it.unimi.dsi.fastutil.io.FastBufferedOutputStream",
      "it.unimi.dsi.fastutil.floats.FloatCollection",
      "it.unimi.dsi.fastutil.floats.FloatBigList",
      "it.unimi.dsi.fastutil.floats.AbstractFloatBigList",
      "it.unimi.dsi.fastutil.floats.FloatBigArrays$ForkJoinQuickSortComp",
      "it.unimi.dsi.fastutil.BigListIterator"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(JoinSortRanks_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.commoncrawl.webgraph.JoinSortRanks",
      "org.commoncrawl.webgraph.JoinSortRanks$JoinSortRanksBig",
      "it.unimi.dsi.fastutil.Arrays",
      "it.unimi.dsi.fastutil.io.BinIO",
      "it.unimi.dsi.fastutil.floats.AbstractFloatCollection",
      "it.unimi.dsi.fastutil.floats.AbstractFloatBigList",
      "it.unimi.dsi.fastutil.floats.FloatMappedBigList",
      "it.unimi.dsi.fastutil.doubles.AbstractDoubleCollection",
      "it.unimi.dsi.fastutil.doubles.AbstractDoubleBigList",
      "it.unimi.dsi.fastutil.doubles.DoubleMappedBigList",
      "it.unimi.dsi.fastutil.BigArrays",
      "it.unimi.dsi.fastutil.doubles.DoubleBigArrays$BigArrayHashStrategy",
      "it.unimi.dsi.fastutil.doubles.DoubleBigArrays",
      "it.unimi.dsi.fastutil.floats.FloatBigArrays$BigArrayHashStrategy",
      "it.unimi.dsi.fastutil.floats.FloatBigArrays"
    );
  }
}
