/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 03:10:06 GMT 2026
 */

package com.github.nylle.javafixture;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.github.nylle.javafixture.PseudoRandom;
import com.github.nylle.javafixture.specimen.constraints.StringConstraints;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PseudoRandom_ESTest extends PseudoRandom_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      StringConstraints stringConstraints0 = new StringConstraints(128, 899);
      Double double0 = pseudoRandom0.nextDouble(true);
      String string0 = pseudoRandom0.nextString(stringConstraints0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Double double0 = pseudoRandom0.nextDouble(true);
      Long long0 = pseudoRandom0.nextLong(true);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      boolean boolean0 = linkedList0.add((Object) pseudoRandom0);
      List<Object> list0 = pseudoRandom0.shuffled((Collection<Object>) linkedList0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      StringConstraints stringConstraints0 = new StringConstraints(0, 899);
      String string0 = pseudoRandom0.nextString(stringConstraints0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Byte byte0 = pseudoRandom0.nextByte();
      Short short0 = pseudoRandom0.nextShort(true);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Random.setNextRandom(32768);
      Short short0 = pseudoRandom0.nextShort(false);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Integer integer0 = pseudoRandom0.nextInt(false);
      Float float0 = pseudoRandom0.nextFloat(true);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Random.setNextRandom(5873);
      Character character0 = pseudoRandom0.nextChar();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      // Undeclared exception!
      try { 
        pseudoRandom0.shuffled((Collection<String>) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      // Undeclared exception!
      try { 
        pseudoRandom0.nextString((StringConstraints) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      StringConstraints stringConstraints0 = new StringConstraints(10, (-3467));
      // Undeclared exception!
      try { 
        pseudoRandom0.nextString(stringConstraints0);
      } catch(RuntimeException e) {
         //
         // maximum must be greater than or equal minimum
         //
         verifyException("com.github.nylle.javafixture.PseudoRandom", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      StringConstraints stringConstraints0 = new StringConstraints((-579), (-579));
      // Undeclared exception!
      try { 
        pseudoRandom0.nextString(stringConstraints0);
      } catch(RuntimeException e) {
         //
         // minimum must be non-negative
         //
         verifyException("com.github.nylle.javafixture.PseudoRandom", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Double double0 = pseudoRandom0.nextDouble(true);
      Integer integer0 = pseudoRandom0.nextInt(true);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Double double0 = pseudoRandom0.nextDouble(false);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Float float0 = pseudoRandom0.nextFloat(true);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Float float0 = pseudoRandom0.nextFloat(false);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Long long0 = pseudoRandom0.nextLong(true);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Long long0 = pseudoRandom0.nextLong(false);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Integer integer0 = pseudoRandom0.nextInt(false);
      Double double0 = pseudoRandom0.nextDouble(true);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Short short0 = pseudoRandom0.nextShort(true);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      List<String> list0 = pseudoRandom0.shuffled((Collection<String>) linkedList0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Character character0 = pseudoRandom0.nextChar();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      StringConstraints stringConstraints0 = new StringConstraints(5873, 5873);
      String string0 = pseudoRandom0.nextString(stringConstraints0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PseudoRandom pseudoRandom0 = new PseudoRandom();
      Boolean boolean0 = pseudoRandom0.nextBool();
  }
}
