/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 12:59:49 GMT 2026
 */

package programmerzamannow.spring.core.data.cyclic;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import programmerzamannow.spring.core.data.cyclic.CyclicA;
import programmerzamannow.spring.core.data.cyclic.CyclicB;
import programmerzamannow.spring.core.data.cyclic.CyclicC;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CyclicA_ESTest extends CyclicA_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CyclicC cyclicC0 = new CyclicC((CyclicA) null);
      CyclicB cyclicB0 = new CyclicB(cyclicC0);
      CyclicA cyclicA0 = new CyclicA(cyclicB0);
      CyclicB cyclicB1 = cyclicA0.getCyclicB();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CyclicC cyclicC0 = new CyclicC((CyclicA) null);
      CyclicB cyclicB0 = new CyclicB(cyclicC0);
      CyclicA cyclicA0 = new CyclicA(cyclicB0);
      boolean boolean0 = cyclicA0.canEqual(cyclicA0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CyclicA cyclicA0 = new CyclicA((CyclicB) null);
      boolean boolean0 = cyclicA0.canEqual((Object) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CyclicA cyclicA0 = new CyclicA((CyclicB) null);
      CyclicB cyclicB0 = cyclicA0.getCyclicB();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CyclicC cyclicC0 = new CyclicC((CyclicA) null);
      CyclicB cyclicB0 = new CyclicB(cyclicC0);
      CyclicA cyclicA0 = new CyclicA(cyclicB0);
      CyclicA cyclicA1 = new CyclicA(cyclicB0);
      boolean boolean0 = cyclicA0.equals(cyclicA1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CyclicA cyclicA0 = new CyclicA((CyclicB) null);
      CyclicC cyclicC0 = new CyclicC(cyclicA0);
      CyclicB cyclicB0 = new CyclicB(cyclicC0);
      CyclicA cyclicA1 = new CyclicA(cyclicB0);
      boolean boolean0 = cyclicA0.equals(cyclicA1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CyclicA cyclicA0 = new CyclicA((CyclicB) null);
      CyclicC cyclicC0 = new CyclicC(cyclicA0);
      CyclicB cyclicB0 = new CyclicB(cyclicC0);
      cyclicA0.setCyclicB(cyclicB0);
      CyclicA cyclicA1 = new CyclicA((CyclicB) null);
      boolean boolean0 = cyclicA0.equals(cyclicA1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CyclicA cyclicA0 = new CyclicA((CyclicB) null);
      CyclicC cyclicC0 = new CyclicC(cyclicA0);
      boolean boolean0 = cyclicA0.equals(cyclicC0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CyclicA cyclicA0 = new CyclicA((CyclicB) null);
      int int0 = cyclicA0.hashCode();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CyclicC cyclicC0 = new CyclicC((CyclicA) null);
      CyclicB cyclicB0 = new CyclicB(cyclicC0);
      CyclicA cyclicA0 = new CyclicA(cyclicB0);
      int int0 = cyclicA0.hashCode();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CyclicA cyclicA0 = new CyclicA((CyclicB) null);
      CyclicA cyclicA1 = new CyclicA((CyclicB) null);
      boolean boolean0 = cyclicA1.equals(cyclicA0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CyclicA cyclicA0 = new CyclicA((CyclicB) null);
      String string0 = cyclicA0.toString();
  }
}
