/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 07 22:17:46 GMT 2026
 */

package com.creativityfactory.swiftserver.response;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.creativityfactory.swiftserver.response.HttpResponse;
import com.creativityfactory.swiftserver.response.Response;
import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletContext;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.PrintWriter;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HttpResponse_ESTest extends HttpResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      PrintWriter printWriter0 = mock(PrintWriter.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn(printWriter0).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      httpResponse0.json("");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      PrintWriter printWriter0 = mock(PrintWriter.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(printWriter0).toString();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn(printWriter0, printWriter0).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      PrintWriter printWriter1 = httpResponse0.out();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((ServletContext) null).when(httpServletRequest0).getServletContext();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      try { 
        httpResponse0.jsp("/6.DKloLg1p");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.creativityfactory.swiftserver.response.HttpResponse", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse((HttpServletRequest) null, httpServletResponse0);
      // Undeclared exception!
      httpResponse0.json(httpResponse0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HttpResponse httpResponse0 = null;
      try {
        httpResponse0 = new HttpResponse((HttpServletRequest) null, (HttpServletResponse) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse1 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse1).getWriter();
      HttpResponse httpResponse0 = new HttpResponse((HttpServletRequest) null, httpServletResponse1);
      // Undeclared exception!
      try { 
        httpResponse0.json(httpServletResponse0);
      } catch(UnsupportedOperationException e) {
         //
         // Attempted to serialize java.lang.Class: jakarta.servlet.http.HttpServletResponse. Forgot to register a type adapter?
         //
         verifyException("com.google.gson.internal.bind.TypeAdapters$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      Response response0 = httpResponse0.status(0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      PrintWriter printWriter0 = mock(PrintWriter.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn(printWriter0).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      Response response0 = httpResponse0.write("H3\"|rM*p~[l");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      Response response0 = httpResponse0.setHeader("TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.", "TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(httpServletRequest0).getPathInfo();
      PrintWriter printWriter0 = mock(PrintWriter.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn(printWriter0).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      httpResponse0.sendError(3, "");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("'3Fj{0S=8/WEB-INF/views/'3Fj{0S=8.jsp");
      boolean boolean0 = FileSystemHandling.createFolder(evoSuiteFile0);
      ServletContext servletContext0 = mock(ServletContext.class, new ViolatedAssumptionAnswer());
      doReturn("'3Fj{0S=8").when(servletContext0).getRealPath(anyString());
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn(servletContext0).when(httpServletRequest0).getServletContext();
      PrintWriter printWriter0 = mock(PrintWriter.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn(printWriter0).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      try { 
        httpResponse0.jsp("'3Fj{0S=8");
      } catch(NoSuchElementException e) {
         //
         // The jsp \"/WEB-INF/views/'3Fj{0S=8.jsp\"page does not exist :
         //
         verifyException("com.creativityfactory.swiftserver.response.HttpResponse", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("'3Fj{0S=8/WEB-INF/views/'3Fj{0S=8.jsp");
      boolean boolean0 = FileSystemHandling.appendLineToFile(evoSuiteFile0, "e<!ELOV`B6<@YR");
      ServletContext servletContext0 = mock(ServletContext.class, new ViolatedAssumptionAnswer());
      doReturn("'3Fj{0S=8").when(servletContext0).getRealPath(anyString());
      RequestDispatcher requestDispatcher0 = mock(RequestDispatcher.class, new ViolatedAssumptionAnswer());
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn(requestDispatcher0).when(httpServletRequest0).getRequestDispatcher(anyString());
      doReturn(servletContext0).when(httpServletRequest0).getServletContext();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      httpResponse0.jsp("'3Fj{0S=8");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ServletContext servletContext0 = mock(ServletContext.class, new ViolatedAssumptionAnswer());
      doReturn("'3Fj{0S=8").when(servletContext0).getRealPath(anyString());
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn(servletContext0).when(httpServletRequest0).getServletContext();
      PrintWriter printWriter0 = mock(PrintWriter.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn(printWriter0).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      try { 
        httpResponse0.jsp("'3Fj{0S=8");
      } catch(NoSuchElementException e) {
         //
         // The jsp \"/WEB-INF/views/'3Fj{0S=8.jsp\"page does not exist :
         //
         verifyException("com.creativityfactory.swiftserver.response.HttpResponse", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      Response response0 = httpResponse0.cacheControl(0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn("", (String) null).when(httpServletRequest0).getPathInfo();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      // Undeclared exception!
      try { 
        httpResponse0.sendError(1, "com.creativityfactory.swiftserver.response.HttpResponse");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse((HttpServletRequest) null, httpServletResponse0);
      HttpServletRequest httpServletRequest0 = httpResponse0.getRequest();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      Response response0 = httpResponse0.lastModified(1L);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse((HttpServletRequest) null, httpServletResponse0);
      // Undeclared exception!
      try { 
        httpResponse0.json((Object) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null, (PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse((HttpServletRequest) null, httpServletResponse0);
      PrintWriter printWriter0 = httpResponse0.out();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      Response response0 = httpResponse0.setDateHeader((String) null, (-1045L));
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      httpResponse0.redirect("'3Fj{0S=8");
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((PrintWriter) null).when(httpServletResponse0).getWriter();
      HttpResponse httpResponse0 = new HttpResponse(httpServletRequest0, httpServletResponse0);
      // Undeclared exception!
      try { 
        httpResponse0.write("");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
