/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 10 20:14:32 GMT 2026
 */

package org.javamoney.jakarta.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import javax.money.MonetaryAmount;
import javax.money.MonetaryAmountFactory;
import javax.validation.ConstraintValidatorContext;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.javamoney.jakarta.validator.MonetaryAmountMinValidator;
import org.javamoney.jakarta.validator.MonetaryMin;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MonetaryAmountMinValidator_ESTest extends MonetaryAmountMinValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MonetaryAmountMinValidator monetaryAmountMinValidator0 = new MonetaryAmountMinValidator();
      MonetaryMin monetaryMin0 = mock(MonetaryMin.class, new ViolatedAssumptionAnswer());
      doReturn("").when(monetaryMin0).value();
      // Undeclared exception!
      try { 
        monetaryAmountMinValidator0.initialize(monetaryMin0);
      } catch(NumberFormatException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.math.BigDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MonetaryAmountMinValidator monetaryAmountMinValidator0 = new MonetaryAmountMinValidator();
      MonetaryMin monetaryMin0 = mock(MonetaryMin.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(monetaryMin0).value();
      // Undeclared exception!
      try { 
        monetaryAmountMinValidator0.initialize(monetaryMin0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MonetaryAmountMinValidator monetaryAmountMinValidator0 = new MonetaryAmountMinValidator();
      boolean boolean0 = monetaryAmountMinValidator0.isValid((MonetaryAmount) null, (ConstraintValidatorContext) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MonetaryAmountMinValidator monetaryAmountMinValidator0 = new MonetaryAmountMinValidator();
      MonetaryAmount monetaryAmount0 = mock(MonetaryAmount.class, new ViolatedAssumptionAnswer());
      doReturn((MonetaryAmountFactory) null).when(monetaryAmount0).getFactory();
      ConstraintValidatorContext constraintValidatorContext0 = mock(ConstraintValidatorContext.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        monetaryAmountMinValidator0.isValid(monetaryAmount0, constraintValidatorContext0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MonetaryAmountMinValidator monetaryAmountMinValidator0 = new MonetaryAmountMinValidator();
      MonetaryMin monetaryMin0 = mock(MonetaryMin.class, new ViolatedAssumptionAnswer());
      doReturn("1").when(monetaryMin0).value();
      monetaryAmountMinValidator0.initialize(monetaryMin0);
  }
}
