/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Aug 10 19:33:14 GMT 2026
 */

package es.joseluisgs.springdam.services.users;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class UsuarioService_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "es.joseluisgs.springdam.services.users.UsuarioService"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(UsuarioService_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.dao.DataAccessException",
      "es.joseluisgs.springdam.repositories.usuarios.UsuariosRepository",
      "org.springframework.http.HttpStatus$Series",
      "org.springframework.data.repository.query.FluentQuery",
      "es.joseluisgs.springdam.errors.usuarios.NewUserWithDifferentPasswordsException",
      "org.springframework.security.core.authority.SimpleGrantedAuthority",
      "org.springframework.data.repository.query.FluentQuery$FetchableFluentQuery",
      "org.springframework.data.repository.CrudRepository",
      "org.springframework.data.repository.query.FluentQuery$ReactiveFluentQuery",
      "org.springframework.dao.DataIntegrityViolationException",
      "org.springframework.data.annotation.CreatedDate",
      "org.springframework.stereotype.Service",
      "org.springframework.data.repository.Repository",
      "org.springframework.security.core.userdetails.UserDetails",
      "org.springframework.data.jpa.domain.support.AuditingEntityListener",
      "org.springframework.data.domain.Sort",
      "org.springframework.data.domain.Pageable",
      "org.springframework.beans.factory.aspectj.ConfigurableObject",
      "org.springframework.dao.NonTransientDataAccessException",
      "org.springframework.core.NestedRuntimeException",
      "org.springframework.web.server.ResponseStatusException",
      "org.springframework.data.repository.PagingAndSortingRepository",
      "es.joseluisgs.springdam.models.Usuario",
      "es.joseluisgs.springdam.services.users.UsuarioService",
      "org.springframework.data.domain.Example",
      "org.springframework.data.domain.Page",
      "es.joseluisgs.springdam.models.Usuario$UsuarioBuilder",
      "org.springframework.data.domain.Slice",
      "org.springframework.security.core.GrantedAuthority",
      "es.joseluisgs.springdam.models.UsuarioRol",
      "org.springframework.data.repository.query.QueryByExampleExecutor",
      "org.springframework.http.HttpStatus",
      "es.joseluisgs.springdam.dto.usuarios.CreateUsuarioDTO$CreateUsuarioDTOBuilder",
      "org.springframework.stereotype.Component",
      "es.joseluisgs.springdam.dto.usuarios.CreateUsuarioDTO",
      "org.springframework.security.crypto.password.PasswordEncoder",
      "org.springframework.data.util.Streamable",
      "org.springframework.data.jpa.repository.JpaRepository"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("es.joseluisgs.springdam.repositories.usuarios.UsuariosRepository", false, UsuarioService_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.springframework.security.crypto.password.PasswordEncoder", false, UsuarioService_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(UsuarioService_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "es.joseluisgs.springdam.services.users.UsuarioService",
      "es.joseluisgs.springdam.models.UsuarioRol",
      "org.springframework.http.HttpStatus$Series",
      "org.springframework.http.HttpStatus",
      "es.joseluisgs.springdam.dto.usuarios.CreateUsuarioDTO",
      "es.joseluisgs.springdam.errors.usuarios.NewUserWithDifferentPasswordsException",
      "es.joseluisgs.springdam.models.Usuario",
      "es.joseluisgs.springdam.models.Usuario$UsuarioBuilder",
      "es.joseluisgs.springdam.dto.usuarios.CreateUsuarioDTO$CreateUsuarioDTOBuilder"
    );
  }
}
