/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 12:33:28 GMT 2026
 */

package com.pgssoft.httpclient.internal;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pgssoft.httpclient.internal.HttpMethods;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HttpMethods_ESTest extends HttpMethods_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpMethods httpMethods0 = new HttpMethods();
  }
}
