/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 16:06:45 GMT 2026
 */

package com.iwamih31;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iwamih31.Cash;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Cash_ESTest extends Cash_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer((-679));
      Period period0 = Period.ofWeeks(0);
      IsoChronology isoChronology0 = period0.getChronology();
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
      Integer integer1 = new Integer(0);
      Cash cash0 = new Cash(integer0, localDate0, integer1, integer1, integer1, integer1, integer0, integer0, integer1, integer0, integer0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      cash0.setHyaku5(integer0);
      int int0 = cash0.hashCode();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-5));
      cash0.setSen1(integer0);
      int int0 = cash0.hashCode();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(11);
      cash0.setSen5(integer0);
      int int0 = cash0.hashCode();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      cash0.setMan1(integer0);
      int int0 = cash0.hashCode();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(43);
      cash0.setId(integer0);
      int int0 = cash0.hashCode();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      cash0.setSen5(integer0);
      Integer integer1 = cash0.getSen5();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofYearDay((-375), 9);
      Integer integer0 = new Integer(10);
      Cash cash0 = new Cash((Integer) null, localDate0, integer0, integer0, (Integer) null, (Integer) null, integer0, integer0, integer0, integer0, (Integer) null);
      Integer integer1 = cash0.getSen5();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-1553));
      cash0.setSen5(integer0);
      Integer integer1 = cash0.getSen5();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      cash0.setSen1(integer0);
      Integer integer1 = cash0.getSen1();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(11);
      LocalDate localDate0 = MockLocalDate.now();
      Cash cash0 = new Cash(integer0, localDate0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Integer integer1 = cash0.getSen1();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-1553));
      cash0.setSen1(integer0);
      Integer integer1 = cash0.getSen1();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = new Integer((-679));
      Period period0 = Period.ofWeeks(0);
      IsoChronology isoChronology0 = period0.getChronology();
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
      Integer integer1 = new Integer(0);
      Cash cash0 = new Cash(integer0, localDate0, integer1, integer1, integer0, integer1, integer1, integer1, integer0, integer1, integer1);
      Integer integer2 = cash0.getMan1();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      Integer integer1 = new Integer(1549);
      Cash cash0 = new Cash(integer0, localDate0, (Integer) null, integer0, integer0, integer0, integer0, integer0, integer0, (Integer) null, integer1);
      cash0.setMan1(integer1);
      Integer integer2 = cash0.getMan1();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-1130));
      cash0.setMan1(integer0);
      Integer integer1 = cash0.getMan1();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      cash0.setJyuu5(integer0);
      Integer integer1 = cash0.getJyuu5();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(2150);
      cash0.setJyuu5(integer0);
      Integer integer1 = cash0.getJyuu5();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-2124));
      cash0.setJyuu5(integer0);
      Integer integer1 = cash0.getJyuu5();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = new Integer(1);
      Cash cash0 = new Cash(integer0, (LocalDate) null, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Integer integer1 = cash0.getJyuu1();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = cash0.getJyuu1();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-463));
      cash0.setJyuu1(integer0);
      Integer integer1 = cash0.getJyuu1();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      cash0.setId(integer0);
      Integer integer1 = cash0.getId();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = Integer.valueOf(4498);
      cash0.setId(integer0);
      Integer integer1 = cash0.getId();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-463));
      cash0.setId(integer0);
      Integer integer1 = cash0.getId();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((byte)0);
      cash0.setHyaku5(integer0);
      Integer integer1 = cash0.getHyaku5();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Integer integer0 = new Integer(11);
      LocalDate localDate0 = MockLocalDate.now();
      Cash cash0 = new Cash(integer0, localDate0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Integer integer1 = cash0.getHyaku5();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofYearDay((-375), 9);
      Integer integer0 = new Integer(10);
      Integer integer1 = new Integer((-1308));
      Cash cash0 = new Cash((Integer) null, localDate0, integer0, integer0, (Integer) null, (Integer) null, integer0, integer0, integer0, integer1, (Integer) null);
      cash0.setHyaku5(integer1);
      Integer integer2 = cash0.getHyaku5();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      Cash cash0 = new Cash(integer0, localDate0, (Integer) null, integer0, integer0, integer0, integer0, integer0, integer0, (Integer) null, integer0);
      Integer integer1 = cash0.getHyaku1();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofYearDay((-375), 9);
      Integer integer0 = new Integer(10);
      Cash cash0 = new Cash((Integer) null, localDate0, integer0, integer0, (Integer) null, (Integer) null, integer0, integer0, integer0, integer0, (Integer) null);
      Integer integer1 = cash0.getHyaku1();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-463));
      cash0.setHyaku1(integer0);
      Integer integer1 = cash0.getHyaku1();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      cash0.setEn5(integer0);
      Integer integer1 = cash0.getEn5();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(3);
      cash0.setEn5(integer0);
      Integer integer1 = cash0.getEn5();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofYearDay((-375), 9);
      Integer integer0 = new Integer(10);
      Integer integer1 = new Integer((-1308));
      Cash cash0 = new Cash((Integer) null, localDate0, integer0, integer0, (Integer) null, (Integer) null, integer0, integer1, integer1, integer1, (Integer) null);
      Integer integer2 = cash0.getEn5();
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Integer integer0 = new Integer(0);
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      Cash cash0 = new Cash(integer0, localDate0, integer0, integer0, integer0, integer0, (Integer) null, integer0, (Integer) null, integer0, integer0);
      Integer integer1 = cash0.getEn1();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(43);
      cash0.setEn1(integer0);
      Integer integer1 = cash0.getEn1();
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-1));
      cash0.setEn1(integer0);
      Integer integer1 = cash0.getEn1();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Cash cash0 = new Cash();
      LocalDate localDate0 = cash0.getDate();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Cash cash0 = new Cash();
      boolean boolean0 = cash0.canEqual(cash0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      boolean boolean0 = cash0.canEqual(integer0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = cash0.getSen5();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = cash0.getHyaku1();
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = cash0.getId();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = cash0.getEn5();
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = cash0.getJyuu5();
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = cash0.getHyaku5();
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      Cash cash0 = new Cash(integer0, localDate0, (Integer) null, integer0, integer0, integer0, integer0, integer0, integer0, (Integer) null, integer0);
      LocalDate localDate1 = cash0.getDate();
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = cash0.getEn1();
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      Cash cash0 = new Cash(integer0, localDate0, (Integer) null, integer0, integer0, integer0, integer0, integer0, integer0, (Integer) null, integer0);
      Integer integer1 = cash0.getMan1();
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1L);
      Cash cash0 = new Cash(integer0, localDate0, (Integer) null, integer0, integer0, integer0, integer0, integer0, integer0, (Integer) null, integer0);
      Integer integer1 = cash0.getJyuu1();
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = cash0.getSen1();
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Cash cash0 = new Cash();
      Cash cash1 = new Cash();
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(1);
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      cash1.setDate(localDate0);
      cash0.setDate(localDate0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Cash cash0 = new Cash();
      Cash cash1 = new Cash();
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(1);
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      cash1.setDate(localDate0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Cash cash0 = new Cash();
      Cash cash1 = new Cash();
      Integer integer0 = new Integer((-2235));
      cash1.setEn1(integer0);
      boolean boolean0 = cash0.equals(cash1);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-1329));
      Cash cash1 = new Cash();
      cash1.setEn1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-823));
      cash0.setEn5(integer0);
      Cash cash1 = new Cash();
      cash1.setEn5(integer0);
      boolean boolean0 = cash0.equals(cash1);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-2075));
      cash0.setEn5(integer0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Cash cash0 = new Cash();
      Cash cash1 = new Cash();
      Integer integer0 = new Integer(1);
      cash1.setEn5(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-2159));
      cash0.setJyuu1(integer0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-2256));
      Cash cash1 = new Cash();
      cash1.setJyuu1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-2169));
      cash0.setJyuu5(integer0);
      Cash cash1 = new Cash();
      cash1.setJyuu5(integer0);
      boolean boolean0 = cash0.equals(cash1);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-80));
      cash0.setSen5(integer0);
      Cash cash1 = new Cash();
      cash1.setJyuu5(integer0);
      cash1.setSen5(integer0);
      boolean boolean0 = cash0.equals(cash1);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Integer integer0 = new Integer(10);
      Cash cash0 = new Cash();
      cash0.setHyaku1(integer0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(1);
      Cash cash1 = new Cash();
      cash1.setHyaku1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(1);
      cash0.setHyaku5(integer0);
      Cash cash1 = new Cash();
      cash1.setHyaku5(integer0);
      boolean boolean0 = cash0.equals(cash1);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(43);
      cash0.setHyaku5(integer0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      Cash cash1 = new Cash();
      cash1.setSen1(integer0);
      boolean boolean0 = cash0.equals(cash1);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(2174);
      Cash cash1 = new Cash();
      cash1.setSen1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-2776));
      cash0.setSen5(integer0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Cash cash0 = new Cash();
      Cash cash1 = new Cash();
      Integer integer0 = new Integer((-2874));
      cash0.setMan1(integer0);
      cash1.setMan1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      cash0.setMan1(integer0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Cash cash0 = new Cash();
      Cash cash1 = new Cash();
      Integer integer0 = new Integer((-2874));
      cash1.setMan1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      Cash cash0 = new Cash();
      Cash cash1 = new Cash();
      Integer integer0 = new Integer(509);
      cash1.setId(integer0);
      boolean boolean0 = cash0.equals(cash1);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = Integer.valueOf(721);
      Cash cash1 = new Cash();
      cash1.setId(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Cash cash0 = new Cash();
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(1);
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      boolean boolean0 = cash0.equals(localDate0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      Cash cash0 = new Cash();
      boolean boolean0 = cash0.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      Integer integer0 = new Integer(11);
      LocalDate localDate0 = MockLocalDate.now();
      Cash cash0 = new Cash(integer0, localDate0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      int int0 = cash0.hashCode();
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-2256));
      cash0.setJyuu1(integer0);
      Cash cash1 = new Cash();
      cash1.setJyuu1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(0);
      cash0.setSen5(integer0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash0.equals(cash1);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      Cash cash0 = new Cash();
      String string0 = cash0.toString();
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = Integer.valueOf(721);
      cash0.setId(integer0);
      Cash cash1 = new Cash();
      cash1.setId(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-1329));
      cash0.setEn1(integer0);
      Cash cash1 = new Cash();
      cash1.setEn1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer((-2169));
      cash0.setJyuu5(integer0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash0.equals(cash1);
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(2174);
      cash0.setSen1(integer0);
      Cash cash1 = new Cash();
      cash1.setSen1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      Cash cash0 = new Cash();
      LocalDate localDate0 = MockLocalDate.now();
      cash0.setDate(localDate0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(1);
      cash0.setHyaku1(integer0);
      Cash cash1 = new Cash();
      cash1.setHyaku1(integer0);
      boolean boolean0 = cash1.equals(cash0);
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      Cash cash0 = new Cash();
      Integer integer0 = new Integer(1);
      cash0.setHyaku5(integer0);
      Cash cash1 = new Cash();
      boolean boolean0 = cash0.equals(cash1);
  }
}
