/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 06:15:52 GMT 2026
 */

package com.coreoz.windmill.imports.parsers.csv;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.coreoz.windmill.imports.Cell;
import com.coreoz.windmill.imports.parsers.csv.CsvCellIterator;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CsvCellIterator_ESTest extends CsvCellIterator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[3];
      CsvCellIterator csvCellIterator0 = new CsvCellIterator(stringArray0);
      boolean boolean0 = csvCellIterator0.hasNext();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[0];
      CsvCellIterator csvCellIterator0 = new CsvCellIterator(stringArray0);
      boolean boolean0 = csvCellIterator0.hasNext();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CsvCellIterator csvCellIterator0 = new CsvCellIterator((String[]) null);
      // Undeclared exception!
      try { 
        csvCellIterator0.next();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CsvCellIterator csvCellIterator0 = new CsvCellIterator((String[]) null);
      // Undeclared exception!
      try { 
        csvCellIterator0.hasNext();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[7];
      CsvCellIterator csvCellIterator0 = new CsvCellIterator(stringArray0);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      csvCellIterator0.forEachRemaining(consumer0);
      // Undeclared exception!
      try { 
        csvCellIterator0.next();
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[7];
      CsvCellIterator csvCellIterator0 = new CsvCellIterator(stringArray0);
      Cell cell0 = csvCellIterator0.next();
      Cell cell1 = csvCellIterator0.next();
  }
}
