/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 07:04:45 GMT 2026
 */

package com.rtbhouse.kafka.workers.api.partitioner;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.rtbhouse.kafka.workers.api.partitioner.WorkerSubpartition;
import org.apache.kafka.common.TopicPartition;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WorkerSubpartition_ESTest extends WorkerSubpartition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance(",*(on!'}", 1386, 0);
      int int0 = workerSubpartition0.hashCode();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((TopicPartition) null, 109);
      TopicPartition topicPartition0 = workerSubpartition0.topicPartition();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((String) null, (-1477), 0);
      TopicPartition topicPartition0 = workerSubpartition0.topicPartition();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((String) null, 4666, 1667);
      String string0 = workerSubpartition0.topic();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("", (-2759), 0);
      WorkerSubpartition workerSubpartition1 = WorkerSubpartition.getInstance("-", (-2759), (-1257));
      String string0 = workerSubpartition1.topic();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("", 1304, 1304);
      String string0 = workerSubpartition0.topic();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TopicPartition topicPartition0 = new TopicPartition("0m9D]`pJ[Va&E$_[4", 1386);
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance(topicPartition0, 1386);
      int int0 = workerSubpartition0.subpartition();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TopicPartition topicPartition0 = new TopicPartition("", (-1454));
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance(topicPartition0, (-2371));
      int int0 = workerSubpartition0.subpartition();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TopicPartition topicPartition0 = new TopicPartition("[M55{`%[];i2_xpow", 0);
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance(topicPartition0, 0);
      int int0 = workerSubpartition0.partition();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance(",*(on!'}", 1386, 0);
      int int0 = workerSubpartition0.partition();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TopicPartition topicPartition0 = new TopicPartition("", (-1454));
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance(topicPartition0, 1585);
      int int0 = workerSubpartition0.partition();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("G]x|g*G^", (-218), (-218));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("", 0, 1585);
      TopicPartition topicPartition0 = new TopicPartition("", (-1454));
      WorkerSubpartition workerSubpartition1 = WorkerSubpartition.getInstance(topicPartition0, 1585);
      boolean boolean0 = workerSubpartition0.equals(workerSubpartition1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((TopicPartition) null, 15);
      WorkerSubpartition workerSubpartition1 = WorkerSubpartition.getInstance((TopicPartition) null, 15);
      boolean boolean0 = workerSubpartition1.equals(workerSubpartition0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((String) null, 0, 0);
      TopicPartition topicPartition0 = workerSubpartition0.topicPartition();
      WorkerSubpartition workerSubpartition1 = WorkerSubpartition.getInstance(topicPartition0, 0);
      boolean boolean0 = workerSubpartition1.equals(workerSubpartition0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("", (-2759), 0);
      WorkerSubpartition workerSubpartition1 = WorkerSubpartition.getInstance("-", (-1257), (-2759));
      boolean boolean0 = workerSubpartition0.equals(workerSubpartition1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("YjaFsn|_,'N2=KI6_", 1450, 1450);
      WorkerSubpartition workerSubpartition1 = WorkerSubpartition.getInstance((TopicPartition) null, 1450);
      boolean boolean0 = workerSubpartition1.equals(workerSubpartition0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TopicPartition topicPartition0 = new TopicPartition("[M55{`%[];i2_xpow", 0);
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance(topicPartition0, 0);
      int int0 = workerSubpartition0.subpartition();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((TopicPartition) null, 31);
      // Undeclared exception!
      try { 
        workerSubpartition0.topic();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((TopicPartition) null, 3368);
      // Undeclared exception!
      try { 
        workerSubpartition0.partition();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("com.rtbhouse.kafka.workers.api.partitioner.WorkerSubpaetition", 1667, 31);
      Object object0 = new Object();
      boolean boolean0 = workerSubpartition0.equals(object0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((String) null, 1450, 1450);
      boolean boolean0 = workerSubpartition0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((String) null, (-30), (-30));
      boolean boolean0 = workerSubpartition0.equals(workerSubpartition0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((TopicPartition) null, 15);
      int int0 = workerSubpartition0.hashCode();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("com.rtbhouse.kafka.workers.api.partitioner.WorkerSubpartition", 1118, 1118);
      TopicPartition topicPartition0 = workerSubpartition0.topicPartition();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("|&`P0g\"9U]'^feB}j", (-561), (-561));
      String string0 = workerSubpartition0.toString();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance("com.rtbhouse.kafka.workers.api.partitioner.WorkerSubpaetition", 1667, 31);
      int int0 = workerSubpartition0.hashCode();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      WorkerSubpartition workerSubpartition0 = WorkerSubpartition.getInstance((TopicPartition) null, (-470));
      // Undeclared exception!
      try { 
        workerSubpartition0.toString();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
