/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 12 09:05:04 GMT 2026
 */

package loliSnatcher;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import loliSnatcher.GelbooruHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BooruHandler_ESTest extends BooruHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GelbooruHandler gelbooruHandler0 = new GelbooruHandler((-1467), "");
      ArrayList arrayList0 = gelbooruHandler0.Search("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GelbooruHandler gelbooruHandler0 = new GelbooruHandler((-1), (String) null);
      // Undeclared exception!
      try { 
        gelbooruHandler0.Search((String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("loliSnatcher.GelbooruHandler", e);
      }
  }
}
