/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 05:37:12 GMT 2026
 */

package io.basquiat.interfacebbuljit.noodle.provider;

import org.junit.Test;
import static org.junit.Assert.*;
import io.basquiat.interfacebbuljit.noodle.provider.ApplicationContextProvider;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.context.ApplicationContext;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ApplicationContextProvider_ESTest extends ApplicationContextProvider_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ApplicationContext applicationContext0 = ApplicationContextProvider.getApplicationContext();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ApplicationContextProvider applicationContextProvider0 = new ApplicationContextProvider();
      applicationContextProvider0.setApplicationContext((ApplicationContext) null);
  }
}
