/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 12 10:17:26 GMT 2026
 */

package com.zxl.dailypractice.algorithm.Day12;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zxl.dailypractice.algorithm.Day12.Solution;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution_ESTest extends Solution_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution solution0 = new Solution();
      int[] intArray0 = new int[6];
      intArray0[0] = 61;
      int int0 = solution0.rob(intArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution solution0 = new Solution();
      int[] intArray0 = new int[6];
      intArray0[0] = (-367);
      intArray0[1] = (-2113);
      int int0 = solution0.rob(intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution solution0 = new Solution();
      int int0 = solution0.climbStairs(0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution solution0 = new Solution();
      // Undeclared exception!
      solution0.climbStairs(1306058617);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution solution0 = new Solution();
      int[] intArray0 = new int[6];
      int int0 = solution0.rob(intArray0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution solution0 = new Solution();
      int int0 = solution0.climbStairs(61);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int[] intArray0 = new int[1];
      Solution solution0 = new Solution();
      int int0 = solution0.rob(intArray0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int[] intArray0 = new int[0];
      Solution solution0 = new Solution();
      int int0 = solution0.rob(intArray0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Solution solution0 = new Solution();
      int int0 = solution0.rob((int[]) null);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Solution.main((String[]) null);
  }
}
