/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 31 02:27:38 GMT 2026
 */

package org.example.toylanguage.statement;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.EmptyStackException;
import java.util.LinkedList;
import java.util.function.Supplier;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.toylanguage.expression.ArrayExpression;
import org.example.toylanguage.expression.ClassExpression;
import org.example.toylanguage.expression.Expression;
import org.example.toylanguage.expression.VariableExpression;
import org.example.toylanguage.expression.value.Value;
import org.example.toylanguage.statement.ClassStatement;
import org.example.toylanguage.statement.CompositeStatement;
import org.example.toylanguage.statement.ConditionStatement;
import org.example.toylanguage.statement.ExpressionStatement;
import org.example.toylanguage.statement.FunctionStatement;
import org.example.toylanguage.statement.HandleExceptionStatement;
import org.example.toylanguage.statement.InputStatement;
import org.example.toylanguage.statement.ReturnStatement;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Statement_ESTest extends Statement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = Integer.getInteger("b)+s`D'");
      Object object0 = new Object();
      Value<Object> value0 = new Value<Object>(object0);
      ExpressionStatement expressionStatement0 = new ExpressionStatement(integer0, "", value0);
      expressionStatement0.execute();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer integer0 = new Integer(0);
      ConditionStatement conditionStatement0 = new ConditionStatement(integer0, ",4!`");
      Integer integer1 = conditionStatement0.getRowNumber();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer integer0 = new Integer(2038);
      CompositeStatement compositeStatement0 = new CompositeStatement(integer0, "A`3$cD:]");
      Integer integer1 = compositeStatement0.getRowNumber();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Object object0 = new Object();
      Value<Object> value0 = new Value<Object>(object0);
      Integer integer0 = new Integer((-1));
      ExpressionStatement expressionStatement0 = new ExpressionStatement(integer0, "", value0);
      Integer integer1 = expressionStatement0.getRowNumber();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Integer integer0 = new Integer(0);
      ConditionStatement conditionStatement0 = new ConditionStatement(integer0, ";#_a");
      String string0 = conditionStatement0.getBlockName();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Integer integer0 = new Integer(0);
      ClassStatement classStatement0 = new ClassStatement(integer0, "");
      String string0 = classStatement0.getBlockName();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Integer integer0 = new Integer(0);
      VariableExpression variableExpression0 = new VariableExpression(";#_a");
      ReturnStatement returnStatement0 = new ReturnStatement(integer0, ";#_a", variableExpression0);
      // Undeclared exception!
      try { 
        returnStatement0.execute();
      } catch(EmptyStackException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ClassStatement classStatement0 = new ClassStatement((Integer) null, " Y]FK");
      HandleExceptionStatement handleExceptionStatement0 = new HandleExceptionStatement((Integer) null, " Y]FK", classStatement0, classStatement0, classStatement0, " Y]FK");
      Integer integer0 = Integer.valueOf((-3128));
      LinkedList<Expression> linkedList0 = new LinkedList<Expression>();
      ClassExpression classExpression0 = new ClassExpression("", linkedList0);
      ExpressionStatement expressionStatement0 = new ExpressionStatement(integer0, " Y]FK", classExpression0);
      classStatement0.addStatement(expressionStatement0);
      // Undeclared exception!
      try { 
        handleExceptionStatement0.execute();
      } catch(EmptyStackException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = new Integer(0);
      LinkedList<Expression> linkedList0 = new LinkedList<Expression>();
      ArrayExpression arrayExpression0 = new ArrayExpression(linkedList0);
      linkedList0.push(arrayExpression0);
      ExpressionStatement expressionStatement0 = new ExpressionStatement(integer0, "org.example.toylanguage.expression.value.ComparableValue", arrayExpression0);
      // Undeclared exception!
      try { 
        expressionStatement0.execute();
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      InputStatement inputStatement0 = new InputStatement((Integer) null, "null", "null", (Supplier<String>) null);
      // Undeclared exception!
      try { 
        inputStatement0.execute();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.toylanguage.statement.InputStatement", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Integer integer0 = new Integer(0);
      HandleExceptionStatement handleExceptionStatement0 = new HandleExceptionStatement(integer0, "v", (CompositeStatement) null, (CompositeStatement) null, (CompositeStatement) null, "v");
      // Undeclared exception!
      try { 
        handleExceptionStatement0.execute();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = Integer.getInteger("b)+s`D'");
      Object object0 = new Object();
      Value<Object> value0 = new Value<Object>(object0);
      ExpressionStatement expressionStatement0 = new ExpressionStatement(integer0, "", value0);
      Integer integer1 = expressionStatement0.getRowNumber();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = new Integer(1759);
      FunctionStatement functionStatement0 = new FunctionStatement(integer0, (String) null);
      String string0 = functionStatement0.getBlockName();
  }
}
