/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 06:09:02 GMT 2026
 */

package tech.jiayezheng.miniJuliaSonar.type;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import tech.jiayezheng.miniJuliaSonar.State;
import tech.jiayezheng.miniJuliaSonar.type.FuncType;
import tech.jiayezheng.miniJuliaSonar.type.InstanceType;
import tech.jiayezheng.miniJuliaSonar.type.PrimType;
import tech.jiayezheng.miniJuliaSonar.type.StructType;
import tech.jiayezheng.miniJuliaSonar.type.Type;
import tech.jiayezheng.miniJuliaSonar.type.UnionType;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StructType_ESTest extends StructType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      State.StateType state_StateType0 = State.StateType.INSTANCE;
      State state0 = new State((State) null, state_StateType0);
      StructType structType0 = new StructType("\ro/[9<y((\"cB Q]", state0);
      boolean boolean0 = structType0.typeEquals(state_StateType0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      State.StateType state_StateType0 = State.StateType.INSTANCE;
      State state0 = new State((State) null, state_StateType0);
      StructType structType0 = new StructType("\ro/[9<y((\"cB Q]", state0);
      Type.CyclicTypeRecorder type_CyclicTypeRecorder0 = structType0.new CyclicTypeRecorder();
      String string0 = structType0.printType(type_CyclicTypeRecorder0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      State state0 = mock(State.class, new ViolatedAssumptionAnswer());
      State state1 = new State(state0, (State.StateType) null);
      StructType structType0 = new StructType("StructDef", state1);
      PrimType primType0 = new PrimType("WAUE`", state1, (Type) null);
      InstanceType instanceType0 = primType0.getInstance();
      structType0.addInstance(instanceType0);
      InstanceType instanceType1 = structType0.getInstance(instanceType0.params);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      UnionType unionType0 = new UnionType();
      StructType structType0 = null;
      try {
        structType0 = new StructType((String) null, unionType0.table, unionType0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UnionType unionType0 = new UnionType();
      StructType structType0 = null;
      try {
        structType0 = new StructType((String) null, unionType0.table);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StructType structType0 = new StructType("CC#L$<j$;XCN&>J@3+", (State) null);
      // Undeclared exception!
      try { 
        structType0.addBase((Type) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StructType structType0 = new StructType(">", (State) null);
      boolean boolean0 = structType0.typeEquals(structType0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StructType structType0 = new StructType("w10(-5O5U^uF;x|E&7P", (State) null);
      PrimType primType0 = new PrimType(">", structType0.table);
      InstanceType instanceType0 = primType0.getInstance();
      structType0.addInstance(instanceType0);
      Map<String, InstanceType> map0 = structType0.getInstances();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StructType structType0 = new StructType((String) null, (State) null);
      Map<String, InstanceType> map0 = structType0.getInstances();
      Map<String, InstanceType> map1 = structType0.getInstances();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      UnionType unionType0 = new UnionType();
      StructType structType0 = new StructType("j[(nx", unionType0.table, unionType0);
      structType0.addBase(unionType0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FuncType funcType0 = new FuncType();
      StructType structType0 = new StructType((String) null, (State) null, funcType0);
      Map<String, InstanceType> map0 = structType0.getInstances();
      // Undeclared exception!
      try { 
        structType0.addInstance((InstanceType) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      UnionType unionType0 = new UnionType();
      StructType structType0 = new StructType("", unionType0.table, (Type) null);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StructType structType0 = new StructType((String) null, (State) null);
      // Undeclared exception!
      try { 
        structType0.getInstance((List<Type>) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
