/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 05:20:10 GMT 2026
 */

package com.API.OnDriver.CustomerSubsystem;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.API.OnDriver.CustomerSubsystem.Driver;
import com.API.OnDriver.CustomerSubsystem.Passenger;
import com.API.OnDriver.RideSubsystem.Area;
import com.API.OnDriver.RideSubsystem.Offer;
import com.API.OnDriver.RideSubsystem.Ride;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Passenger_ESTest extends Passenger_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Area area0 = new Area("iO[");
      Passenger passenger0 = new Passenger("iO[", "a)1'", "iO[", "n5N`KH,Rt1b@xft?1u'", "a)1'");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      Driver driver0 = new Driver((String) null, "iO[", (String) null, "", "", "", 854);
      Offer offer0 = new Offer(0, driver0);
      ride0.addOffer(offer0);
      passenger0.requestRide(ride0);
      ride0.addOffer(offer0);
      boolean boolean0 = passenger0.acceptOffer(1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Passenger passenger0 = new Passenger("gVc_iW;K%Dg^i", "gVc_iW;K%Dg^i", "g?|1X7yP8@I*TO[%", "g?|1X7yP8@I*TO[%", "g?|1X7yP8@I*TO[%");
      Area area0 = new Area("");
      Ride ride0 = new Ride(area0, area0, passenger0, (-1));
      passenger0.requestRide(ride0);
      boolean boolean0 = passenger0.acceptOffer(1774);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Passenger passenger0 = new Passenger(" h1H!}[H_3Av", " h1H!}[H_3Av", "", "", "");
      boolean boolean0 = passenger0.rateRide((Ride) null, 5);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Passenger passenger0 = new Passenger(" h1H!}[H_3Av", " h1H!}[H_3Av", "", "", "");
      boolean boolean0 = passenger0.isFirstRide();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Area area0 = new Area("iO[");
      Passenger passenger0 = new Passenger("iO[", "a)1'", "iO[", "n5N`KH,Rt1b@xft?1u'", "a)1'");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      Driver driver0 = new Driver((String) null, "iO[", "a)1'", "", "", "", 854);
      Offer offer0 = new Offer(0, driver0);
      ride0.addOffer(offer0);
      passenger0.requestRide(ride0);
      boolean boolean0 = passenger0.acceptOffer(0);
      Ride ride1 = passenger0.getPastRide(0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Passenger passenger0 = new Passenger("a)1'", "n5N`KH,Rt1b@xft?1u'", "a)1'", (String) null, "n5N`KH,Rt1b@xft?1u'");
      Area area0 = new Area((String) null);
      Ride ride0 = new Ride(area0, area0, passenger0, 5);
      Driver driver0 = new Driver("7-ugY+", "No rides yet", "n5N`KH,Rt1b@xft?1u'", "", "{?f9kC YV<NFl7~}O", (String) null, 5);
      Offer offer0 = new Offer(0.0, driver0);
      ride0.addOffer(offer0);
      passenger0.requestRide(ride0);
      boolean boolean0 = passenger0.acceptOffer(0);
      Ride ride1 = passenger0.getPastRide(0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Passenger passenger0 = new Passenger((String) null, (String) null, "", "", (String) null);
      String string0 = passenger0.getDateOfBirth();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Passenger passenger0 = new Passenger("com.API.OnDriver.EventSubsystem.SourceEvent", "com.API.OnDriver.EventSubsystem.SourceEvent", "com.API.OnDriver.EventSubsystem.SourceEvent", "com.API.OnDriver.EventSubsystem.SourceEvent", "com.API.OnDriver.EventSubsystem.SourceEvent");
      String string0 = passenger0.getDateOfBirth();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Passenger passenger0 = new Passenger("There's no past rides", "There's no past rides", "There's no past rides", "There's no past rides", "");
      String string0 = passenger0.getDateOfBirth();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Passenger passenger0 = new Passenger(" h1H!}[H_3Av", " h1H!}[H_3Av", "", "", "");
      Area area0 = new Area("R=\"wgq/g|");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      passenger0.requestRide(ride0);
      ArrayList<String> arrayList0 = passenger0.checkOffers();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Passenger passenger0 = new Passenger(":YY:3c|rt*.", ":YY:3c|rt*.", ":YY:3c|rt*.", ":YY:3c|rt*.", ":YY:3c|rt*.");
      // Undeclared exception!
      try { 
        passenger0.requestRide((Ride) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.API.OnDriver.CustomerSubsystem.Passenger", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Passenger passenger0 = new Passenger("iO[", "a)1'", "iO[", "n5N`KH,Rt1b@xft?1u'", "a)1'");
      // Undeclared exception!
      try { 
        passenger0.acceptOffer(0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Area area0 = new Area("iTO[");
      Passenger passenger0 = new Passenger("iTO[", "iTO[", "iTO[", "iTO[", "iTO[");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      Driver driver0 = new Driver("iTO[", "iTO[", "iTO[", "iTO[", "iTO[", "iTO[", 0);
      Offer offer0 = new Offer(0, driver0);
      ride0.addOffer(offer0);
      passenger0.requestRide(ride0);
      boolean boolean0 = passenger0.acceptOffer(0);
      boolean boolean1 = passenger0.isFirstRide();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Area area0 = new Area("iO[");
      Passenger passenger0 = new Passenger("iO[", "a)1'", "iO[", "n5N`KH,Rt1b@xft?1u'", "a)1'");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      Driver driver0 = new Driver((String) null, "iO[", "4a;sEL)yUlm.", "", "", "", 854);
      Offer offer0 = new Offer(0, driver0);
      ride0.addOffer(offer0);
      passenger0.requestRide(ride0);
      boolean boolean0 = passenger0.acceptOffer(0);
      ArrayList<String> arrayList0 = passenger0.listPastRides();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Passenger passenger0 = new Passenger("iO[", "a)1'", "iO[", "n5N`KH,Rt1b@xft?1u'", "a)1'");
      ArrayList<String> arrayList0 = passenger0.listPastRides();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Passenger passenger0 = new Passenger(" h1H!}[H_3Av", " h1H!}[H_3Av", "", "", "");
      Area area0 = new Area("R=\"wgq/g|");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      passenger0.requestRide(ride0);
      boolean boolean0 = passenger0.acceptOffer((-1));
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Passenger passenger0 = new Passenger(" h1H!}[H_3Av", " h1H!}[H_3Av", "", "", "");
      Area area0 = new Area("R=\"wgq/g|");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      passenger0.requestRide(ride0);
      boolean boolean0 = passenger0.acceptOffer(0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Area area0 = new Area("iO[");
      Passenger passenger0 = new Passenger("iO[", "a)1'", "iO[", "n5N`KH,Rt1b@xft?1u'", "a)1'");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      Driver driver0 = new Driver((String) null, "iO[", (String) null, (String) null, (String) null, (String) null, 862);
      Offer offer0 = new Offer(0, driver0);
      ride0.addOffer(offer0);
      passenger0.requestRide(ride0);
      boolean boolean0 = passenger0.acceptOffer(0);
      Ride ride1 = new Ride(area0, area0, passenger0, 0);
      boolean boolean1 = passenger0.rateRide(ride1, 4);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Area area0 = new Area("iO[");
      Passenger passenger0 = new Passenger("iO[", "a)1'", "iO[", "n5N`KH,Rt1b@xft?1u'", "a)1'");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      boolean boolean0 = passenger0.rateRide(ride0, 10);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Passenger passenger0 = new Passenger(" h1H!}[H_3Av", " h1H!}[H_3Av", "", "", "");
      boolean boolean0 = passenger0.rateRide((Ride) null, 0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Area area0 = new Area("iO[");
      Passenger passenger0 = new Passenger("iO[", "a)1'", "iO[", "n5N`KH,Rt1b@xft?1u'", "a)1'");
      Ride ride0 = new Ride(area0, area0, passenger0, 0);
      Driver driver0 = new Driver((String) null, "iO[", "4a;sEL)yUlm.", "", "", "", 854);
      Offer offer0 = new Offer(0, driver0);
      ride0.addOffer(offer0);
      passenger0.requestRide(ride0);
      boolean boolean0 = passenger0.acceptOffer(0);
      boolean boolean1 = passenger0.rateRide(ride0, 4);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Passenger passenger0 = new Passenger(" h1H!}[H_3Av", " h1H!}[H_3Av", "", "", "");
      String string0 = passenger0.toString();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Passenger passenger0 = new Passenger("a)1'", "n5N`KH,Rt1b@xft?1u'", "a)1'", (String) null, "n5N`KH,Rt1b@xft?1u'");
      // Undeclared exception!
      try { 
        passenger0.getPastRide(0);
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Passenger passenger0 = new Passenger("a)1'", "n5N`KH,Rt1b@xft?1u'", "a)1'", (String) null, "n5N`KH,Rt1b@xft?1u'");
      // Undeclared exception!
      try { 
        passenger0.checkOffers();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
