/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 23:38:02 GMT 2026
 */

package io.graversen.minecraft.rcon.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.graversen.minecraft.rcon.commands.GameModeCommand;
import io.graversen.minecraft.rcon.util.GameModes;
import io.graversen.minecraft.rcon.util.Selectors;
import io.graversen.minecraft.rcon.util.Target;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GameModeCommand_ESTest extends GameModeCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Selectors selectors0 = Selectors.NEAREST_PLAYER;
      Target target0 = Target.selector(selectors0);
      GameModeCommand gameModeCommand0 = null;
      try {
        gameModeCommand0 = new GameModeCommand(target0, (GameModes) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Selectors selectors0 = Selectors.RANDOM_PLAYER;
      Target target0 = Target.selector(selectors0);
      GameModes gameModes0 = GameModes.ADVENTURE;
      GameModeCommand gameModeCommand0 = new GameModeCommand(target0, gameModes0);
      String string0 = gameModeCommand0.command();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = Target.player("T4mG^|yZ");
      GameModes gameModes0 = GameModes.SURVIVAL;
      GameModeCommand gameModeCommand0 = new GameModeCommand(target0, gameModes0);
      GameModes gameModes1 = gameModeCommand0.getGameMode();
  }
}
