/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 13:28:59 GMT 2026
 */

package com.jakubduchon.webapidemo.projects;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jakubduchon.webapidemo.employee.Employee;
import com.jakubduchon.webapidemo.projects.Project;
import java.util.LinkedHashSet;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Project_ESTest extends Project_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Project project0 = new Project();
      String string0 = project0.getName();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Project project0 = new Project("", "");
      String string0 = project0.getName();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Project project0 = new Project("fa", "fa");
      Long long0 = new Long(0L);
      project0.setId(long0);
      Long long1 = project0.getId();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Project project0 = new Project();
      Long long0 = new Long(1772L);
      project0.setId(long0);
      Long long1 = project0.getId();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Project project0 = new Project("", "");
      Long long0 = new Long((-1L));
      project0.setId(long0);
      Long long1 = project0.getId();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Project project0 = new Project();
      Employee employee0 = new Employee("oj4@Blc/uyyqYK7Z", "");
      LinkedHashSet<Employee> linkedHashSet0 = new LinkedHashSet<Employee>();
      boolean boolean0 = linkedHashSet0.add(employee0);
      project0.setEnrolledEmployees(linkedHashSet0);
      Set<Employee> set0 = project0.getEnrolledEmployees();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Project project0 = new Project();
      String string0 = project0.getDescription();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Project project0 = new Project("fa", "fa");
      project0.setDescription("");
      String string0 = project0.getDescription();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Project project0 = new Project();
      // Undeclared exception!
      try { 
        project0.enrollEmployee((Employee) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Project project0 = new Project("fa", "fa");
      Employee employee0 = new Employee("", "#0(Y92+i");
      project0.enrollEmployee(employee0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Project project0 = new Project("fa", "fa");
      String string0 = project0.getName();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Project project0 = new Project();
      Set<Employee> set0 = project0.getEnrolledEmployees();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Project project0 = new Project("fa", "fa");
      String string0 = project0.getDescription();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Project project0 = new Project("", "");
      Set<Employee> set0 = project0.getEnrolledEmployees();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Project project0 = new Project();
      Long long0 = project0.getId();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Project project0 = new Project();
      project0.setName("com.jakubduchon.webapidemo.employee.Employee");
  }
}
