/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 12:14:37 GMT 2026
 */

package in.cubestack.apps.blog.base.web;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import in.cubestack.apps.blog.base.web.HttpHelper;
import java.util.Map;
import javax.ws.rs.container.ContainerRequestContext;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HttpHelper_ESTest extends HttpHelper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpHelper httpHelper0 = new HttpHelper();
      ContainerRequestContext containerRequestContext0 = mock(ContainerRequestContext.class, new ViolatedAssumptionAnswer());
      ContainerRequestContext containerRequestContext1 = mock(ContainerRequestContext.class, new ViolatedAssumptionAnswer());
      doReturn((Map) null).when(containerRequestContext1).getCookies();
      // Undeclared exception!
      try { 
        httpHelper0.getTokenFromRequest(containerRequestContext1);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpHelper httpHelper0 = new HttpHelper();
      ContainerRequestContext containerRequestContext0 = mock(ContainerRequestContext.class, new ViolatedAssumptionAnswer());
      doReturn("H7M0oFi7u~s[").when(containerRequestContext0).getHeaderString(anyString());
      String string0 = httpHelper0.getTokenFromHeader(containerRequestContext0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpHelper httpHelper0 = new HttpHelper();
      ContainerRequestContext containerRequestContext0 = mock(ContainerRequestContext.class, new ViolatedAssumptionAnswer());
      doReturn("vdN{T").when(containerRequestContext0).getHeaderString(anyString());
      String string0 = httpHelper0.getTokenFromHeader(containerRequestContext0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HttpHelper httpHelper0 = new HttpHelper();
      ContainerRequestContext containerRequestContext0 = mock(ContainerRequestContext.class, new ViolatedAssumptionAnswer());
      doReturn((Map) null).when(containerRequestContext0).getCookies();
      // Undeclared exception!
      try { 
        httpHelper0.getTokenFromRequest(containerRequestContext0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HttpHelper httpHelper0 = new HttpHelper();
      // Undeclared exception!
      try { 
        httpHelper0.getTokenFromHeader((ContainerRequestContext) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HttpHelper httpHelper0 = new HttpHelper();
      ContainerRequestContext containerRequestContext0 = mock(ContainerRequestContext.class, new ViolatedAssumptionAnswer());
      doReturn("").when(containerRequestContext0).getHeaderString(anyString());
      // Undeclared exception!
      try { 
        httpHelper0.getTokenFromHeader(containerRequestContext0);
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      HttpHelper httpHelper0 = new HttpHelper();
      ContainerRequestContext containerRequestContext0 = mock(ContainerRequestContext.class, new ViolatedAssumptionAnswer());
      doReturn((Map) null).when(containerRequestContext0).getCookies();
      // Undeclared exception!
      try { 
        httpHelper0.getTokenFromCookie(containerRequestContext0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      HttpHelper httpHelper0 = new HttpHelper();
      ContainerRequestContext containerRequestContext0 = mock(ContainerRequestContext.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(containerRequestContext0).getHeaderString(anyString());
      String string0 = httpHelper0.getTokenFromHeader(containerRequestContext0);
  }
}
