/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 19:10:35 GMT 2026
 */

package ru.smartup.timetracker.pojo.notice;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ru.smartup.timetracker.pojo.notice.NoticePersonalToken;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NoticePersonalToken_ESTest extends NoticePersonalToken_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NoticePersonalToken noticePersonalToken0 = new NoticePersonalToken("", "", 1L);
      long long0 = noticePersonalToken0.getTtlInHours();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NoticePersonalToken noticePersonalToken0 = new NoticePersonalToken("", "", (-1L));
      long long0 = noticePersonalToken0.getTtlInHours();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NoticePersonalToken noticePersonalToken0 = new NoticePersonalToken("|~kx%rLd", "|~kx%rLd", 0L);
      String string0 = noticePersonalToken0.getToken();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NoticePersonalToken noticePersonalToken0 = new NoticePersonalToken("", "", 0L);
      String string0 = noticePersonalToken0.getToken();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NoticePersonalToken noticePersonalToken0 = new NoticePersonalToken("|~kx%rLd", "|~kx%rLd", 0L);
      String string0 = noticePersonalToken0.getEmployeeName();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NoticePersonalToken noticePersonalToken0 = new NoticePersonalToken("", "", 0L);
      String string0 = noticePersonalToken0.getEmployeeName();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      NoticePersonalToken noticePersonalToken0 = new NoticePersonalToken("%Pjc|[W~{3", (String) null, 0L);
      long long0 = noticePersonalToken0.getTtlInHours();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      NoticePersonalToken noticePersonalToken0 = new NoticePersonalToken((String) null, (String) null, (-3767L));
      String string0 = noticePersonalToken0.getEmployeeName();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      NoticePersonalToken noticePersonalToken0 = new NoticePersonalToken((String) null, (String) null, 0L);
      String string0 = noticePersonalToken0.getToken();
  }
}
