/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 19 01:43:43 GMT 2026
 */

package com.analytics.covid19.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.analytics.covid19.parser.CSVParser;
import com.analytics.covid19.source.CSVSource;
import com.analytics.covid19.source.DataSource;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Set;
import java.util.SortedMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CSVParser_ESTest extends CSVParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Zzts:ZZ,SG");
      byte[] byteArray0 = new byte[10];
      boolean boolean0 = FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      CSVSource cSVSource0 = new CSVSource("Zzts:ZZ,SG");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      // Undeclared exception!
      try { 
        cSVParser0.parseKeyVals();
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CSVSource cSVSource0 = new CSVSource("");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      ArrayList<String> arrayList0 = cSVParser0.getDatesIndeces();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CSVSource cSVSource0 = new CSVSource("ONAb':LoO");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      int int0 = cSVParser0.getDateIndex(",");
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CSVSource cSVSource0 = new CSVSource("ONAb':LoO");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      String[] stringArray0 = cSVParser0.skipQC(",");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CSVSource cSVSource0 = new CSVSource("");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      SortedMap<String, ArrayList<String>> sortedMap0 = cSVParser0.parseKeyVals();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser((DataSource) null);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      ArrayList<LocalDate> arrayList1 = cSVParser0.convertDates(arrayList0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser((DataSource) null);
      // Undeclared exception!
      try { 
        cSVParser0.skipQC((String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser((DataSource) null);
      // Undeclared exception!
      try { 
        cSVParser0.parseKeyVals();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser((DataSource) null);
      // Undeclared exception!
      try { 
        cSVParser0.getDatesIndeces();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Zzts:ZZ,SG");
      boolean boolean0 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      CSVSource cSVSource0 = new CSVSource("Zzts:ZZ,SG");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      // Undeclared exception!
      try { 
        cSVParser0.getDatesIndeces();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser((DataSource) null);
      // Undeclared exception!
      try { 
        cSVParser0.getDateIndex("org.springframework.data.domain.SliceImpl");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser((DataSource) null);
      // Undeclared exception!
      try { 
        cSVParser0.convertDates((ArrayList<String>) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CSVSource cSVSource0 = new CSVSource("Zzts:ZZ,SG");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      String[] stringArray0 = cSVParser0.skipQC("Zzts:ZZ,SG");
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Zzts:ZZ,SG");
      boolean boolean0 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      boolean boolean1 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      boolean boolean2 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      boolean boolean3 = FileSystemHandling.appendLineToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      CSVSource cSVSource0 = new CSVSource("Zzts:ZZ,SG");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      int int0 = cSVParser0.getDateIndex((String) null);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Zzts:ZZ,SG");
      boolean boolean0 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      CSVSource cSVSource0 = new CSVSource("Zzts:ZZ,SG");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      int int0 = cSVParser0.getDateIndex((String) null);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Zzts:ZZ,SG");
      boolean boolean0 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      boolean boolean1 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      boolean boolean2 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      boolean boolean3 = FileSystemHandling.appendLineToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      CSVSource cSVSource0 = new CSVSource("Zzts:ZZ,SG");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      ArrayList<String> arrayList0 = cSVParser0.getDatesIndeces();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Zzts:ZZ,SG");
      boolean boolean0 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      CSVSource cSVSource0 = new CSVSource("Zzts:ZZ,SG");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      ArrayList<String> arrayList0 = cSVParser0.getDatesIndeces();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser((DataSource) null);
      String[] stringArray0 = cSVParser0.skipQC(")eh=\"2e.I]TbK\"7v.O");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser((DataSource) null);
      String[] stringArray0 = cSVParser0.skipQC("mSV(?_XJ`\"Ia'U,z");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Zzts:ZZ,SG");
      boolean boolean0 = FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      CSVSource cSVSource0 = new CSVSource("Zzts:ZZ,SG");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      // Undeclared exception!
      try { 
        cSVParser0.parseKeyVals();
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Zzts:ZZ,SG");
      boolean boolean0 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "Zzts:ZZ,SG");
      CSVSource cSVSource0 = new CSVSource("Zzts:ZZ,SG");
      CSVParser cSVParser0 = new CSVParser(cSVSource0);
      SortedMap<String, ArrayList<String>> sortedMap0 = cSVParser0.parseKeyVals();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CSVParser cSVParser0 = new CSVParser((DataSource) null);
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      ArrayList<String> arrayList0 = new ArrayList<String>(set0);
      // Undeclared exception!
      try { 
        cSVParser0.convertDates(arrayList0);
      } catch(DateTimeParseException e) {
         //
         // Text 'Asia/Aden' could not be parsed at index 0
         //
         verifyException("java.time.format.DateTimeFormatter", e);
      }
  }
}
