/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 17:12:21 GMT 2026
 */

package icu.samnyan.aqua.sega.util.jackson;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.SerializerProvider;
import icu.samnyan.aqua.sega.util.jackson.ByteBufSerializer;
import io.netty.buffer.ByteBuf;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ByteBufSerializer_ESTest extends ByteBufSerializer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ByteBufSerializer byteBufSerializer0 = new ByteBufSerializer();
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(byteBuf0).readableBytes();
      doReturn(0).when(byteBuf0).readerIndex();
      JsonGenerator jsonGenerator0 = mock(JsonGenerator.class, new ViolatedAssumptionAnswer());
      SerializerProvider serializerProvider0 = mock(SerializerProvider.class, new ViolatedAssumptionAnswer());
      byteBufSerializer0.serialize(byteBuf0, jsonGenerator0, serializerProvider0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Class<ByteBuf> class0 = ByteBuf.class;
      ByteBufSerializer byteBufSerializer0 = new ByteBufSerializer(class0);
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      doReturn((-3464)).when(byteBuf0).readableBytes();
      doReturn(522133279).when(byteBuf0).readerIndex();
      JsonGenerator jsonGenerator0 = mock(JsonGenerator.class, new ViolatedAssumptionAnswer());
      SerializerProvider serializerProvider0 = mock(SerializerProvider.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        byteBufSerializer0.serialize(byteBuf0, jsonGenerator0, serializerProvider0);
      } catch(IllegalArgumentException e) {
         //
         // length : -3464 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ByteBufSerializer byteBufSerializer0 = new ByteBufSerializer();
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(byteBuf0).readableBytes();
      doReturn(0).when(byteBuf0).readerIndex();
      SerializerProvider serializerProvider0 = mock(SerializerProvider.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        byteBufSerializer0.serialize(byteBuf0, (JsonGenerator) null, serializerProvider0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("icu.samnyan.aqua.sega.util.jackson.ByteBufSerializer", e);
      }
  }
}
