/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 21:59:30 GMT 2026
 */

package com.zxl.dailypractice.designPattern.ResponsibilityPattern;

import org.junit.Test;
import static org.junit.Assert.*;
import com.zxl.dailypractice.designPattern.ResponsibilityPattern.Client;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Client_ESTest extends Client_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Client client0 = new Client();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Client.main(stringArray0);
  }
}
