/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 30 19:39:02 GMT 2026
 */

package org.openRealmOfStars.starMap.planet.status;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Optional;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.json.JSONObject;
import org.junit.runner.RunWith;
import org.openRealmOfStars.starMap.planet.status.PlanetaryStatus;
import org.openRealmOfStars.starMap.planet.status.PlanetaryStatusLoader;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class PlanetaryStatusLoader_ESTest extends PlanetaryStatusLoader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PlanetaryStatusLoader planetaryStatusLoader0 = new PlanetaryStatusLoader();
      String[] stringArray0 = new String[0];
      Object object0 = new Object();
      JSONObject jSONObject0 = new JSONObject(object0, stringArray0);
      Optional<PlanetaryStatus> optional0 = planetaryStatusLoader0.parseFromJson(jSONObject0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlanetaryStatusLoader planetaryStatusLoader0 = new PlanetaryStatusLoader();
      String[] stringArray0 = new String[6];
      PlanetaryStatus planetaryStatus0 = new PlanetaryStatus("", "", "", stringArray0);
      String string0 = planetaryStatusLoader0.valueIdGetter(planetaryStatus0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PlanetaryStatusLoader planetaryStatusLoader0 = new PlanetaryStatusLoader();
      // Undeclared exception!
      try { 
        planetaryStatusLoader0.valueIdGetter((PlanetaryStatus) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.openRealmOfStars.starMap.planet.status.PlanetaryStatusLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlanetaryStatusLoader planetaryStatusLoader0 = new PlanetaryStatusLoader();
      // Undeclared exception!
      try { 
        planetaryStatusLoader0.parseFromJson((JSONObject) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.openRealmOfStars.starMap.planet.status.PlanetaryStatusLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PlanetaryStatusLoader planetaryStatusLoader0 = new PlanetaryStatusLoader();
      String[] stringArray0 = new String[6];
      PlanetaryStatus planetaryStatus0 = new PlanetaryStatus("2f{xY-Vp0\"?|=a0/3", "_d#4a", "", stringArray0);
      JSONObject jSONObject0 = new JSONObject(planetaryStatus0);
      Optional<PlanetaryStatus> optional0 = planetaryStatusLoader0.parseFromJson(jSONObject0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlanetaryStatusLoader planetaryStatusLoader0 = new PlanetaryStatusLoader();
      String string0 = planetaryStatusLoader0.typeNameGetter();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PlanetaryStatusLoader planetaryStatusLoader0 = new PlanetaryStatusLoader();
      String[] stringArray0 = new String[6];
      PlanetaryStatus planetaryStatus0 = new PlanetaryStatus("2f{xY-Vp0\"?|=a0/3", "_d#4a", "", stringArray0);
      String string0 = planetaryStatusLoader0.valueIdGetter(planetaryStatus0);
  }
}
