/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 20 09:16:18 GMT 2026
 */

package com.alkemy.ong.infrastructure.rest.response.category;

import org.junit.Test;
import static org.junit.Assert.*;
import com.alkemy.ong.infrastructure.rest.response.category.UpdateCategoryResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UpdateCategoryResponse_ESTest extends UpdateCategoryResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Long long0 = new Long(97L);
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse(long0, "L#(MPj1h<V\"", "L#(MPj1h<V\"", "aCbh}mK^TR;");
      String string0 = updateCategoryResponse0.getName();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse();
      updateCategoryResponse0.setName("");
      String string0 = updateCategoryResponse0.getName();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Long long0 = new Long(1L);
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse(long0, "", "cy in\"m2'Q~", "cy in\"m2'Q~");
      String string0 = updateCategoryResponse0.getImageUrl();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Long long0 = new Long(1L);
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse(long0, "", "cy in\"m2'Q~", "cy in\"m2'Q~");
      updateCategoryResponse0.setImageUrl("");
      String string0 = updateCategoryResponse0.getImageUrl();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse();
      Long long0 = new Long(0L);
      updateCategoryResponse0.setId(long0);
      Long long1 = updateCategoryResponse0.getId();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Long long0 = new Long(1L);
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse(long0, "", "cy in\"m2'Q~", "cy in\"m2'Q~");
      Long long1 = updateCategoryResponse0.getId();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse();
      updateCategoryResponse0.setDescription("com.alkemy.ong.infrastructure.rest.response.category.UpdateCategoryResponse");
      String string0 = updateCategoryResponse0.getDescription();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse();
      updateCategoryResponse0.setDescription("");
      String string0 = updateCategoryResponse0.getDescription();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse();
      String string0 = updateCategoryResponse0.getImageUrl();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse();
      Long long0 = updateCategoryResponse0.getId();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse();
      Long long0 = new Long((-1564L));
      updateCategoryResponse0.setId(long0);
      Long long1 = updateCategoryResponse0.getId();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse();
      String string0 = updateCategoryResponse0.getDescription();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      UpdateCategoryResponse updateCategoryResponse0 = new UpdateCategoryResponse();
      String string0 = updateCategoryResponse0.getName();
  }
}
