/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 12 09:39:57 GMT 2026
 */

package com.zxl.dailypractice.io;

import org.junit.Test;
import static org.junit.Assert.*;
import com.zxl.dailypractice.io.FileToUnicode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FileToUnicode_ESTest extends FileToUnicode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileToUnicode.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("E:\\daily-practice\\src\\main\\java\\com\\zxl\\dailypractice\\Io\\file1.txt");
      byte[] byteArray0 = new byte[7];
      boolean boolean0 = FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      FileToUnicode.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FileToUnicode fileToUnicode0 = new FileToUnicode();
  }
}
