/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 12 07:30:26 GMT 2026
 */

package ru.yandex.practicum.filmorate.storage.Dao;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zaxxer.hikari.HikariDataSource;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import javax.sql.ConnectionPoolDataSource;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.h2.jdbcx.JdbcConnectionPool;
import org.junit.runner.RunWith;
import org.postgresql.ds.PGSimpleDataSource;
import org.springframework.jdbc.core.JdbcTemplate;
import ru.yandex.practicum.filmorate.storage.Dao.MpaDaoStorage;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MpaDaoStorage_ESTest extends MpaDaoStorage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          PGSimpleDataSource pGSimpleDataSource0 = new PGSimpleDataSource();
          JdbcTemplate jdbcTemplate0 = new JdbcTemplate(pGSimpleDataSource0);
          MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
          // Undeclared exception!
          try { 
            mpaDaoStorage0.getMpaById(868);
          } catch(RuntimeException e) {
             //
             // Mpa-\u0440\u0435\u0439\u0442\u0438\u043D\u0433 \u0444\u0438\u043B\u044C\u043C\u0430 \u043F\u043E \u0438\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\u0442\u043E\u0440\u0443 {} \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D.
             //
             verifyException("ru.yandex.practicum.filmorate.storage.Dao.MpaDaoStorage", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HikariDataSource hikariDataSource0 = new HikariDataSource();
      hikariDataSource0.setDataSourceClassName("RAZK}W?CB?&$<G");
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate(hikariDataSource0);
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getMpaById((-2198));
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: Class 'RAZK}W?CB?&$<G.class' should be in target project, but could not be found!
         //
         verifyException("com.zaxxer.hikari.util.UtilityElf", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage((JdbcTemplate) null);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getMpaById(0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JdbcConnectionPool jdbcConnectionPool0 = JdbcConnectionPool.create((ConnectionPoolDataSource) null);
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate(jdbcConnectionPool0);
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getMpaById(1016);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.h2.jdbcx.JdbcConnectionPool", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate();
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getMpaById(1008);
      } catch(IllegalStateException e) {
         //
         // No DataSource set
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HikariDataSource hikariDataSource0 = new HikariDataSource();
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate(hikariDataSource0);
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getMpaById(1);
      } catch(IllegalArgumentException e) {
         //
         // dataSource or dataSourceClassName or jdbcUrl is required.
         //
         verifyException("com.zaxxer.hikari.HikariConfig", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PGSimpleDataSource pGSimpleDataSource0 = new PGSimpleDataSource();
      String[] stringArray0 = new String[3];
      pGSimpleDataSource0.setServerNames(stringArray0);
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate(pGSimpleDataSource0, true);
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getMpaById(565);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          PGSimpleDataSource pGSimpleDataSource0 = new PGSimpleDataSource();
          JdbcTemplate jdbcTemplate0 = new JdbcTemplate(pGSimpleDataSource0);
          MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
          // Undeclared exception!
          try { 
            mpaDaoStorage0.getAllMpa();
          } catch(RuntimeException e) {
             //
             // Failed to obtain JDBC Connection; nested exception is org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
             //
             verifyException("org.springframework.jdbc.datasource.DataSourceUtils", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HikariDataSource hikariDataSource0 = new HikariDataSource();
      hikariDataSource0.setDataSourceJNDI("Sc");
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate(hikariDataSource0);
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getAllMpa();
      } catch(RuntimeException e) {
         //
         // Failed to initialize pool: Need to specify class name in environment or system property, or in an application resource file: java.naming.factory.initial
         //
         verifyException("com.zaxxer.hikari.pool.PoolBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HikariDataSource hikariDataSource0 = new HikariDataSource();
      hikariDataSource0.setDataSourceClassName("RAZK}W?CB?&$<G");
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate(hikariDataSource0);
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getAllMpa();
      } catch(RuntimeException e) {
         //
         // java.lang.ClassNotFoundException: Class 'RAZK}W?CB?&$<G.class' should be in target project, but could not be found!
         //
         verifyException("com.zaxxer.hikari.util.UtilityElf", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JdbcConnectionPool jdbcConnectionPool0 = JdbcConnectionPool.create((ConnectionPoolDataSource) null);
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate(jdbcConnectionPool0, true);
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getAllMpa();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.h2.jdbcx.JdbcConnectionPool", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate();
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getAllMpa();
      } catch(IllegalStateException e) {
         //
         // No DataSource set
         //
         verifyException("org.springframework.util.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HikariDataSource hikariDataSource0 = new HikariDataSource();
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate(hikariDataSource0);
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getAllMpa();
      } catch(IllegalArgumentException e) {
         //
         // dataSource or dataSourceClassName or jdbcUrl is required.
         //
         verifyException("com.zaxxer.hikari.HikariConfig", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PGSimpleDataSource pGSimpleDataSource0 = new PGSimpleDataSource();
      String[] stringArray0 = new String[3];
      pGSimpleDataSource0.setServerNames(stringArray0);
      JdbcTemplate jdbcTemplate0 = new JdbcTemplate(pGSimpleDataSource0, true);
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage(jdbcTemplate0);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getAllMpa();
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MpaDaoStorage mpaDaoStorage0 = new MpaDaoStorage((JdbcTemplate) null);
      // Undeclared exception!
      try { 
        mpaDaoStorage0.getAllMpa();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
