/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 21 00:22:50 GMT 2026
 */

package io.axoniq.demo.bikerental.bikerental.command;

import org.junit.Test;
import static org.junit.Assert.*;
import io.axoniq.demo.bikerental.bikerental.command.BikeSnapshotDefinition;
import org.axonframework.eventsourcing.Snapshotter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BikeSnapshotDefinition_ESTest extends BikeSnapshotDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BikeSnapshotDefinition bikeSnapshotDefinition0 = new BikeSnapshotDefinition((Snapshotter) null);
  }
}
