/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 16:42:33 GMT 2026
 */

package mil.nga.geopackage.attributes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import mil.nga.geopackage.attributes.AttributesColumn;
import mil.nga.geopackage.attributes.AttributesColumns;
import mil.nga.geopackage.attributes.AttributesTable;
import mil.nga.geopackage.contents.Contents;
import mil.nga.geopackage.contents.ContentsDataType;
import mil.nga.geopackage.db.GeoPackageDataType;
import mil.nga.geopackage.db.table.RawConstraint;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AttributesTable_ESTest extends AttributesTable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("", linkedList0);
      attributesTable0.setValueValidation(false);
      AttributesColumns attributesColumns0 = attributesTable0.getUserColumns();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("h`7Ze [I>4v[8cPmC>X", linkedList0);
      attributesTable0.setPkModifiable(true);
      AttributesColumns attributesColumns0 = attributesTable0.getUserColumns();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesColumn attributesColumn0 = AttributesColumn.createPrimaryKeyColumn("2/,");
      boolean boolean0 = linkedList0.add(attributesColumn0);
      AttributesTable attributesTable0 = new AttributesTable("", linkedList0);
      AttributesColumns attributesColumns0 = attributesTable0.getUserColumns();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("", linkedList0);
      AttributesColumns attributesColumns0 = attributesTable0.createUserColumns((List<AttributesColumn>) linkedList0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesColumn attributesColumn0 = AttributesColumn.createPrimaryKeyColumn("", false);
      boolean boolean0 = linkedList0.add(attributesColumn0);
      AttributesTable attributesTable0 = new AttributesTable("", linkedList0);
      AttributesColumns attributesColumns0 = attributesTable0.createUserColumns((List<AttributesColumn>) linkedList0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("mil.nga.geopackage.db.table.RawConstraint", linkedList0);
      attributesTable0.setValueValidation(false);
      AttributesTable attributesTable1 = attributesTable0.copy();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable((String) null, linkedList0);
      attributesTable0.setPkModifiable(true);
      AttributesTable attributesTable1 = attributesTable0.copy();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("w", linkedList0);
      Integer integer0 = new Integer(1206);
      RawConstraint rawConstraint0 = new RawConstraint(integer0, "w");
      attributesTable0.addConstraint(rawConstraint0);
      AttributesTable attributesTable1 = attributesTable0.copy();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesColumn attributesColumn0 = AttributesColumn.createPrimaryKeyColumn("BYTE_ARRAY");
      boolean boolean0 = linkedList0.offerFirst(attributesColumn0);
      AttributesTable attributesTable0 = new AttributesTable("'O%xu_\"g5LRCLe5", linkedList0);
      AttributesTable attributesTable1 = attributesTable0.copy();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      GeoPackageDataType geoPackageDataType0 = GeoPackageDataType.REAL;
      AttributesColumns attributesColumns0 = new AttributesColumns("built statement {}", linkedList0);
      AttributesColumn attributesColumn0 = AttributesColumn.createColumn(0, "", geoPackageDataType0, false, (Object) attributesColumns0);
      boolean boolean0 = linkedList0.add(attributesColumn0);
      AttributesColumn attributesColumn1 = AttributesColumn.createPrimaryKeyColumn("%ei=*H@Ai1U{AZLz", false);
      boolean boolean1 = linkedList0.add(attributesColumn1);
      AttributesTable attributesTable0 = new AttributesTable("r>#vc91hFyzNO", linkedList0);
      AttributesTable attributesTable1 = attributesTable0.copy();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("!KV<", linkedList0);
      // Undeclared exception!
      try { 
        attributesTable0.validateContents((Contents) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("mil.nga.geopackage.attributes.AttributesTable", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("mil.nga.geopackage.user.custom.UserCustomColumns", linkedList0);
      AttributesColumn attributesColumn0 = AttributesColumn.createPrimaryKeyColumn("mil.nga.geopackage.user.custom.UserCustomColumns");
      List<AttributesColumn> list0 = List.of(attributesColumn0, attributesColumn0, attributesColumn0, attributesColumn0, attributesColumn0, attributesColumn0, attributesColumn0, attributesColumn0);
      // Undeclared exception!
      try { 
        attributesTable0.createUserColumns(list0);
      } catch(RuntimeException e) {
         //
         // More than one primary key column was found for custom specified table columns. table: mil.nga.geopackage.user.custom.UserCustomColumns, index1: 0, index2: 1, columns: [Ljava.lang.String;@16df0852
         //
         verifyException("mil.nga.geopackage.user.UserColumns", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("q E5ChA59Ly|Dt~`lc", linkedList0);
      boolean boolean0 = linkedList0.offer((AttributesColumn) null);
      // Undeclared exception!
      try { 
        attributesTable0.copy();
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("h", linkedList0);
      boolean boolean0 = linkedList0.add((AttributesColumn) null);
      AttributesTable attributesTable1 = null;
      try {
        attributesTable1 = new AttributesTable(attributesTable0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesColumn attributesColumn0 = AttributesColumn.createPrimaryKeyColumn(1, " parsing default date-long value: ");
      boolean boolean0 = linkedList0.add(attributesColumn0);
      AttributesTable attributesTable0 = null;
      try {
        attributesTable0 = new AttributesTable((String) null, linkedList0);
      } catch(RuntimeException e) {
         //
         // No column found at index: 0, Table Name: null
         //
         verifyException("mil.nga.geopackage.user.UserColumns", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GeoPackageDataType geoPackageDataType0 = GeoPackageDataType.FLOAT;
      AttributesColumn attributesColumn0 = AttributesColumn.createColumn("T", geoPackageDataType0, true, (Object) null);
      List<AttributesColumn> list0 = List.of(attributesColumn0);
      AttributesTable attributesTable0 = null;
      try {
        attributesTable0 = new AttributesTable("", list0);
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ImmutableCollections", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      boolean boolean0 = linkedList0.add((AttributesColumn) null);
      AttributesTable attributesTable0 = null;
      try {
        attributesTable0 = new AttributesTable("?", linkedList0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("", linkedList0);
      AttributesTable attributesTable1 = new AttributesTable(attributesTable0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("!KV<", linkedList0);
      Contents contents0 = new Contents();
      ContentsDataType contentsDataType0 = ContentsDataType.TILES;
      contents0.setDataType(contentsDataType0);
      // Undeclared exception!
      try { 
        attributesTable0.validateContents(contents0);
      } catch(RuntimeException e) {
         //
         // The Contents of an AttributesTable must have a data type of attributes. actual type: tiles
         //
         verifyException("mil.nga.geopackage.attributes.AttributesTable", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("!KV<", linkedList0);
      Contents contents0 = new Contents();
      attributesTable0.validateContents(contents0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable("h`7Ze [I>4v[8cPmC>X", linkedList0);
      String string0 = attributesTable0.getDataType();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LinkedList<AttributesColumn> linkedList0 = new LinkedList<AttributesColumn>();
      AttributesTable attributesTable0 = new AttributesTable((String) null, linkedList0);
      // Undeclared exception!
      try { 
        attributesTable0.createUserColumns((List<AttributesColumn>) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
