/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 12 10:25:19 GMT 2026
 */

package com.zxl.dailypractice.algorithm.Day6;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.zxl.dailypractice.algorithm.Day6.Solution;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution_ESTest extends Solution_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution solution0 = new Solution();
      // Undeclared exception!
      try { 
        solution0.lengthOfLongestSubstring((String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution solution0 = new Solution();
      int int0 = solution0.lengthOfLongestSubstring("Er_^jwBK7R:iY7&,I+");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution solution0 = new Solution();
      int int0 = solution0.lengthOfLongestSubstring("");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution.main((String[]) null);
  }
}
