/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 12 05:31:42 GMT 2026
 */

package kyungseo.poc.simple.web.site.sample.web.view;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import groovy.lang.NonEmptySequence;
import groovy.lang.Sequence;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.LineNumberReader;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletRequestWrapper;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpServletResponseWrapper;
import kyungseo.poc.simple.web.appcore.data.enums.ExcelColumnType;
import kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil;
import org.apache.poi.hssf.model.InternalWorkbook;
import org.apache.poi.hssf.record.Record;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.streaming.SXSSFSheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFFactory;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbookType;
import org.apache.xmlbeans.XmlSimpleList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.springframework.expression.spel.support.StandardTypeLocator;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class XlsxUtil_ESTest extends XlsxUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      HSSFWorkbook hSSFWorkbook0 = new HSSFWorkbook();
      HSSFSheet hSSFSheet0 = hSSFWorkbook0.createSheet("3,");
      xlsxUtil0.autoSizeColumn(hSSFSheet0, 3787);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      Sequence sequence0 = new Sequence();
      StandardOpenOption standardOpenOption0 = StandardOpenOption.CREATE;
      boolean boolean0 = sequence0.add((Object) standardOpenOption0);
      HSSFWorkbook hSSFWorkbook0 = new HSSFWorkbook();
      HSSFSheet hSSFSheet0 = hSSFWorkbook0.createSheet();
      Class<MockFileInputStream> class0 = MockFileInputStream.class;
      Sequence sequence1 = new Sequence(class0);
      // Undeclared exception!
      try { 
        xlsxUtil0.createCell((Workbook) hSSFWorkbook0, (Sheet) hSSFSheet0, (List<List<String>>) sequence0, (List<ExcelColumnType>) sequence1, 1206);
      } catch(ClassCastException e) {
         //
         // class java.nio.file.StandardOpenOption cannot be cast to class java.util.List (java.nio.file.StandardOpenOption and java.util.List are in module java.base of loader 'bootstrap')
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn("").when(httpServletRequest0).getHeader(anyString());
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      String string0 = xlsxUtil0.makeFilename(httpServletRequestWrapper0, "");
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      ArrayList<ExcelColumnType> arrayList0 = new ArrayList<ExcelColumnType>();
      int int0 = xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) xSSFSheet0, (List<List<String>>) null, (List<ExcelColumnType>) arrayList0, 0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      XSSFFactory xSSFFactory0 = XSSFFactory.getInstance();
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook(xSSFFactory0);
      Sequence sequence0 = new Sequence();
      int int0 = xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) null, (List<List<String>>) sequence0, (List<ExcelColumnType>) sequence0, (-109));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      // Undeclared exception!
      try { 
        xlsxUtil0.renderWorkbook(xSSFWorkbook0, (HttpServletResponse) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      HSSFWorkbook hSSFWorkbook0 = new HSSFWorkbook();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((ServletOutputStream) null).when(httpServletResponse0).getOutputStream();
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      // Undeclared exception!
      try { 
        xlsxUtil0.renderWorkbook(hSSFWorkbook0, httpServletResponseWrapper0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.poi.poifs.nio.ByteArrayBackedDataSource", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      XSSFWorkbookType xSSFWorkbookType0 = XSSFWorkbookType.XLSX;
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook(xSSFWorkbookType0);
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((ServletOutputStream) null).when(httpServletResponse0).getOutputStream();
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      // Undeclared exception!
      try { 
        xlsxUtil0.renderWorkbook(xSSFWorkbook0, httpServletResponseWrapper0);
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class java.util.zip.Deflater
         //
         verifyException("org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      SXSSFWorkbook sXSSFWorkbook0 = new SXSSFWorkbook();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((ServletOutputStream) null).when(httpServletResponse0).getOutputStream();
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      // Undeclared exception!
      try { 
        xlsxUtil0.renderWorkbook(sXSSFWorkbook0, httpServletResponseWrapper0);
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class java.util.zip.Deflater
         //
         verifyException("org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      SXSSFWorkbook sXSSFWorkbook0 = new SXSSFWorkbook();
      boolean boolean0 = FileSystemHandling.shouldAllThrowIOExceptions();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((ServletOutputStream) null).when(httpServletResponse0).getOutputStream();
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      try { 
        xlsxUtil0.renderWorkbook(sXSSFWorkbook0, httpServletResponseWrapper0);
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp/poifiles/poi-sxssf-template0.xlsx");
      boolean boolean0 = FileSystemHandling.createFolder(evoSuiteFile0);
      SXSSFWorkbook sXSSFWorkbook0 = new SXSSFWorkbook();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      doReturn((ServletOutputStream) null).when(httpServletResponse0).getOutputStream();
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      try { 
        xlsxUtil0.renderWorkbook(sXSSFWorkbook0, httpServletResponseWrapper0);
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      List<String> list0 = List.of("", "");
      // Undeclared exception!
      try { 
        xlsxUtil0.mergeCellByReference((Sheet) null, list0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      NonEmptySequence nonEmptySequence0 = new NonEmptySequence();
      List<List<String>> list0 = List.of((List<String>) nonEmptySequence0, (List<String>) nonEmptySequence0);
      XmlSimpleList xmlSimpleList0 = new XmlSimpleList(list0);
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      // Undeclared exception!
      try { 
        xlsxUtil0.mergeCellByReference((Sheet) null, xmlSimpleList0);
      } catch(ClassCastException e) {
         //
         // class groovy.lang.NonEmptySequence cannot be cast to class java.lang.String (groovy.lang.NonEmptySequence is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      XmlSimpleList xmlSimpleList0 = new XmlSimpleList((List) null);
      // Undeclared exception!
      try { 
        xlsxUtil0.mergeCellByAddress((Sheet) null, xmlSimpleList0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlbeans.XmlSimpleList", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      // Undeclared exception!
      try { 
        xlsxUtil0.makeFilename((HttpServletRequest) null, "");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      // Undeclared exception!
      try { 
        xlsxUtil0.getCellStyleMap((Workbook) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      Vector<Record> vector0 = new Vector<Record>();
      InternalWorkbook internalWorkbook0 = InternalWorkbook.createWorkbook((List<Record>) vector0);
      HSSFWorkbook hSSFWorkbook0 = HSSFWorkbook.create(internalWorkbook0);
      // Undeclared exception!
      try { 
        xlsxUtil0.getCellStyleMap(hSSFWorkbook0);
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      // Undeclared exception!
      try { 
        xlsxUtil0.defaultSheetStyle((Sheet) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      StandardTypeLocator standardTypeLocator0 = new StandardTypeLocator();
      List<String> list0 = standardTypeLocator0.getImportPrefixes();
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      ArrayList<ExcelColumnType> arrayList0 = new ArrayList<ExcelColumnType>();
      // Undeclared exception!
      try { 
        xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) null, list0, (List<ExcelColumnType>) arrayList0, 1024, (Map<ExcelColumnType, CellStyle>) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      List<String> list0 = List.of("^(d{4})(d{2})(d{2})(d{2})(d{2})$", "^(d{4})(d{2})(d{2})(d{2})(d{2})$");
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      Sequence sequence0 = new Sequence();
      HashMap<ExcelColumnType, CellStyle> hashMap0 = new HashMap<ExcelColumnType, CellStyle>();
      // Undeclared exception!
      try { 
        xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) xSSFSheet0, list0, (List<ExcelColumnType>) sequence0, (-1984), (Map<ExcelColumnType, CellStyle>) hashMap0);
      } catch(IllegalArgumentException e) {
         //
         // Invalid row number (-1984) outside allowable range (0..1048575)
         //
         verifyException("org.apache.poi.xssf.usermodel.XSSFRow", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      List<String> list0 = List.of("^(d{4})(d{2})(d{2})(d{2})(d{2})$", "^(d{4})(d{2})(d{2})(d{2})(d{2})$");
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      HashMap<ExcelColumnType, CellStyle> hashMap0 = new HashMap<ExcelColumnType, CellStyle>();
      Sequence sequence0 = new Sequence();
      boolean boolean0 = sequence0.add((Object) hashMap0);
      // Undeclared exception!
      try { 
        xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) xSSFSheet0, list0, (List<ExcelColumnType>) sequence0, 12, (Map<ExcelColumnType, CellStyle>) hashMap0);
      } catch(ClassCastException e) {
         //
         // class java.util.HashMap cannot be cast to class kyungseo.poc.simple.web.appcore.data.enums.ExcelColumnType (java.util.HashMap is in module java.base of loader 'bootstrap'; kyungseo.poc.simple.web.appcore.data.enums.ExcelColumnType is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @1e5d8313)
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      Workbook workbook0 = xlsxUtil0.createXlsxWorkbook();
      NonEmptySequence nonEmptySequence0 = new NonEmptySequence();
      List<List<String>> list0 = List.of((List<String>) nonEmptySequence0, (List<String>) nonEmptySequence0);
      // Undeclared exception!
      try { 
        xlsxUtil0.createCell(workbook0, (Sheet) null, list0, (List<ExcelColumnType>) nonEmptySequence0, (-2057));
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlbeans.impl.values.JavaLongHolderEx", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      NonEmptySequence nonEmptySequence0 = new NonEmptySequence();
      List<List<String>> list0 = List.of((List<String>) nonEmptySequence0, (List<String>) nonEmptySequence0);
      // Undeclared exception!
      try { 
        xlsxUtil0.createCell((Workbook) null, (Sheet) null, list0, (List<ExcelColumnType>) nonEmptySequence0, (-2041));
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      // Undeclared exception!
      try { 
        xlsxUtil0.autoSizeColumn(xSSFSheet0, 10);
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlbeans.impl.values.JavaLongHolderEx", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      List<String> list0 = List.of("^(d{4})(d{2})(d{2})(d{2})(d{2})$", "^(d{4})(d{2})(d{2})(d{2})(d{2})$");
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      HashMap<ExcelColumnType, CellStyle> hashMap0 = new HashMap<ExcelColumnType, CellStyle>();
      ExcelColumnType excelColumnType0 = ExcelColumnType.DOUBLE;
      ExcelColumnType[] excelColumnTypeArray0 = new ExcelColumnType[5];
      ExcelColumnType excelColumnType1 = ExcelColumnType.DATETIME;
      excelColumnTypeArray0[0] = excelColumnType1;
      excelColumnTypeArray0[1] = excelColumnType0;
      excelColumnTypeArray0[2] = excelColumnType0;
      excelColumnTypeArray0[3] = excelColumnType0;
      excelColumnTypeArray0[4] = excelColumnType0;
      List<ExcelColumnType> list1 = List.of(excelColumnTypeArray0);
      // Undeclared exception!
      try { 
        xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) xSSFSheet0, list0, list1, 8, (Map<ExcelColumnType, CellStyle>) hashMap0);
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      List<String> list0 = List.of("^(d{4})(d{2})(d{2})(d{2})(d{2})$", "^(d{4})(d{2})(d{2})(d{2})(d{2})$");
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      HashMap<ExcelColumnType, CellStyle> hashMap0 = new HashMap<ExcelColumnType, CellStyle>(10);
      ExcelColumnType excelColumnType0 = ExcelColumnType.DOUBLE;
      ExcelColumnType[] excelColumnTypeArray0 = new ExcelColumnType[5];
      ExcelColumnType excelColumnType1 = ExcelColumnType.DATEHHMM;
      excelColumnTypeArray0[0] = excelColumnType1;
      excelColumnTypeArray0[1] = excelColumnType0;
      excelColumnTypeArray0[2] = excelColumnType1;
      excelColumnTypeArray0[3] = excelColumnType0;
      excelColumnTypeArray0[4] = excelColumnType0;
      List<ExcelColumnType> list1 = List.of(excelColumnTypeArray0);
      // Undeclared exception!
      try { 
        xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) xSSFSheet0, list0, list1, 8, (Map<ExcelColumnType, CellStyle>) hashMap0);
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      NonEmptySequence nonEmptySequence0 = new NonEmptySequence();
      List<List<String>> list0 = List.of((List<String>) nonEmptySequence0, (List<String>) nonEmptySequence0);
      XmlSimpleList xmlSimpleList0 = new XmlSimpleList(list0);
      // Undeclared exception!
      try { 
        xlsxUtil0.mergeCellByAddress((Sheet) null, xmlSimpleList0);
      } catch(ClassCastException e) {
         //
         // class groovy.lang.NonEmptySequence cannot be cast to class org.apache.poi.ss.util.CellRangeAddress (groovy.lang.NonEmptySequence is in unnamed module of loader 'app'; org.apache.poi.ss.util.CellRangeAddress is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @1e5d8313)
         //
         verifyException("kyungseo.poc.simple.web.site.sample.web.view.XlsxUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      Class<LineNumberReader> class0 = LineNumberReader.class;
      Sequence sequence0 = new Sequence(class0);
      xlsxUtil0.mergeCellByAddress(xSSFSheet0, sequence0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      StandardTypeLocator standardTypeLocator0 = new StandardTypeLocator();
      List<String> list0 = standardTypeLocator0.getImportPrefixes();
      // Undeclared exception!
      try { 
        xlsxUtil0.mergeCellByReference((Sheet) null, list0);
      } catch(IllegalArgumentException e) {
         //
         // Invalid CellReference: java.lang
         //
         verifyException("org.apache.poi.ss.util.CellReference", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      Sequence sequence0 = new Sequence();
      xlsxUtil0.mergeCellByReference((Sheet) null, sequence0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      // Undeclared exception!
      try { 
        xlsxUtil0.autoSizeColumn((Sheet) null, 18387);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      SXSSFWorkbook sXSSFWorkbook0 = (SXSSFWorkbook)xlsxUtil0.createXlsxWorkbook();
      SXSSFSheet sXSSFSheet0 = sXSSFWorkbook0.createSheet("max-age=0, private, must-revalidate");
      xlsxUtil0.autoSizeColumn(sXSSFSheet0, (-412));
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      List<String> list0 = List.of("^(d{4})(d{2})(d{2})(d{2})(d{2})$", "^(d{4})(d{2})(d{2})(d{2})(d{2})$");
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      HashMap<ExcelColumnType, CellStyle> hashMap0 = new HashMap<ExcelColumnType, CellStyle>();
      ExcelColumnType[] excelColumnTypeArray0 = new ExcelColumnType[1];
      ExcelColumnType excelColumnType0 = ExcelColumnType.INTEGER;
      excelColumnTypeArray0[0] = excelColumnType0;
      List<ExcelColumnType> list1 = List.of(excelColumnTypeArray0);
      // Undeclared exception!
      try { 
        xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) xSSFSheet0, list0, list1, 3764, (Map<ExcelColumnType, CellStyle>) hashMap0);
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      List<String> list0 = List.of("^(d{4})(d{2})(d{2})(d{2})(d{2})$", "^(d{4})(d{2})(d{2})(d{2})(d{2})$");
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      HashMap<ExcelColumnType, CellStyle> hashMap0 = new HashMap<ExcelColumnType, CellStyle>();
      Sequence sequence0 = new Sequence();
      xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) xSSFSheet0, list0, (List<ExcelColumnType>) sequence0, 12, (Map<ExcelColumnType, CellStyle>) hashMap0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      List<String> list0 = List.of("^(d{4})(d{2})(d{2})(d{2})(d{2})$", "^(d{4})(d{2})(d{2})(d{2})(d{2})$");
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      HashMap<ExcelColumnType, CellStyle> hashMap0 = new HashMap<ExcelColumnType, CellStyle>();
      ExcelColumnType excelColumnType0 = ExcelColumnType.DOUBLE;
      ExcelColumnType excelColumnType1 = ExcelColumnType.DATE;
      ExcelColumnType excelColumnType2 = ExcelColumnType.STRING;
      ExcelColumnType[] excelColumnTypeArray0 = new ExcelColumnType[8];
      excelColumnTypeArray0[0] = excelColumnType2;
      excelColumnTypeArray0[1] = excelColumnType1;
      excelColumnTypeArray0[2] = excelColumnType2;
      excelColumnTypeArray0[3] = excelColumnType1;
      excelColumnTypeArray0[4] = excelColumnType2;
      excelColumnTypeArray0[5] = excelColumnType0;
      excelColumnTypeArray0[6] = excelColumnType2;
      excelColumnTypeArray0[7] = excelColumnType0;
      List<ExcelColumnType> list1 = List.of(excelColumnTypeArray0);
      xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) xSSFSheet0, list0, list1, 10, (Map<ExcelColumnType, CellStyle>) hashMap0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      NonEmptySequence nonEmptySequence0 = new NonEmptySequence();
      HashMap<ExcelColumnType, CellStyle> hashMap0 = new HashMap<ExcelColumnType, CellStyle>();
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) null, (List<String>) nonEmptySequence0, (List<ExcelColumnType>) nonEmptySequence0, 8, (Map<ExcelColumnType, CellStyle>) hashMap0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      XSSFWorkbook xSSFWorkbook0 = new XSSFWorkbook();
      XSSFSheet xSSFSheet0 = xSSFWorkbook0.createSheet();
      NonEmptySequence nonEmptySequence0 = new NonEmptySequence();
      int int0 = xlsxUtil0.createCell((Workbook) xSSFWorkbook0, (Sheet) xSSFSheet0, (List<List<String>>) nonEmptySequence0, (List<ExcelColumnType>) nonEmptySequence0, 8);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn("~").when(httpServletRequest0).getHeader(anyString());
      HttpServletRequestWrapper httpServletRequestWrapper0 = new HttpServletRequestWrapper(httpServletRequest0);
      String string0 = xlsxUtil0.makeFilename(httpServletRequestWrapper0, "3,");
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      HttpServletResponseWrapper httpServletResponseWrapper0 = new HttpServletResponseWrapper(httpServletResponse0);
      xlsxUtil0.setResponseHeaders(httpServletResponseWrapper0, "");
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      SXSSFWorkbook sXSSFWorkbook0 = (SXSSFWorkbook)xlsxUtil0.createXlsxWorkbook();
      SXSSFSheet sXSSFSheet0 = sXSSFWorkbook0.createSheet("max-age=0, private, must-revalidate");
      xlsxUtil0.defaultSheetStyle(sXSSFSheet0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      HSSFWorkbook hSSFWorkbook0 = new HSSFWorkbook();
      Map<ExcelColumnType, CellStyle> map0 = xlsxUtil0.getCellStyleMap(hSSFWorkbook0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      XlsxUtil xlsxUtil0 = new XlsxUtil();
      Workbook workbook0 = xlsxUtil0.createXlsxWorkbook();
      // Undeclared exception!
      try { 
        xlsxUtil0.getCellStyleMap(workbook0);
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xmlbeans.impl.values.JavaLongHolderEx", e);
      }
  }
}
