/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 19:31:16 GMT 2026
 */

package skaro.pokeapi.resource.pokemonspecies;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import skaro.pokeapi.resource.NamedApiResource;
import skaro.pokeapi.resource.language.Language;
import skaro.pokeapi.resource.pokemonspecies.Genus;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Genus_ESTest extends Genus_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Genus genus0 = new Genus();
      genus0.setGenus("-N9'uMD/`a! ");
      String string0 = genus0.getGenus();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Genus genus0 = new Genus();
      genus0.setGenus("");
      String string0 = genus0.getGenus();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Genus genus0 = new Genus();
      NamedApiResource<Language> namedApiResource0 = genus0.getLanguage();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Genus genus0 = new Genus();
      NamedApiResource<Language> namedApiResource0 = new NamedApiResource<Language>();
      genus0.setLanguage(namedApiResource0);
      NamedApiResource<Language> namedApiResource1 = genus0.getLanguage();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Genus genus0 = new Genus();
      String string0 = genus0.getGenus();
  }
}
