/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 08:42:56 GMT 2026
 */

package com.loomcom.symon;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.loomcom.symon.Breakpoints;
import com.loomcom.symon.Simulator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Breakpoints_ESTest extends Breakpoints_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      // Undeclared exception!
      try { 
        breakpoints0.getValueAt(2556, 1);
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      // Undeclared exception!
      try { 
        breakpoints0.getValueAt(74, 0);
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      Object object0 = breakpoints0.getValueAt((-1452), (-64));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      String string0 = breakpoints0.getColumnName((-1452));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      // Undeclared exception!
      try { 
        breakpoints0.removeBreakpointAtIndex(0);
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      breakpoints0.addBreakpoint((-489));
      breakpoints0.addBreakpoint(1352);
      breakpoints0.addBreakpoint(149);
      breakpoints0.removeBreakpointAtIndex(2);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      breakpoints0.addBreakpoint(143);
      Object object0 = breakpoints0.getValueAt(0, 0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      breakpoints0.addBreakpoint(143);
      int int0 = breakpoints0.getRowCount();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      String string0 = breakpoints0.getColumnName(22);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      breakpoints0.addBreakpoint((-1452));
      boolean boolean0 = breakpoints0.contains((-1452));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      int int0 = breakpoints0.findColumn("'zt}u?XwS$");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      breakpoints0.removeBreakpointAtIndex((-1374));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      breakpoints0.refresh();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      int int0 = breakpoints0.getRowCount();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      int int0 = breakpoints0.getColumnCount();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      breakpoints0.addBreakpoint(304);
      breakpoints0.addBreakpoint(1911);
      // Undeclared exception!
      try { 
        breakpoints0.getValueAt(1, 1);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Breakpoints breakpoints0 = new Breakpoints((Simulator) null);
      boolean boolean0 = breakpoints0.contains((-1452));
  }
}
