/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Aug 08 08:13:44 GMT 2026
 */

package com.getindata.connectors.http.internal.table;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class SerializationSchemaElementConverter_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.getindata.connectors.http.internal.table.SerializationSchemaElementConverter"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SerializationSchemaElementConverter_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.flink.api.connector.sink2.Sink",
      "org.apache.flink.connector.base.sink.writer.ElementConverter",
      "com.getindata.connectors.http.internal.table.SerializationSchemaElementConverter",
      "org.apache.flink.metrics.groups.SinkWriterMetricGroup",
      "org.apache.flink.api.connector.sink2.SinkWriter",
      "org.apache.flink.metrics.groups.OperatorMetricGroup",
      "org.apache.flink.table.data.RowData$FieldGetter",
      "com.getindata.connectors.http.internal.utils.SynchronizedSerializationSchema",
      "org.apache.flink.table.data.RowData",
      "org.apache.flink.api.common.typeutils.TypeSerializer",
      "org.apache.flink.util.FlinkRuntimeException",
      "org.apache.flink.table.data.TimestampData",
      "org.apache.flink.util.AbstractID",
      "org.apache.flink.table.data.MapData",
      "org.apache.flink.util.UserCodeClassLoader",
      "org.apache.flink.api.common.operators.MailboxExecutor",
      "org.apache.flink.api.common.operators.ProcessingTimeService",
      "org.apache.flink.table.data.DecimalData",
      "org.apache.flink.api.connector.sink2.SinkWriter$Context",
      "com.getindata.connectors.http.internal.sink.HttpSinkRequestEntry",
      "org.apache.flink.table.data.StringData",
      "org.apache.flink.api.common.serialization.SerializationSchema$InitializationContext",
      "org.apache.flink.table.data.ArrayData",
      "org.apache.flink.metrics.MetricGroup",
      "org.apache.flink.api.common.JobID",
      "org.apache.flink.table.types.logical.LogicalType",
      "com.getindata.connectors.http.SchemaLifecycleAwareElementConverter",
      "org.apache.flink.types.RowKind",
      "org.apache.flink.table.data.RawValueData",
      "org.apache.flink.api.common.serialization.SerializationSchema",
      "org.apache.flink.api.connector.sink2.Sink$InitContext"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.apache.flink.api.common.serialization.SerializationSchema", false, SerializationSchemaElementConverter_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.flink.api.connector.sink2.Sink$InitContext", false, SerializationSchemaElementConverter_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.flink.api.connector.sink2.SinkWriter$Context", false, SerializationSchemaElementConverter_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.flink.table.data.RowData", false, SerializationSchemaElementConverter_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SerializationSchemaElementConverter_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.getindata.connectors.http.internal.table.SerializationSchemaElementConverter",
      "com.getindata.connectors.http.internal.utils.SynchronizedSerializationSchema",
      "com.getindata.connectors.http.internal.sink.HttpSinkRequestEntry",
      "org.apache.flink.util.FlinkRuntimeException"
    );
  }
}
