/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 08:13:44 GMT 2026
 */

package com.getindata.connectors.http.internal.table;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.getindata.connectors.http.internal.sink.HttpSinkRequestEntry;
import com.getindata.connectors.http.internal.table.SerializationSchemaElementConverter;
import com.getindata.connectors.http.internal.utils.SynchronizedSerializationSchema;
import org.apache.flink.api.common.serialization.SerializationSchema;
import org.apache.flink.api.connector.sink2.Sink;
import org.apache.flink.api.connector.sink2.SinkWriter;
import org.apache.flink.table.data.RowData;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SerializationSchemaElementConverter_ESTest extends SerializationSchemaElementConverter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      SerializationSchema<RowData> serializationSchema0 = (SerializationSchema<RowData>) mock(SerializationSchema.class, new ViolatedAssumptionAnswer());
      doReturn(byteArray0).when(serializationSchema0).serialize(any(org.apache.flink.table.data.RowData.class));
      SynchronizedSerializationSchema<RowData> synchronizedSerializationSchema0 = new SynchronizedSerializationSchema<RowData>(serializationSchema0);
      SerializationSchemaElementConverter serializationSchemaElementConverter0 = new SerializationSchemaElementConverter("", synchronizedSerializationSchema0);
      RowData rowData0 = mock(RowData.class, new ViolatedAssumptionAnswer());
      SinkWriter.Context sinkWriter_Context0 = mock(SinkWriter.Context.class, new ViolatedAssumptionAnswer());
      HttpSinkRequestEntry httpSinkRequestEntry0 = serializationSchemaElementConverter0.apply(rowData0, sinkWriter_Context0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      SerializationSchema<RowData> serializationSchema0 = (SerializationSchema<RowData>) mock(SerializationSchema.class, new ViolatedAssumptionAnswer());
      doReturn(byteArray0).when(serializationSchema0).serialize(any(org.apache.flink.table.data.RowData.class));
      SynchronizedSerializationSchema<RowData> synchronizedSerializationSchema0 = new SynchronizedSerializationSchema<RowData>(serializationSchema0);
      SerializationSchemaElementConverter serializationSchemaElementConverter0 = new SerializationSchemaElementConverter("RB o", synchronizedSerializationSchema0);
      RowData rowData0 = mock(RowData.class, new ViolatedAssumptionAnswer());
      SinkWriter.Context sinkWriter_Context0 = mock(SinkWriter.Context.class, new ViolatedAssumptionAnswer());
      HttpSinkRequestEntry httpSinkRequestEntry0 = serializationSchemaElementConverter0.apply(rowData0, sinkWriter_Context0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SerializationSchema<RowData> serializationSchema0 = (SerializationSchema<RowData>) mock(SerializationSchema.class, new ViolatedAssumptionAnswer());
      doReturn((byte[]) null).when(serializationSchema0).serialize(any(org.apache.flink.table.data.RowData.class));
      SynchronizedSerializationSchema<RowData> synchronizedSerializationSchema0 = new SynchronizedSerializationSchema<RowData>(serializationSchema0);
      SerializationSchemaElementConverter serializationSchemaElementConverter0 = new SerializationSchemaElementConverter((String) null, synchronizedSerializationSchema0);
      RowData rowData0 = mock(RowData.class, new ViolatedAssumptionAnswer());
      SinkWriter.Context sinkWriter_Context0 = mock(SinkWriter.Context.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        serializationSchemaElementConverter0.apply(rowData0, sinkWriter_Context0);
      } catch(NullPointerException e) {
         //
         // method is marked non-null but is null
         //
         verifyException("com.getindata.connectors.http.internal.sink.HttpSinkRequestEntry", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SerializationSchema<RowData> serializationSchema0 = (SerializationSchema<RowData>) mock(SerializationSchema.class, new ViolatedAssumptionAnswer());
      SynchronizedSerializationSchema<RowData> synchronizedSerializationSchema0 = new SynchronizedSerializationSchema<RowData>(serializationSchema0);
      SerializationSchemaElementConverter serializationSchemaElementConverter0 = new SerializationSchemaElementConverter("sZs4", synchronizedSerializationSchema0);
      Sink.InitContext sink_InitContext0 = mock(Sink.InitContext.class, new ViolatedAssumptionAnswer());
      doReturn((SerializationSchema.InitializationContext) null).when(sink_InitContext0).asSerializationSchemaInitializationContext();
      serializationSchemaElementConverter0.open(sink_InitContext0);
      Sink.InitContext sink_InitContext1 = mock(Sink.InitContext.class, new ViolatedAssumptionAnswer());
      serializationSchemaElementConverter0.open(sink_InitContext1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SerializationSchemaElementConverter serializationSchemaElementConverter0 = new SerializationSchemaElementConverter("zN x2E:pc9|,ohYCwUr", (SerializationSchema<RowData>) null);
      // Undeclared exception!
      try { 
        serializationSchemaElementConverter0.apply((RowData) null, (SinkWriter.Context) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SerializationSchemaElementConverter serializationSchemaElementConverter0 = new SerializationSchemaElementConverter("=*z", (SerializationSchema<RowData>) null);
      // Undeclared exception!
      try { 
        serializationSchemaElementConverter0.open((Sink.InitContext) null);
      } catch(RuntimeException e) {
         //
         // Failed to initialize serialization schema.
         //
         verifyException("com.getindata.connectors.http.internal.table.SerializationSchemaElementConverter", e);
      }
  }
}
