/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 06 13:20:58 GMT 2026
 */

package org.example.toylanguage.expression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.toylanguage.expression.Expression;
import org.example.toylanguage.expression.ExpressionReader;
import org.example.toylanguage.token.Token;
import org.example.toylanguage.token.TokensStack;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ExpressionReader_ESTest extends ExpressionReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<Token> linkedList0 = new LinkedList<Token>();
      TokensStack tokensStack0 = new TokensStack(linkedList0);
      tokensStack0.back();
      // Undeclared exception!
      try { 
        ExpressionReader.readExpression(tokensStack0);
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -1, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      List<Token> list0 = List.of();
      TokensStack tokensStack0 = new TokensStack(list0);
      tokensStack0.back();
      // Undeclared exception!
      try { 
        ExpressionReader.readExpression(tokensStack0);
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Token> linkedList0 = new LinkedList<Token>();
      TokensStack tokensStack0 = new TokensStack(linkedList0);
      Expression expression0 = ExpressionReader.readExpression(tokensStack0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExpressionReader.readExpression((ExpressionReader) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.toylanguage.expression.ExpressionReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        ExpressionReader.readExpression((TokensStack) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
