/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 07 22:30:49 GMT 2026
 */

package com.creativityfactory.swiftserver.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.creativityfactory.swiftserver.utils.IdUtils;
import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IdUtils_ESTest extends IdUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      Map<String, Object> map0 = IdUtils.mapIdToObject(class0, class0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Class<Field> class0 = Field.class;
      Class<?> class1 = IdUtils.getIdTypeFromModel(class0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      // Undeclared exception!
      try { 
        IdUtils.mapObjectToId("1>$\"%,f}Ta&At.3", (Class<?>) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Class<Annotation> class0 = Annotation.class;
      // Undeclared exception!
      try { 
        IdUtils.mapObjectToId(",C^", class0);
      } catch(RuntimeException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Unexpected value at line 1 column 2 path $
         //
         verifyException("com.google.gson.Gson", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        IdUtils.mapIdToObject("2n:V:5", (Class<?>) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Class<Double> class0 = Double.class;
      // Undeclared exception!
      try { 
        IdUtils.mapIdToObject(class0, class0);
      } catch(IllegalArgumentException e) {
         //
         // object is not an instance of java.lang.Double
         //
         verifyException("java.lang.reflect.AccessibleObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        IdUtils.getIdTypeFromModel((Class<?>) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        IdUtils.getIdField((Class<?>) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      try { 
        IdUtils.extractIdValue((Object) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Class<Object> class0 = Object.class;
      Field field0 = IdUtils.getIdField(class0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Class<String> class0 = String.class;
      Class<?> class1 = IdUtils.getIdTypeFromModel(class0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Class<Object> class0 = Object.class;
      Class<?> class1 = IdUtils.getIdTypeFromModel(class0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Class<String> class0 = String.class;
      Map<String, Object> map0 = IdUtils.mapIdToObject((Object) null, class0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Class<Field> class0 = Field.class;
      Class<Integer> class1 = Integer.class;
      Field field0 = IdUtils.getIdField(class1);
      Map<String, Object> map0 = IdUtils.mapIdToObject(field0, class0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Class<String> class0 = String.class;
      Object object0 = IdUtils.convertId(class0, (String) null);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Object object0 = IdUtils.convertId((Class<?>) null, "OJ%>Wfi&XrJ}%ciF");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Class<Field> class0 = Field.class;
      Object object0 = IdUtils.convertId(class0, "DxF#z5V0RN]ozcao(");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Class<Double> class0 = Double.class;
      Field field0 = IdUtils.getIdField(class0);
      Object object0 = IdUtils.extractIdValue(field0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Object object0 = new Object();
      Object object1 = IdUtils.extractIdValue(object0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      try { 
        IdUtils.extractIdValue("null");
      } catch(IllegalArgumentException e) {
         //
         // non-null object for private static final java.io.ObjectStreamField[] java.lang.String.serialPersistentFields
         //
         verifyException("java.lang.reflect.AccessibleObject", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Class<String> class0 = String.class;
      String string0 = IdUtils.mapObjectToId("", class0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      IdUtils idUtils0 = new IdUtils();
  }
}
