/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 14:33:24 GMT 2026
 */

package com.scaleguard.server.db;

import org.junit.Test;
import static org.junit.Assert.*;
import com.scaleguard.server.db.ApplicationEntry;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ApplicationEntry_ESTest extends ApplicationEntry_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setUts(1319L);
      long long0 = applicationEntry0.getUts();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setName("");
      String string0 = applicationEntry0.getName();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setMts(1093L);
      long long0 = applicationEntry0.getMts();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setMts((-2250L));
      long long0 = applicationEntry0.getMts();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setId("");
      String string0 = applicationEntry0.getId();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setDescription("9=LnT*MwUI6TrPhYp");
      String string0 = applicationEntry0.getDescription();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setDescription("");
      String string0 = applicationEntry0.getDescription();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setId("9Y2H");
      String string0 = applicationEntry0.getId();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      String string0 = applicationEntry0.getDescription();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setUts((-2250L));
      long long0 = applicationEntry0.getUts();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      applicationEntry0.setName("com.scaleguard.server.db.ApplicationEntry");
      String string0 = applicationEntry0.getName();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      String string0 = applicationEntry0.getName();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      String string0 = applicationEntry0.getId();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      long long0 = applicationEntry0.getMts();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ApplicationEntry applicationEntry0 = new ApplicationEntry();
      long long0 = applicationEntry0.getUts();
  }
}
