/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 19 03:33:44 GMT 2026
 */

package pdev.com.agenda.api.response;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import pdev.com.agenda.api.response.PacienteResponse;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PacienteResponse_ESTest extends PacienteResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      String string0 = pacienteResponse0.getSobrenome();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Long long0 = new Long(0L);
      PacienteResponse pacienteResponse0 = new PacienteResponse(long0, "'5$t/", "xwWGwG", "'5$t/", "'5$t/");
      pacienteResponse0.setSobrenome("");
      String string0 = pacienteResponse0.getSobrenome();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      pacienteResponse0.setNome("i;C");
      String string0 = pacienteResponse0.getNome();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      Long long0 = new Long(0L);
      pacienteResponse0.setId(long0);
      Long long1 = pacienteResponse0.getId();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse((Long) null, "KF m", "", "", "#1(1$KqTj#|@YL_");
      Long long0 = new Long(1312L);
      pacienteResponse0.setId(long0);
      Long long1 = pacienteResponse0.getId();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      Long long0 = new Long((-730L));
      pacienteResponse0.setId(long0);
      Long long1 = pacienteResponse0.getId();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      pacienteResponse0.setEmail("JW\"<j>?2oL|onF-8;");
      String string0 = pacienteResponse0.getEmail();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      pacienteResponse0.setEmail("");
      String string0 = pacienteResponse0.getEmail();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      pacienteResponse0.setCpf("Eq+^BQ^h");
      String string0 = pacienteResponse0.getCpf();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      pacienteResponse0.setCpf("");
      String string0 = pacienteResponse0.getCpf();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      String string0 = pacienteResponse0.getCpf();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Long long0 = new Long(0L);
      PacienteResponse pacienteResponse0 = new PacienteResponse(long0, "'5$t/", "xwWGwG", "'5$t/", "'5$t/");
      String string0 = pacienteResponse0.getSobrenome();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      String string0 = pacienteResponse0.getNome();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      String string0 = pacienteResponse0.getEmail();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      Long long0 = pacienteResponse0.getId();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PacienteResponse pacienteResponse0 = new PacienteResponse();
      pacienteResponse0.setNome("");
      String string0 = pacienteResponse0.getNome();
  }
}
