/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 08 01:04:39 GMT 2026
 */

package com.cecilireid.springchallenges;

import org.junit.Test;
import static org.junit.Assert.*;
import com.cecilireid.springchallenges.CateringJob;
import com.cecilireid.springchallenges.Status;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CateringJob_ESTest extends CateringJob_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setNoOfGuests(59);
      int int0 = cateringJob0.hashCode();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setNoOfGuests(1);
      CateringJob cateringJob1 = new CateringJob();
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Status status0 = Status.COMPLETED;
      cateringJob0.setStatus(status0);
      Status status1 = cateringJob0.getStatus();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setPhoneNumber("ddZ");
      String string0 = cateringJob0.getPhoneNumber();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setPhoneNumber("");
      String string0 = cateringJob0.getPhoneNumber();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setNoOfGuests(3769);
      int int0 = cateringJob0.getNoOfGuests();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setNoOfGuests((-2188));
      int int0 = cateringJob0.getNoOfGuests();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setMenu("Sxs3;HsM%\"}@#zoH");
      String string0 = cateringJob0.getMenu();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setMenu("");
      String string0 = cateringJob0.getMenu();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Long long0 = new Long(0L);
      cateringJob0.setId(long0);
      Long long1 = cateringJob0.getId();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Long long0 = new Long(3283L);
      cateringJob0.setId(long0);
      Long long1 = cateringJob0.getId();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Long long0 = new Long((-137L));
      cateringJob0.setId(long0);
      Long long1 = cateringJob0.getId();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setEmail("$VALUES");
      String string0 = cateringJob0.getEmail();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setEmail("");
      String string0 = cateringJob0.getEmail();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setCustomerName("wnUOQP>|Q2nx3E+ZCn");
      String string0 = cateringJob0.getCustomerName();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setCustomerName("");
      String string0 = cateringJob0.getCustomerName();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      boolean boolean0 = cateringJob0.canEqual(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      boolean boolean0 = cateringJob0.canEqual("");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      String string0 = cateringJob0.getMenu();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Status status0 = cateringJob0.getStatus();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      String string0 = cateringJob0.getCustomerName();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      String string0 = cateringJob0.getPhoneNumber();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      int int0 = cateringJob0.getNoOfGuests();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Long long0 = cateringJob0.getId();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      String string0 = cateringJob0.getEmail();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      Status status0 = Status.NOT_STARTED;
      cateringJob0.setStatus(status0);
      cateringJob1.setStatus(status0);
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Status status0 = Status.CANCELED;
      cateringJob0.setStatus(status0);
      CateringJob cateringJob1 = new CateringJob();
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      Status status0 = Status.NOT_STARTED;
      cateringJob0.setStatus(status0);
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setMenu("");
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setMenu("");
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setMenu("");
      CateringJob cateringJob1 = new CateringJob();
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setMenu("");
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setEmail("");
      CateringJob cateringJob1 = new CateringJob();
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      cateringJob0.setEmail("r");
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setPhoneNumber("?o`9Fe;&`![*q*EH");
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setPhoneNumber("");
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      cateringJob0.setCustomerName("Hkhy\"Z7r7G9?YSV");
      cateringJob1.setCustomerName("Hkhy\"Z7r7G9?YSV");
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setCustomerName("");
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setCustomerName("");
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      CateringJob cateringJob1 = new CateringJob();
      Long long0 = new Long((-1L));
      cateringJob1.setId(long0);
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Long long0 = new Long(0L);
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setId(long0);
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setNoOfGuests((-1));
      CateringJob cateringJob1 = new CateringJob();
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      boolean boolean0 = cateringJob0.equals("CateringJob(id=null, customerName=null, phoneNumber=null, email=null, menu=null, noOfGuests=0, status=null)");
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      boolean boolean0 = cateringJob0.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Status status0 = Status.CANCELED;
      cateringJob0.setStatus(status0);
      int int0 = cateringJob0.hashCode();
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setEmail("r");
      int int0 = cateringJob0.hashCode();
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setPhoneNumber("ddZ");
      int int0 = cateringJob0.hashCode();
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Long long0 = new Long((-1L));
      cateringJob0.setId(long0);
      int int0 = cateringJob0.hashCode();
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setEmail("b7@XEHR");
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setEmail("b7@XEHR");
      boolean boolean0 = cateringJob0.equals(cateringJob1);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      String string0 = cateringJob0.toString();
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setPhoneNumber("");
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setPhoneNumber("");
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setCustomerName("");
      int int0 = cateringJob0.hashCode();
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      cateringJob0.setMenu("");
      int int0 = cateringJob0.hashCode();
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      CateringJob cateringJob0 = new CateringJob();
      Long long0 = new Long(0L);
      cateringJob0.setId(long0);
      CateringJob cateringJob1 = new CateringJob();
      cateringJob1.setId(long0);
      boolean boolean0 = cateringJob1.equals(cateringJob0);
  }
}
